// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: auths.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthLoginService_AuthLogin_FullMethodName = "/pb.AuthLoginService/AuthLogin"
)

// AuthLoginServiceClient is the client API for AuthLoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthLoginServiceClient interface {
	AuthLogin(ctx context.Context, in *AuthLoginREQ, opts ...grpc.CallOption) (*AuthLoginRSP, error)
}

type authLoginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthLoginServiceClient(cc grpc.ClientConnInterface) AuthLoginServiceClient {
	return &authLoginServiceClient{cc}
}

func (c *authLoginServiceClient) AuthLogin(ctx context.Context, in *AuthLoginREQ, opts ...grpc.CallOption) (*AuthLoginRSP, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthLoginRSP)
	err := c.cc.Invoke(ctx, AuthLoginService_AuthLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthLoginServiceServer is the server API for AuthLoginService service.
// All implementations must embed UnimplementedAuthLoginServiceServer
// for forward compatibility.
type AuthLoginServiceServer interface {
	AuthLogin(context.Context, *AuthLoginREQ) (*AuthLoginRSP, error)
	mustEmbedUnimplementedAuthLoginServiceServer()
}

// UnimplementedAuthLoginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthLoginServiceServer struct{}

func (UnimplementedAuthLoginServiceServer) AuthLogin(context.Context, *AuthLoginREQ) (*AuthLoginRSP, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthLogin not implemented")
}
func (UnimplementedAuthLoginServiceServer) mustEmbedUnimplementedAuthLoginServiceServer() {}
func (UnimplementedAuthLoginServiceServer) testEmbeddedByValue()                          {}

// UnsafeAuthLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthLoginServiceServer will
// result in compilation errors.
type UnsafeAuthLoginServiceServer interface {
	mustEmbedUnimplementedAuthLoginServiceServer()
}

func RegisterAuthLoginServiceServer(s grpc.ServiceRegistrar, srv AuthLoginServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthLoginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthLoginService_ServiceDesc, srv)
}

func _AuthLoginService_AuthLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthLoginREQ)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthLoginServiceServer).AuthLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthLoginService_AuthLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthLoginServiceServer).AuthLogin(ctx, req.(*AuthLoginREQ))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthLoginService_ServiceDesc is the grpc.ServiceDesc for AuthLoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthLoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AuthLoginService",
	HandlerType: (*AuthLoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthLogin",
			Handler:    _AuthLoginService_AuthLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auths.proto",
}
