// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.11
// source: micro.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMD int32

const (
	CMD_NONE   CMD = 0
	CMD_MAIN   CMD = 1
	CMD_LOGIN  CMD = 2
	CMD_PLAYER CMD = 3
	CMD_PACK   CMD = 4
	CMD_TASK   CMD = 5
	CMD_HERO   CMD = 6
	CMD_EQUIP  CMD = 7
)

// Enum value maps for CMD.
var (
	CMD_name = map[int32]string{
		0: "NONE",
		1: "MAIN",
		2: "LOGIN",
		3: "PLAYER",
		4: "PACK",
		5: "TASK",
		6: "HERO",
		7: "EQUIP",
	}
	CMD_value = map[string]int32{
		"NONE":   0,
		"MAIN":   1,
		"LOGIN":  2,
		"PLAYER": 3,
		"PACK":   4,
		"TASK":   5,
		"HERO":   6,
		"EQUIP":  7,
	}
)

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}

func (x CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_proto_enumTypes[0].Descriptor()
}

func (CMD) Type() protoreflect.EnumType {
	return &file_micro_proto_enumTypes[0]
}

func (x CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD.Descriptor instead.
func (CMD) EnumDescriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{0}
}

type ACT int32

const (
	ACT_ACT_NONE            ACT = 0
	ACT_LOGIN_BY_SESSION    ACT = 1
	ACT_LOGIN_OUT           ACT = 2
	ACT_LOGIN_RECONNECT     ACT = 3
	ACT_LOGIN_SWITCH_SERVER ACT = 4
	ACT_MAIN_GM             ACT = 1
	ACT_PACK_SUB            ACT = 1
)

// Enum value maps for ACT.
var (
	ACT_name = map[int32]string{
		0: "ACT_NONE",
		1: "LOGIN_BY_SESSION",
		2: "LOGIN_OUT",
		3: "LOGIN_RECONNECT",
		4: "LOGIN_SWITCH_SERVER",
		// Duplicate value: 1: "MAIN_GM",
		// Duplicate value: 1: "PACK_SUB",
	}
	ACT_value = map[string]int32{
		"ACT_NONE":            0,
		"LOGIN_BY_SESSION":    1,
		"LOGIN_OUT":           2,
		"LOGIN_RECONNECT":     3,
		"LOGIN_SWITCH_SERVER": 4,
		"MAIN_GM":             1,
		"PACK_SUB":            1,
	}
)

func (x ACT) Enum() *ACT {
	p := new(ACT)
	*p = x
	return p
}

func (x ACT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACT) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_proto_enumTypes[1].Descriptor()
}

func (ACT) Type() protoreflect.EnumType {
	return &file_micro_proto_enumTypes[1]
}

func (x ACT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACT.Descriptor instead.
func (ACT) EnumDescriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{1}
}

var File_micro_proto protoreflect.FileDescriptor

var file_micro_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x2a, 0x59, 0x0a, 0x03, 0x43, 0x4d, 0x44, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x4c, 0x41, 0x59, 0x45,
	0x52, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x43, 0x4b, 0x10, 0x04, 0x12, 0x08, 0x0a,
	0x04, 0x54, 0x41, 0x53, 0x4b, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x45, 0x52, 0x4f, 0x10,
	0x06, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x51, 0x55, 0x49, 0x50, 0x10, 0x07, 0x2a, 0x85, 0x01, 0x0a,
	0x03, 0x41, 0x43, 0x54, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x42, 0x59, 0x5f, 0x53,
	0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x4f, 0x47, 0x49,
	0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x4f, 0x47, 0x49, 0x4e,
	0x5f, 0x52, 0x45, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x53, 0x57, 0x49, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x45, 0x52,
	0x56, 0x45, 0x52, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x41, 0x49, 0x4e, 0x5f, 0x47, 0x4d,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x41, 0x43, 0x4b, 0x5f, 0x53, 0x55, 0x42, 0x10, 0x01,
	0x1a, 0x02, 0x10, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_micro_proto_rawDescOnce sync.Once
	file_micro_proto_rawDescData = file_micro_proto_rawDesc
)

func file_micro_proto_rawDescGZIP() []byte {
	file_micro_proto_rawDescOnce.Do(func() {
		file_micro_proto_rawDescData = protoimpl.X.CompressGZIP(file_micro_proto_rawDescData)
	})
	return file_micro_proto_rawDescData
}

var file_micro_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_micro_proto_goTypes = []any{
	(CMD)(0), // 0: pb.CMD
	(ACT)(0), // 1: pb.ACT
}
var file_micro_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_micro_proto_init() }
func file_micro_proto_init() {
	if File_micro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_micro_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_micro_proto_goTypes,
		DependencyIndexes: file_micro_proto_depIdxs,
		EnumInfos:         file_micro_proto_enumTypes,
	}.Build()
	File_micro_proto = out.File
	file_micro_proto_rawDesc = nil
	file_micro_proto_goTypes = nil
	file_micro_proto_depIdxs = nil
}
