
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;

const (
    /**
     * 无
     */
    ActivityType_None = 0;
    /**
     * 商城
     */
    ActivityType_Shop = 1;
    /**
     * 社区
     */
    ActivityType_Discard = 2;
    /**
     * 梦想通行证
     */
    ActivityType_DreamPass = 3;
    /**
     * 免广告
     */
    ActivityType_Adfree = 5;
    /**
     * 无尽宝藏
     */
    ActivityType_UntoldTreasure = 6;
    /**
     * 新手礼包
     */
    ActivityType_NewPlayerPack = 7;
    /**
     * VIP订阅
     */
    ActivityType_VIP = 8;
    /**
     * 抽卡
     */
    ActivityType_Gacha = 9;
    /**
     * 七日签到
     */
    ActivityType_DayCheckIn = 10;
    /**
     * 广告获得钻石
     */
    ActivityType_ADToDiamond = 11;
    /**
     * 每日礼包
     */
    ActivityType_DailyGift = 12;
)

