
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type AttributeExpression struct {
    Id int32
    Expression string
}

const TypeId_AttributeExpression = -459715020

func (*AttributeExpression) GetTypeId() int32 {
    return -459715020
}

func NewAttributeExpression(_buf map[string]interface{}) (_v *AttributeExpression, err error) {
    _v = &AttributeExpression{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_Expression__ interface{}; if __json_Expression__, _ok_ = _buf["Expression"]; !_ok_ || __json_Expression__ == nil { err = errors.New("Expression error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_Expression__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Expression = __x__ }}
    return
}

