
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type AttributeRetrieval struct {
    Id int32
    Param interface{}
}

const TypeId_AttributeRetrieval = 961619992

func (*AttributeRetrieval) GetTypeId() int32 {
    return 961619992
}

func NewAttributeRetrieval(_buf map[string]interface{}) (_v *AttributeRetrieval, err error) {
    _v = &AttributeRetrieval{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_Param__ interface{}; if __json_Param__, _ok_ = _buf["Param"]; !_ok_ || __json_Param__ == nil { err = errors.New("Param error"); return } else { var __x__ interface{};  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_Param__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewRetrievalBase(_x_); err != nil { return } }; _v.Param = __x__ }}
    return
}

