
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type AutoTbAuto struct {
    _dataMap map[int32]*AutoAuto
    _dataList []*AutoAuto
}

func NewAutoTbAuto(_buf []map[string]interface{}) (*AutoTbAuto, error) {
    _dataList := make([]*AutoAuto, 0, len(_buf))
    dataMap := make(map[int32]*AutoAuto)

    for _, _ele_ := range _buf {
        if _v, err2 := NewAutoAuto(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &AutoTbAuto{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *AutoTbAuto) GetDataMap() map[int32]*AutoAuto {
    return table._dataMap
}

func (table *AutoTbAuto) GetDataList() []*AutoAuto {
    return table._dataList
}

func (table *AutoTbAuto) Get(key int32) *AutoAuto {
    return table._dataMap[key]
}


