
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type AutoAuto struct {
    Id int32
    AutoSpeed float32
    AutoLv int32
    AutoTime int32
    GetWay int32
    Spd float32
    AutoSpd float32
    Name string
}

const TypeId_AutoAuto = 1614537390

func (*AutoAuto) GetTypeId() int32 {
    return 1614537390
}

func NewAutoAuto(_buf map[string]interface{}) (_v *AutoAuto, err error) {
    _v = &AutoAuto{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_auto_speed__ interface{}; if __json_auto_speed__, _ok_ = _buf["auto_speed"]; !_ok_ || __json_auto_speed__ == nil { err = errors.New("auto_speed error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_auto_speed__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.AutoSpeed = __x__ }}
    { var _ok_ bool; var __json_auto_lv__ interface{}; if __json_auto_lv__, _ok_ = _buf["auto_lv"]; !_ok_ || __json_auto_lv__ == nil { err = errors.New("auto_lv error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_auto_lv__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AutoLv = __x__ }}
    { var _ok_ bool; var __json_auto_time__ interface{}; if __json_auto_time__, _ok_ = _buf["auto_time"]; !_ok_ || __json_auto_time__ == nil { err = errors.New("auto_time error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_auto_time__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AutoTime = __x__ }}
    { var _ok_ bool; var __json_get_way__ interface{}; if __json_get_way__, _ok_ = _buf["get_way"]; !_ok_ || __json_get_way__ == nil { err = errors.New("get_way error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_get_way__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.GetWay = __x__ }}
    { var _ok_ bool; var __json_spd__ interface{}; if __json_spd__, _ok_ = _buf["spd"]; !_ok_ || __json_spd__ == nil { err = errors.New("spd error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_spd__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Spd = __x__ }}
    { var _ok_ bool; var __json_auto_spd__ interface{}; if __json_auto_spd__, _ok_ = _buf["auto_spd"]; !_ok_ || __json_auto_spd__ == nil { err = errors.New("auto_spd error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_auto_spd__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.AutoSpd = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    return
}

