
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;

/**
 * [M8.3] 效果类型(Buff/技能共享)
 */
const (
    /**
     * 造成伤害
     */
    BattleEffectType_Damage = 0;
    /**
     * 治疗
     */
    BattleEffectType_Heal = 1;
    /**
     * 护盾
     */
    BattleEffectType_Shield = 2;
    /**
     * 修改属性
     */
    BattleEffectType_ModifyAttribute = 3;
    /**
     * 控制
     */
    BattleEffectType_Control = 4;
    /**
     * 添加Buff
     */
    BattleEffectType_AddBuff = 5;
    /**
     * 移除Buff
     */
    BattleEffectType_RemoveBuff = 6;
    /**
     * 驱散
     */
    BattleEffectType_Dispel = 7;
)

