
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;

/**
 * [M8.3] 效果目标
 */
const (
    /**
     * Buff携带者
     */
    BattleEffectTarget_Owner = 0;
    /**
     * 施法者
     */
    BattleEffectTarget_Caster = 1;
    /**
     * 敌方
     */
    BattleEffectTarget_Enemies = 2;
    /**
     * 友方
     */
    BattleEffectTarget_Allies = 3;
    /**
     * 全场
     */
    BattleEffectTarget_All = 4;
    /**
     * 随机一名敌人
     */
    BattleEffectTarget_RandomEnemy = 5;
    /**
     * 前排敌人
     */
    BattleEffectTarget_FrontEnemy = 6;
)

