
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;

/**
 * [M8.3] 属性操作
 */
const (
    /**
     * 附加decorator
     */
    BattleAttrOp_Add = 0;
    /**
     * 乘比例
     */
    BattleAttrOp_Multiply = 1;
    /**
     * 覆盖
     */
    BattleAttrOp_Cover = 2;
    /**
     * 移除decorator
     */
    BattleAttrOp_Remove = 3;
)

