
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type BattleTbBattle struct {
    _dataMap map[int32]*BattleBattle
    _dataList []*BattleBattle
}

func NewBattleTbBattle(_buf []map[string]interface{}) (*BattleTbBattle, error) {
    _dataList := make([]*BattleBattle, 0, len(_buf))
    dataMap := make(map[int32]*BattleBattle)

    for _, _ele_ := range _buf {
        if _v, err2 := NewBattleBattle(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &BattleTbBattle{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *BattleTbBattle) GetDataMap() map[int32]*BattleBattle {
    return table._dataMap
}

func (table *BattleTbBattle) GetDataList() []*BattleBattle {
    return table._dataList
}

func (table *BattleTbBattle) Get(key int32) *BattleBattle {
    return table._dataMap[key]
}


