
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Book_confBookConf struct {
    Id int32
    Name string
    NickName string
    Atk int32
    DefId int32
    Hp int64
    Spd int32
    Level int32
    Star int32
    Stage int32
    Zhanli int64
}

const TypeId_Book_confBookConf = 1771532929

func (*Book_confBookConf) GetTypeId() int32 {
    return 1771532929
}

func NewBook_confBookConf(_buf map[string]interface{}) (_v *Book_confBookConf, err error) {
    _v = &Book_confBookConf{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_nick_name__ interface{}; if __json_nick_name__, _ok_ = _buf["nick_name"]; !_ok_ || __json_nick_name__ == nil { err = errors.New("nick_name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_nick_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.NickName = __x__ }}
    { var _ok_ bool; var __json_atk__ interface{}; if __json_atk__, _ok_ = _buf["atk"]; !_ok_ || __json_atk__ == nil { err = errors.New("atk error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_atk__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Atk = __x__ }}
    { var _ok_ bool; var __json_def_id__ interface{}; if __json_def_id__, _ok_ = _buf["def_id"]; !_ok_ || __json_def_id__ == nil { err = errors.New("def_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_def_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DefId = __x__ }}
    { var _ok_ bool; var __json_hp__ interface{}; if __json_hp__, _ok_ = _buf["hp"]; !_ok_ || __json_hp__ == nil { err = errors.New("hp error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hp__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Hp = __x__ }}
    { var _ok_ bool; var __json_spd__ interface{}; if __json_spd__, _ok_ = _buf["spd"]; !_ok_ || __json_spd__ == nil { err = errors.New("spd error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_spd__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Spd = __x__ }}
    { var _ok_ bool; var __json_level__ interface{}; if __json_level__, _ok_ = _buf["level"]; !_ok_ || __json_level__ == nil { err = errors.New("level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Level = __x__ }}
    { var _ok_ bool; var __json_star__ interface{}; if __json_star__, _ok_ = _buf["star"]; !_ok_ || __json_star__ == nil { err = errors.New("star error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_star__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Star = __x__ }}
    { var _ok_ bool; var __json_stage__ interface{}; if __json_stage__, _ok_ = _buf["stage"]; !_ok_ || __json_stage__ == nil { err = errors.New("stage error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_stage__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Stage = __x__ }}
    { var _ok_ bool; var __json_zhanli__ interface{}; if __json_zhanli__, _ok_ = _buf["zhanli"]; !_ok_ || __json_zhanli__ == nil { err = errors.New("zhanli error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_zhanli__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.Zhanli = __x__ }}
    return
}

