
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Book_confTbBookConf struct {
    _dataMap map[int32]*Book_confBookConf
    _dataList []*Book_confBookConf
}

func NewBook_confTbBookConf(_buf []map[string]interface{}) (*Book_confTbBookConf, error) {
    _dataList := make([]*Book_confBookConf, 0, len(_buf))
    dataMap := make(map[int32]*Book_confBookConf)

    for _, _ele_ := range _buf {
        if _v, err2 := NewBook_confBookConf(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Book_confTbBookConf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Book_confTbBookConf) GetDataMap() map[int32]*Book_confBookConf {
    return table._dataMap
}

func (table *Book_confTbBookConf) GetDataList() []*Book_confBookConf {
    return table._dataList
}

func (table *Book_confTbBookConf) Get(key int32) *Book_confBookConf {
    return table._dataMap[key]
}


