
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type BoxTbBox struct {
    _dataMap map[int32]*BoxBox
    _dataList []*BoxBox
}

func NewBoxTbBox(_buf []map[string]interface{}) (*BoxTbBox, error) {
    _dataList := make([]*BoxBox, 0, len(_buf))
    dataMap := make(map[int32]*BoxBox)

    for _, _ele_ := range _buf {
        if _v, err2 := NewBoxBox(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &BoxTbBox{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *BoxTbBox) GetDataMap() map[int32]*BoxBox {
    return table._dataMap
}

func (table *BoxTbBox) GetDataList() []*BoxBox {
    return table._dataList
}

func (table *BoxTbBox) Get(key int32) *BoxBox {
    return table._dataMap[key]
}


