
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type BoxBox struct {
    Id int32
    Name string
    Des string
    ImgPath string
    Rewards string
    Score int32
}

const TypeId_BoxBox = 71143176

func (*BoxBox) GetTypeId() int32 {
    return 71143176
}

func NewBoxBox(_buf map[string]interface{}) (_v *BoxBox, err error) {
    _v = &BoxBox{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_des__ interface{}; if __json_des__, _ok_ = _buf["des"]; !_ok_ || __json_des__ == nil { err = errors.New("des error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_des__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Des = __x__ }}
    { var _ok_ bool; var __json_img_path__ interface{}; if __json_img_path__, _ok_ = _buf["img_path"]; !_ok_ || __json_img_path__ == nil { err = errors.New("img_path error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_img_path__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ImgPath = __x__ }}
    { var _ok_ bool; var __json_rewards__ interface{}; if __json_rewards__, _ok_ = _buf["rewards"]; !_ok_ || __json_rewards__ == nil { err = errors.New("rewards error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_rewards__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Rewards = __x__ }}
    { var _ok_ bool; var __json_score__ interface{}; if __json_score__, _ok_ = _buf["score"]; !_ok_ || __json_score__ == nil { err = errors.New("score error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_score__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Score = __x__ }}
    return
}

