
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Box_stageBoxStage struct {
    Id int32
    PathLiang string
    PathAn string
    Limit int32
    Des string
    KeyId int32
}

const TypeId_Box_stageBoxStage = 961842679

func (*Box_stageBoxStage) GetTypeId() int32 {
    return 961842679
}

func NewBox_stageBoxStage(_buf map[string]interface{}) (_v *Box_stageBoxStage, err error) {
    _v = &Box_stageBoxStage{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_path_liang__ interface{}; if __json_path_liang__, _ok_ = _buf["path_liang"]; !_ok_ || __json_path_liang__ == nil { err = errors.New("path_liang error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_path_liang__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PathLiang = __x__ }}
    { var _ok_ bool; var __json_path_an__ interface{}; if __json_path_an__, _ok_ = _buf["path_an"]; !_ok_ || __json_path_an__ == nil { err = errors.New("path_an error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_path_an__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PathAn = __x__ }}
    { var _ok_ bool; var __json_limit__ interface{}; if __json_limit__, _ok_ = _buf["limit"]; !_ok_ || __json_limit__ == nil { err = errors.New("limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Limit = __x__ }}
    { var _ok_ bool; var __json_des__ interface{}; if __json_des__, _ok_ = _buf["des"]; !_ok_ || __json_des__ == nil { err = errors.New("des error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_des__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Des = __x__ }}
    { var _ok_ bool; var __json_key_id__ interface{}; if __json_key_id__, _ok_ = _buf["key_id"]; !_ok_ || __json_key_id__ == nil { err = errors.New("key_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_key_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.KeyId = __x__ }}
    return
}

