
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type BuffBuff struct {
    Id int32
    Name string
    Describe string
    IconPath string
    Gain int32
    Overlying int32
    Tip string
    EffectBuff string
    Tags string
    Duration int32
    StackPolicy int32
    UniqueGroup string
    EffectIds string
    CustomHandler string
}

const TypeId_BuffBuff = 9300270

func (*BuffBuff) GetTypeId() int32 {
    return 9300270
}

func NewBuffBuff(_buf map[string]interface{}) (_v *BuffBuff, err error) {
    _v = &BuffBuff{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_describe__ interface{}; if __json_describe__, _ok_ = _buf["describe"]; !_ok_ || __json_describe__ == nil { err = errors.New("describe error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_describe__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Describe = __x__ }}
    { var _ok_ bool; var __json_icon_path__ interface{}; if __json_icon_path__, _ok_ = _buf["icon_path"]; !_ok_ || __json_icon_path__ == nil { err = errors.New("icon_path error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_icon_path__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IconPath = __x__ }}
    { var _ok_ bool; var __json_gain__ interface{}; if __json_gain__, _ok_ = _buf["gain"]; !_ok_ || __json_gain__ == nil { err = errors.New("gain error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_gain__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Gain = __x__ }}
    { var _ok_ bool; var __json_overlying__ interface{}; if __json_overlying__, _ok_ = _buf["overlying"]; !_ok_ || __json_overlying__ == nil { err = errors.New("overlying error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_overlying__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Overlying = __x__ }}
    { var _ok_ bool; var __json_tip__ interface{}; if __json_tip__, _ok_ = _buf["tip"]; !_ok_ || __json_tip__ == nil { err = errors.New("tip error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_tip__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Tip = __x__ }}
    { var _ok_ bool; var __json_effect_buff__ interface{}; if __json_effect_buff__, _ok_ = _buf["effect_buff"]; !_ok_ || __json_effect_buff__ == nil { err = errors.New("effect_buff error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_effect_buff__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.EffectBuff = __x__ }}
    { var _ok_ bool; var __json_tags__ interface{}; if __json_tags__, _ok_ = _buf["tags"]; !_ok_ || __json_tags__ == nil { err = errors.New("tags error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_tags__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Tags = __x__ }}
    { var _ok_ bool; var __json_duration__ interface{}; if __json_duration__, _ok_ = _buf["duration"]; !_ok_ || __json_duration__ == nil { err = errors.New("duration error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_duration__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Duration = __x__ }}
    { var _ok_ bool; var __json_stack_policy__ interface{}; if __json_stack_policy__, _ok_ = _buf["stack_policy"]; !_ok_ || __json_stack_policy__ == nil { err = errors.New("stack_policy error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_stack_policy__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StackPolicy = __x__ }}
    { var _ok_ bool; var __json_unique_group__ interface{}; if __json_unique_group__, _ok_ = _buf["unique_group"]; !_ok_ || __json_unique_group__ == nil { err = errors.New("unique_group error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_unique_group__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.UniqueGroup = __x__ }}
    { var _ok_ bool; var __json_effect_ids__ interface{}; if __json_effect_ids__, _ok_ = _buf["effect_ids"]; !_ok_ || __json_effect_ids__ == nil { err = errors.New("effect_ids error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_effect_ids__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.EffectIds = __x__ }}
    { var _ok_ bool; var __json_custom_handler__ interface{}; if __json_custom_handler__, _ok_ = _buf["custom_handler"]; !_ok_ || __json_custom_handler__ == nil { err = errors.New("custom_handler error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_custom_handler__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CustomHandler = __x__ }}
    return
}

