
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;

/**
 * [M8.3] Buff 标签
 */
const (
    /**
     * 减益
     */
    BuffTag_Debuff = 0;
    /**
     * 增益
     */
    BuffTag_Buff = 1;
    /**
     * 流血/中毒/灼烧
     */
    BuffTag_DoT = 2;
    /**
     * 治疗
     */
    BuffTag_Heal = 3;
    /**
     * 冰冻/眩晕/沉默
     */
    BuffTag_Control = 4;
    /**
     * 流血
     */
    BuffTag_Bleed = 5;
    /**
     * 灼烧
     */
    BuffTag_Burn = 6;
    /**
     * 中毒
     */
    BuffTag_Poison = 7;
    /**
     * 冰冻
     */
    BuffTag_Frozen = 8;
    /**
     * 眩晕
     */
    BuffTag_Stun = 9;
    /**
     * 沉默
     */
    BuffTag_Silence = 10;
    /**
     * 冰冻/眩晕共有
     */
    BuffTag_CannotAct = 11;
    /**
     * 属性修改
     */
    BuffTag_Attribute = 12;
    /**
     * 护盾
     */
    BuffTag_Shield = 13;
)

