
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Buff_effectBuffEffect struct {
    Id int32
    Trigger string
    EffectType int32
    Target int32
    Formula string
    Attr string
    Op string
    DamageType string
    Value int32
    ExtraBuffId int32
}

const TypeId_Buff_effectBuffEffect = 941777781

func (*Buff_effectBuffEffect) GetTypeId() int32 {
    return 941777781
}

func NewBuff_effectBuffEffect(_buf map[string]interface{}) (_v *Buff_effectBuffEffect, err error) {
    _v = &Buff_effectBuffEffect{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_trigger__ interface{}; if __json_trigger__, _ok_ = _buf["trigger"]; !_ok_ || __json_trigger__ == nil { err = errors.New("trigger error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_trigger__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Trigger = __x__ }}
    { var _ok_ bool; var __json_effect_type__ interface{}; if __json_effect_type__, _ok_ = _buf["effect_type"]; !_ok_ || __json_effect_type__ == nil { err = errors.New("effect_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_effect_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.EffectType = __x__ }}
    { var _ok_ bool; var __json_target__ interface{}; if __json_target__, _ok_ = _buf["target"]; !_ok_ || __json_target__ == nil { err = errors.New("target error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_target__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Target = __x__ }}
    { var _ok_ bool; var __json_formula__ interface{}; if __json_formula__, _ok_ = _buf["formula"]; !_ok_ || __json_formula__ == nil { err = errors.New("formula error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_formula__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Formula = __x__ }}
    { var _ok_ bool; var __json_attr__ interface{}; if __json_attr__, _ok_ = _buf["attr"]; !_ok_ || __json_attr__ == nil { err = errors.New("attr error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_attr__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Attr = __x__ }}
    { var _ok_ bool; var __json_op__ interface{}; if __json_op__, _ok_ = _buf["op"]; !_ok_ || __json_op__ == nil { err = errors.New("op error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_op__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Op = __x__ }}
    { var _ok_ bool; var __json_damage_type__ interface{}; if __json_damage_type__, _ok_ = _buf["damage_type"]; !_ok_ || __json_damage_type__ == nil { err = errors.New("damage_type error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_damage_type__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.DamageType = __x__ }}
    { var _ok_ bool; var __json_value__ interface{}; if __json_value__, _ok_ = _buf["value"]; !_ok_ || __json_value__ == nil { err = errors.New("value error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_value__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Value = __x__ }}
    { var _ok_ bool; var __json_extra_buff_id__ interface{}; if __json_extra_buff_id__, _ok_ = _buf["extra_buff_id"]; !_ok_ || __json_extra_buff_id__ == nil { err = errors.New("extra_buff_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_extra_buff_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExtraBuffId = __x__ }}
    return
}

