
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Buff_formulaTbFormula struct {
    _dataMap map[string]*Buff_formulaFormula
    _dataList []*Buff_formulaFormula
}

func NewBuff_formulaTbFormula(_buf []map[string]interface{}) (*Buff_formulaTbFormula, error) {
    _dataList := make([]*Buff_formulaFormula, 0, len(_buf))
    dataMap := make(map[string]*Buff_formulaFormula)

    for _, _ele_ := range _buf {
        if _v, err2 := NewBuff_formulaFormula(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Buff_formulaTbFormula{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Buff_formulaTbFormula) GetDataMap() map[string]*Buff_formulaFormula {
    return table._dataMap
}

func (table *Buff_formulaTbFormula) GetDataList() []*Buff_formulaFormula {
    return table._dataList
}

func (table *Buff_formulaTbFormula) Get(key string) *Buff_formulaFormula {
    return table._dataMap[key]
}


