
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;

/**
 * [M8.3] 叠加策略
 */
const (
    /**
     * 刷新回合
     */
    BuffStackPolicy_Refresh = 0;
    /**
     * 叠层+回收
     */
    BuffStackPolicy_AddStack = 1;
    /**
     * 替换
     */
    BuffStackPolicy_Replace = 2;
    /**
     * 保留高优先级
     */
    BuffStackPolicy_KeepHigher = 3;
    /**
     * 暴击/暴伤/攻击叠加
     */
    BuffStackPolicy_AddStackNoRemove = 4;
)

