
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Buff_effectTbBuffEffect struct {
    _dataMap map[int32]*Buff_effectBuffEffect
    _dataList []*Buff_effectBuffEffect
}

func NewBuff_effectTbBuffEffect(_buf []map[string]interface{}) (*Buff_effectTbBuffEffect, error) {
    _dataList := make([]*Buff_effectBuffEffect, 0, len(_buf))
    dataMap := make(map[int32]*Buff_effectBuffEffect)

    for _, _ele_ := range _buf {
        if _v, err2 := NewBuff_effectBuffEffect(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Buff_effectTbBuffEffect{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Buff_effectTbBuffEffect) GetDataMap() map[int32]*Buff_effectBuffEffect {
    return table._dataMap
}

func (table *Buff_effectTbBuffEffect) GetDataList() []*Buff_effectBuffEffect {
    return table._dataList
}

func (table *Buff_effectTbBuffEffect) Get(key int32) *Buff_effectBuffEffect {
    return table._dataMap[key]
}


