
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Buff_formulaFormula struct {
    Id string
    Type int32
    ParamA string
    ParamB string
}

const TypeId_Buff_formulaFormula = 1041442002

func (*Buff_formulaFormula) GetTypeId() int32 {
    return 1041442002
}

func NewBuff_formulaFormula(_buf map[string]interface{}) (_v *Buff_formulaFormula, err error) {
    _v = &Buff_formulaFormula{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_type__ interface{}; if __json_type__, _ok_ = _buf["type"]; !_ok_ || __json_type__ == nil { err = errors.New("type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_param_a__ interface{}; if __json_param_a__, _ok_ = _buf["param_a"]; !_ok_ || __json_param_a__ == nil { err = errors.New("param_a error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_param_a__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ParamA = __x__ }}
    { var _ok_ bool; var __json_param_b__ interface{}; if __json_param_b__, _ok_ = _buf["param_b"]; !_ok_ || __json_param_b__ == nil { err = errors.New("param_b error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_param_b__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ParamB = __x__ }}
    return
}

