
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type CardTbCard struct {
    _dataMap map[int32]*CardCard
    _dataList []*CardCard
}

func NewCardTbCard(_buf []map[string]interface{}) (*CardTbCard, error) {
    _dataList := make([]*CardCard, 0, len(_buf))
    dataMap := make(map[int32]*CardCard)

    for _, _ele_ := range _buf {
        if _v, err2 := NewCardCard(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &CardTbCard{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *CardTbCard) GetDataMap() map[int32]*CardCard {
    return table._dataMap
}

func (table *CardTbCard) GetDataList() []*CardCard {
    return table._dataList
}

func (table *CardTbCard) Get(key int32) *CardCard {
    return table._dataMap[key]
}


