
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type CardCard struct {
    Id int32
    CardDay float32
    Benefit string
    Name string
    DailyReward string
    Rank int32
    BuyReward string
    ActivityID int32
    Price int32
    Path string
    Tips string
    CardDescription string
}

const TypeId_CardCard = -291760306

func (*CardCard) GetTypeId() int32 {
    return -291760306
}

func NewCardCard(_buf map[string]interface{}) (_v *CardCard, err error) {
    _v = &CardCard{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_card_day__ interface{}; if __json_card_day__, _ok_ = _buf["card_day"]; !_ok_ || __json_card_day__ == nil { err = errors.New("card_day error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_card_day__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.CardDay = __x__ }}
    { var _ok_ bool; var __json_benefit__ interface{}; if __json_benefit__, _ok_ = _buf["benefit"]; !_ok_ || __json_benefit__ == nil { err = errors.New("benefit error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_benefit__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Benefit = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_daily_reward__ interface{}; if __json_daily_reward__, _ok_ = _buf["daily_reward"]; !_ok_ || __json_daily_reward__ == nil { err = errors.New("daily_reward error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_daily_reward__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.DailyReward = __x__ }}
    { var _ok_ bool; var __json_rank__ interface{}; if __json_rank__, _ok_ = _buf["rank"]; !_ok_ || __json_rank__ == nil { err = errors.New("rank error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_rank__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Rank = __x__ }}
    { var _ok_ bool; var __json_buy_reward__ interface{}; if __json_buy_reward__, _ok_ = _buf["buy_reward"]; !_ok_ || __json_buy_reward__ == nil { err = errors.New("buy_reward error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_buy_reward__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.BuyReward = __x__ }}
    { var _ok_ bool; var __json_activity_iD__ interface{}; if __json_activity_iD__, _ok_ = _buf["activity_iD"]; !_ok_ || __json_activity_iD__ == nil { err = errors.New("activity_iD error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_activity_iD__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ActivityID = __x__ }}
    { var _ok_ bool; var __json_price__ interface{}; if __json_price__, _ok_ = _buf["price"]; !_ok_ || __json_price__ == nil { err = errors.New("price error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_price__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Price = __x__ }}
    { var _ok_ bool; var __json_path__ interface{}; if __json_path__, _ok_ = _buf["path"]; !_ok_ || __json_path__ == nil { err = errors.New("path error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_path__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Path = __x__ }}
    { var _ok_ bool; var __json_tips__ interface{}; if __json_tips__, _ok_ = _buf["tips"]; !_ok_ || __json_tips__ == nil { err = errors.New("tips error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_tips__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Tips = __x__ }}
    { var _ok_ bool; var __json_card_description__ interface{}; if __json_card_description__, _ok_ = _buf["card_description"]; !_ok_ || __json_card_description__ == nil { err = errors.New("card_description error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_card_description__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CardDescription = __x__ }}
    return
}

