
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type ChapterInfo struct {
    KeyId int32
    ChapterID int32
    DifficultLv int32
    RefPower int64
    Cost *ItemNumPair
    FirstReward []int32
    StageRewards []int32
    SweepReward []int32
    SweepAdditionalReward []int32
    StarBoxRewards []int32
}

const TypeId_ChapterInfo = -2127032709

func (*ChapterInfo) GetTypeId() int32 {
    return -2127032709
}

func NewChapterInfo(_buf map[string]interface{}) (_v *ChapterInfo, err error) {
    _v = &ChapterInfo{}
    { var _ok_ bool; var __json_KeyId__ interface{}; if __json_KeyId__, _ok_ = _buf["KeyId"]; !_ok_ || __json_KeyId__ == nil { err = errors.New("KeyId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_KeyId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.KeyId = __x__ }}
    { var _ok_ bool; var __json_ChapterID__ interface{}; if __json_ChapterID__, _ok_ = _buf["ChapterID"]; !_ok_ || __json_ChapterID__ == nil { err = errors.New("ChapterID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ChapterID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ChapterID = __x__ }}
    { var _ok_ bool; var __json_DifficultLv__ interface{}; if __json_DifficultLv__, _ok_ = _buf["DifficultLv"]; !_ok_ || __json_DifficultLv__ == nil { err = errors.New("DifficultLv error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_DifficultLv__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DifficultLv = __x__ }}
    { var _ok_ bool; var __json_RefPower__ interface{}; if __json_RefPower__, _ok_ = _buf["RefPower"]; !_ok_ || __json_RefPower__ == nil { err = errors.New("RefPower error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RefPower__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.RefPower = __x__ }}
    { var _ok_ bool; var __json_Cost__ interface{}; if __json_Cost__, _ok_ = _buf["Cost"]; !_ok_ || __json_Cost__ == nil { err = errors.New("Cost error"); return } else { var __x__ *ItemNumPair;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_Cost__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewItemNumPair(_x_); err != nil { return } }; _v.Cost = __x__ }}
    { var _ok_ bool; var __json_FirstReward__ interface{}; if __json_FirstReward__, _ok_ = _buf["FirstReward"]; !_ok_ || __json_FirstReward__ == nil { err = errors.New("FirstReward error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_FirstReward__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.FirstReward = __x__ }}
    { var _ok_ bool; var __json_StageRewards__ interface{}; if __json_StageRewards__, _ok_ = _buf["StageRewards"]; !_ok_ || __json_StageRewards__ == nil { err = errors.New("StageRewards error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_StageRewards__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.StageRewards = __x__ }}
    { var _ok_ bool; var __json_SweepReward__ interface{}; if __json_SweepReward__, _ok_ = _buf["SweepReward"]; !_ok_ || __json_SweepReward__ == nil { err = errors.New("SweepReward error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_SweepReward__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.SweepReward = __x__ }}
    { var _ok_ bool; var __json_SweepAdditionalReward__ interface{}; if __json_SweepAdditionalReward__, _ok_ = _buf["SweepAdditionalReward"]; !_ok_ || __json_SweepAdditionalReward__ == nil { err = errors.New("SweepAdditionalReward error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_SweepAdditionalReward__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.SweepAdditionalReward = __x__ }}
    { var _ok_ bool; var __json_StarBoxRewards__ interface{}; if __json_StarBoxRewards__, _ok_ = _buf["StarBoxRewards"]; !_ok_ || __json_StarBoxRewards__ == nil { err = errors.New("StarBoxRewards error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_StarBoxRewards__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.StarBoxRewards = __x__ }}
    return
}

