
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type ChapterLevel struct {
    Id int32
    LevelType int32
}

const TypeId_ChapterLevel = -1510986921

func (*ChapterLevel) GetTypeId() int32 {
    return -1510986921
}

func NewChapterLevel(_buf map[string]interface{}) (_v *ChapterLevel, err error) {
    _v = &ChapterLevel{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_LevelType__ interface{}; if __json_LevelType__, _ok_ = _buf["LevelType"]; !_ok_ || __json_LevelType__ == nil { err = errors.New("LevelType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_LevelType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LevelType = __x__ }}
    return
}

