
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type CommonKanbanMaidInteractArea struct {
    X float32
    Y float32
    Width float32
    Height float32
    VideoNames []string
}

const TypeId_CommonKanbanMaidInteractArea = 664146956

func (*CommonKanbanMaidInteractArea) GetTypeId() int32 {
    return 664146956
}

func NewCommonKanbanMaidInteractArea(_buf map[string]interface{}) (_v *CommonKanbanMaidInteractArea, err error) {
    _v = &CommonKanbanMaidInteractArea{}
    { var _ok_ bool; var __json_x__ interface{}; if __json_x__, _ok_ = _buf["x"]; !_ok_ || __json_x__ == nil { err = errors.New("x error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_x__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.X = __x__ }}
    { var _ok_ bool; var __json_y__ interface{}; if __json_y__, _ok_ = _buf["y"]; !_ok_ || __json_y__ == nil { err = errors.New("y error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_y__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Y = __x__ }}
    { var _ok_ bool; var __json_width__ interface{}; if __json_width__, _ok_ = _buf["width"]; !_ok_ || __json_width__ == nil { err = errors.New("width error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_width__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Width = __x__ }}
    { var _ok_ bool; var __json_height__ interface{}; if __json_height__, _ok_ = _buf["height"]; !_ok_ || __json_height__ == nil { err = errors.New("height error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_height__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Height = __x__ }}
    { var _ok_ bool; var __json_videoNames__ interface{}; if __json_videoNames__, _ok_ = _buf["videoNames"]; !_ok_ || __json_videoNames__ == nil { err = errors.New("videoNames error"); return } else { var __x__ []string;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_videoNames__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]string, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ string
                        {  if _list_v0_, _ok_ = _e0_.(string); !_ok_ { err = errors.New("_list_v0_ error"); return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.VideoNames = __x__ }}
    return
}

