
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type ConditionGroup struct {
    Conditions []*Condition
}

const TypeId_ConditionGroup = -1414898108

func (*ConditionGroup) GetTypeId() int32 {
    return -1414898108
}

func NewConditionGroup(_buf map[string]interface{}) (_v *ConditionGroup, err error) {
    _v = &ConditionGroup{}
    { var _ok_ bool; var __json_Conditions__ interface{}; if __json_Conditions__, _ok_ = _buf["Conditions"]; !_ok_ || __json_Conditions__ == nil { err = errors.New("Conditions error"); return } else { var __x__ []*Condition;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_Conditions__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*Condition, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *Condition
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewCondition(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Conditions = __x__ }}
    return
}

