
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Condition struct {
    Type int32
    Value int32
}

const TypeId_Condition = 1142656251

func (*Condition) GetTypeId() int32 {
    return 1142656251
}

func NewCondition(_buf map[string]interface{}) (_v *Condition, err error) {
    _v = &Condition{}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_Value__ interface{}; if __json_Value__, _ok_ = _buf["Value"]; !_ok_ || __json_Value__ == nil { err = errors.New("Value error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Value__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Value = __x__ }}
    return
}

