
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type ConfigTbCfgActivity struct {
    _dataMap map[int32]*ConfigCfgActivity
    _dataList []*ConfigCfgActivity
}

func NewConfigTbCfgActivity(_buf []map[string]interface{}) (*ConfigTbCfgActivity, error) {
    _dataList := make([]*ConfigCfgActivity, 0, len(_buf))
    dataMap := make(map[int32]*ConfigCfgActivity)

    for _, _ele_ := range _buf {
        if _v, err2 := NewConfigCfgActivity(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &ConfigTbCfgActivity{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *ConfigTbCfgActivity) GetDataMap() map[int32]*ConfigCfgActivity {
    return table._dataMap
}

func (table *ConfigTbCfgActivity) GetDataList() []*ConfigCfgActivity {
    return table._dataList
}

func (table *ConfigTbCfgActivity) Get(key int32) *ConfigCfgActivity {
    return table._dataMap[key]
}


