
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type ConfigTbCfgKanbanMaid struct {
    _dataMap map[int32]*ConfigCfgKanbanMaid
    _dataList []*ConfigCfgKanbanMaid
}

func NewConfigTbCfgKanbanMaid(_buf []map[string]interface{}) (*ConfigTbCfgKanbanMaid, error) {
    _dataList := make([]*ConfigCfgKanbanMaid, 0, len(_buf))
    dataMap := make(map[int32]*ConfigCfgKanbanMaid)

    for _, _ele_ := range _buf {
        if _v, err2 := NewConfigCfgKanbanMaid(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &ConfigTbCfgKanbanMaid{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *ConfigTbCfgKanbanMaid) GetDataMap() map[int32]*ConfigCfgKanbanMaid {
    return table._dataMap
}

func (table *ConfigTbCfgKanbanMaid) GetDataList() []*ConfigCfgKanbanMaid {
    return table._dataList
}

func (table *ConfigTbCfgKanbanMaid) Get(key int32) *ConfigCfgKanbanMaid {
    return table._dataMap[key]
}


