
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type ConfigConstant struct {
    CDNBaseUrl string
    ApiUrl string
    ServerCa string
    ServerUrl string
}

const TypeId_ConfigConstant = 499204336

func (*ConfigConstant) GetTypeId() int32 {
    return 499204336
}

func NewConfigConstant(_buf map[string]interface{}) (_v *ConfigConstant, err error) {
    _v = &ConfigConstant{}
    { var _ok_ bool; var __json_CDNBaseUrl__ interface{}; if __json_CDNBaseUrl__, _ok_ = _buf["CDNBaseUrl"]; !_ok_ || __json_CDNBaseUrl__ == nil { err = errors.New("CDNBaseUrl error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_CDNBaseUrl__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CDNBaseUrl = __x__ }}
    { var _ok_ bool; var __json_ApiUrl__ interface{}; if __json_ApiUrl__, _ok_ = _buf["ApiUrl"]; !_ok_ || __json_ApiUrl__ == nil { err = errors.New("ApiUrl error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_ApiUrl__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ApiUrl = __x__ }}
    { var _ok_ bool; var __json_ServerCa__ interface{}; if __json_ServerCa__, _ok_ = _buf["ServerCa"]; !_ok_ || __json_ServerCa__ == nil { err = errors.New("ServerCa error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_ServerCa__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ServerCa = __x__ }}
    { var _ok_ bool; var __json_ServerUrl__ interface{}; if __json_ServerUrl__, _ok_ = _buf["ServerUrl"]; !_ok_ || __json_ServerUrl__ == nil { err = errors.New("ServerUrl error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_ServerUrl__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ServerUrl = __x__ }}
    return
}

