
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type ConfigCfgActivity struct {
    Id int32
    IsOpen bool
    ActType int32
    ActivityName string
    Icon string
    LeftOrRight int32
    RedType int32
    UnLockLevel int32
    ActTime int64
    OpenType int32
    Order int32
    TimeClose bool
    RechargeId int32
    PhotoRemoteKey string
    RandomCount int32
    RandomGroupID int32
    OpenBtnEff bool
    OpenBtnFlash bool
}

const TypeId_ConfigCfgActivity = 1251164871

func (*ConfigCfgActivity) GetTypeId() int32 {
    return 1251164871
}

func NewConfigCfgActivity(_buf map[string]interface{}) (_v *ConfigCfgActivity, err error) {
    _v = &ConfigCfgActivity{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_isOpen__ interface{}; if __json_isOpen__, _ok_ = _buf["isOpen"]; !_ok_ || __json_isOpen__ == nil { err = errors.New("isOpen error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_isOpen__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsOpen = __x__ }}
    { var _ok_ bool; var __json_actType__ interface{}; if __json_actType__, _ok_ = _buf["actType"]; !_ok_ || __json_actType__ == nil { err = errors.New("actType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_actType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ActType = __x__ }}
    { var _ok_ bool; var __json_activityName__ interface{}; if __json_activityName__, _ok_ = _buf["activityName"]; !_ok_ || __json_activityName__ == nil { err = errors.New("activityName error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_activityName__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ActivityName = __x__ }}
    { var _ok_ bool; var __json_Icon__ interface{}; if __json_Icon__, _ok_ = _buf["Icon"]; !_ok_ || __json_Icon__ == nil { err = errors.New("Icon error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_Icon__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Icon = __x__ }}
    { var _ok_ bool; var __json_LeftOrRight__ interface{}; if __json_LeftOrRight__, _ok_ = _buf["LeftOrRight"]; !_ok_ || __json_LeftOrRight__ == nil { err = errors.New("LeftOrRight error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_LeftOrRight__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LeftOrRight = __x__ }}
    { var _ok_ bool; var __json_redType__ interface{}; if __json_redType__, _ok_ = _buf["redType"]; !_ok_ || __json_redType__ == nil { err = errors.New("redType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_redType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RedType = __x__ }}
    { var _ok_ bool; var __json_unLockLevel__ interface{}; if __json_unLockLevel__, _ok_ = _buf["unLockLevel"]; !_ok_ || __json_unLockLevel__ == nil { err = errors.New("unLockLevel error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_unLockLevel__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnLockLevel = __x__ }}
    { var _ok_ bool; var __json_actTime__ interface{}; if __json_actTime__, _ok_ = _buf["actTime"]; !_ok_ || __json_actTime__ == nil { err = errors.New("actTime error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_actTime__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.ActTime = __x__ }}
    { var _ok_ bool; var __json_openType__ interface{}; if __json_openType__, _ok_ = _buf["openType"]; !_ok_ || __json_openType__ == nil { err = errors.New("openType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_openType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.OpenType = __x__ }}
    { var _ok_ bool; var __json_order__ interface{}; if __json_order__, _ok_ = _buf["order"]; !_ok_ || __json_order__ == nil { err = errors.New("order error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_order__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Order = __x__ }}
    { var _ok_ bool; var __json_timeClose__ interface{}; if __json_timeClose__, _ok_ = _buf["timeClose"]; !_ok_ || __json_timeClose__ == nil { err = errors.New("timeClose error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_timeClose__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.TimeClose = __x__ }}
    { var _ok_ bool; var __json_rechargeId__ interface{}; if __json_rechargeId__, _ok_ = _buf["rechargeId"]; !_ok_ || __json_rechargeId__ == nil { err = errors.New("rechargeId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_rechargeId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RechargeId = __x__ }}
    { var _ok_ bool; var __json_PhotoRemoteKey__ interface{}; if __json_PhotoRemoteKey__, _ok_ = _buf["PhotoRemoteKey"]; !_ok_ || __json_PhotoRemoteKey__ == nil { err = errors.New("PhotoRemoteKey error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_PhotoRemoteKey__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.PhotoRemoteKey = __x__ }}
    { var _ok_ bool; var __json_RandomCount__ interface{}; if __json_RandomCount__, _ok_ = _buf["RandomCount"]; !_ok_ || __json_RandomCount__ == nil { err = errors.New("RandomCount error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RandomCount__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RandomCount = __x__ }}
    { var _ok_ bool; var __json_RandomGroupID__ interface{}; if __json_RandomGroupID__, _ok_ = _buf["RandomGroupID"]; !_ok_ || __json_RandomGroupID__ == nil { err = errors.New("RandomGroupID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RandomGroupID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RandomGroupID = __x__ }}
    { var _ok_ bool; var __json_openBtnEff__ interface{}; if __json_openBtnEff__, _ok_ = _buf["openBtnEff"]; !_ok_ || __json_openBtnEff__ == nil { err = errors.New("openBtnEff error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_openBtnEff__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.OpenBtnEff = __x__ }}
    { var _ok_ bool; var __json_openBtnFlash__ interface{}; if __json_openBtnFlash__, _ok_ = _buf["openBtnFlash"]; !_ok_ || __json_openBtnFlash__ == nil { err = errors.New("openBtnFlash error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_openBtnFlash__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.OpenBtnFlash = __x__ }}
    return
}

