
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Daily_taskDailyTask struct {
    Id int32
    Des string
    RewardPoints int32
    CompleteCondition int32
    CompleteValue int32
    GotoId int32
    KeyId int32
    IsOpen int32
}

const TypeId_Daily_taskDailyTask = -2073455397

func (*Daily_taskDailyTask) GetTypeId() int32 {
    return -2073455397
}

func NewDaily_taskDailyTask(_buf map[string]interface{}) (_v *Daily_taskDailyTask, err error) {
    _v = &Daily_taskDailyTask{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_des__ interface{}; if __json_des__, _ok_ = _buf["des"]; !_ok_ || __json_des__ == nil { err = errors.New("des error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_des__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Des = __x__ }}
    { var _ok_ bool; var __json_reward_points__ interface{}; if __json_reward_points__, _ok_ = _buf["reward_points"]; !_ok_ || __json_reward_points__ == nil { err = errors.New("reward_points error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_reward_points__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RewardPoints = __x__ }}
    { var _ok_ bool; var __json_complete_condition__ interface{}; if __json_complete_condition__, _ok_ = _buf["complete_condition"]; !_ok_ || __json_complete_condition__ == nil { err = errors.New("complete_condition error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_complete_condition__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CompleteCondition = __x__ }}
    { var _ok_ bool; var __json_complete_value__ interface{}; if __json_complete_value__, _ok_ = _buf["complete_value"]; !_ok_ || __json_complete_value__ == nil { err = errors.New("complete_value error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_complete_value__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CompleteValue = __x__ }}
    { var _ok_ bool; var __json_goto_id__ interface{}; if __json_goto_id__, _ok_ = _buf["goto_id"]; !_ok_ || __json_goto_id__ == nil { err = errors.New("goto_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_goto_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.GotoId = __x__ }}
    { var _ok_ bool; var __json_key_id__ interface{}; if __json_key_id__, _ok_ = _buf["key_id"]; !_ok_ || __json_key_id__ == nil { err = errors.New("key_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_key_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.KeyId = __x__ }}
    { var _ok_ bool; var __json_is_open__ interface{}; if __json_is_open__, _ok_ = _buf["is_open"]; !_ok_ || __json_is_open__ == nil { err = errors.New("is_open error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_is_open__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.IsOpen = __x__ }}
    return
}

