
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Daily_taskTbDailyTask struct {
    _dataMap map[int32]*Daily_taskDailyTask
    _dataList []*Daily_taskDailyTask
}

func NewDaily_taskTbDailyTask(_buf []map[string]interface{}) (*Daily_taskTbDailyTask, error) {
    _dataList := make([]*Daily_taskDailyTask, 0, len(_buf))
    dataMap := make(map[int32]*Daily_taskDailyTask)

    for _, _ele_ := range _buf {
        if _v, err2 := NewDaily_taskDailyTask(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Daily_taskTbDailyTask{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Daily_taskTbDailyTask) GetDataMap() map[int32]*Daily_taskDailyTask {
    return table._dataMap
}

func (table *Daily_taskTbDailyTask) GetDataList() []*Daily_taskDailyTask {
    return table._dataList
}

func (table *Daily_taskTbDailyTask) Get(key int32) *Daily_taskDailyTask {
    return table._dataMap[key]
}


