
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Daily_dealTbDailyDeal struct {
    _dataMap map[int32]*Daily_dealDailyDeal
    _dataList []*Daily_dealDailyDeal
}

func NewDaily_dealTbDailyDeal(_buf []map[string]interface{}) (*Daily_dealTbDailyDeal, error) {
    _dataList := make([]*Daily_dealDailyDeal, 0, len(_buf))
    dataMap := make(map[int32]*Daily_dealDailyDeal)

    for _, _ele_ := range _buf {
        if _v, err2 := NewDaily_dealDailyDeal(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Daily_dealTbDailyDeal{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Daily_dealTbDailyDeal) GetDataMap() map[int32]*Daily_dealDailyDeal {
    return table._dataMap
}

func (table *Daily_dealTbDailyDeal) GetDataList() []*Daily_dealDailyDeal {
    return table._dataList
}

func (table *Daily_dealTbDailyDeal) Get(key int32) *Daily_dealDailyDeal {
    return table._dataMap[key]
}


