
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Daily_dealDailyDeal struct {
    Id int32
    CardDay int32
    CardRewardDaily string
    Price int32
    TitleDes string
    Relation string
    Limit int32
    Rewards string
}

const TypeId_Daily_dealDailyDeal = 720956905

func (*Daily_dealDailyDeal) GetTypeId() int32 {
    return 720956905
}

func NewDaily_dealDailyDeal(_buf map[string]interface{}) (_v *Daily_dealDailyDeal, err error) {
    _v = &Daily_dealDailyDeal{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_card_day__ interface{}; if __json_card_day__, _ok_ = _buf["card_day"]; !_ok_ || __json_card_day__ == nil { err = errors.New("card_day error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_card_day__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CardDay = __x__ }}
    { var _ok_ bool; var __json_card_reward_daily__ interface{}; if __json_card_reward_daily__, _ok_ = _buf["card_reward_daily"]; !_ok_ || __json_card_reward_daily__ == nil { err = errors.New("card_reward_daily error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_card_reward_daily__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CardRewardDaily = __x__ }}
    { var _ok_ bool; var __json_price__ interface{}; if __json_price__, _ok_ = _buf["price"]; !_ok_ || __json_price__ == nil { err = errors.New("price error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_price__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Price = __x__ }}
    { var _ok_ bool; var __json_title_des__ interface{}; if __json_title_des__, _ok_ = _buf["title_des"]; !_ok_ || __json_title_des__ == nil { err = errors.New("title_des error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_title_des__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.TitleDes = __x__ }}
    { var _ok_ bool; var __json_relation__ interface{}; if __json_relation__, _ok_ = _buf["relation"]; !_ok_ || __json_relation__ == nil { err = errors.New("relation error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_relation__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Relation = __x__ }}
    { var _ok_ bool; var __json_limit__ interface{}; if __json_limit__, _ok_ = _buf["limit"]; !_ok_ || __json_limit__ == nil { err = errors.New("limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Limit = __x__ }}
    { var _ok_ bool; var __json_rewards__ interface{}; if __json_rewards__, _ok_ = _buf["rewards"]; !_ok_ || __json_rewards__ == nil { err = errors.New("rewards error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_rewards__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Rewards = __x__ }}
    return
}

