
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type DropItemList struct {
    ItemList []*DropItemPair
}

const TypeId_DropItemList = 1825990272

func (*DropItemList) GetTypeId() int32 {
    return 1825990272
}

func NewDropItemList(_buf map[string]interface{}) (_v *DropItemList, err error) {
    _v = &DropItemList{}
    { var _ok_ bool; var __json_ItemList__ interface{}; if __json_ItemList__, _ok_ = _buf["ItemList"]; !_ok_ || __json_ItemList__ == nil { err = errors.New("ItemList error"); return } else { var __x__ []*DropItemPair;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_ItemList__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*DropItemPair, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *DropItemPair
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewDropItemPair(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.ItemList = __x__ }}
    return
}

