
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type DropItemPair struct {
    Id int32
    Num int32
    Weight int32
}

const TypeId_DropItemPair = 1826101436

func (*DropItemPair) GetTypeId() int32 {
    return 1826101436
}

func NewDropItemPair(_buf map[string]interface{}) (_v *DropItemPair, err error) {
    _v = &DropItemPair{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_Num__ interface{}; if __json_Num__, _ok_ = _buf["Num"]; !_ok_ || __json_Num__ == nil { err = errors.New("Num error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Num__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Num = __x__ }}
    { var _ok_ bool; var __json_Weight__ interface{}; if __json_Weight__, _ok_ = _buf["Weight"]; !_ok_ || __json_Weight__ == nil { err = errors.New("Weight error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Weight__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Weight = __x__ }}
    return
}

