
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 血量
     */
    E_AttributeType_HP = 0;
    /**
     * 攻击力
     */
    E_AttributeType_Atk = 1;
    /**
     * 暴击
     */
    E_AttributeType_CritRate = 2;
    /**
     * 抗暴
     */
    E_AttributeType_AntiCritRate = 3;
    /**
     * 暴击伤害
     */
    E_AttributeType_CritDmg = 4;
    /**
     * 发射间隔
     */
    E_AttributeType_LaunchCD = 5;
    /**
     * 移动速度
     */
    E_AttributeType_MoveSpeed = 7;
    /**
     * 撞击次数
     */
    E_AttributeType_CollisionCount = 8;
    /**
     * 弹珠上限
     */
    E_AttributeType_BallMaxCount = 9;
    /**
     * 发射数量
     */
    E_AttributeType_LaunchCount = 10;
    /**
     * 体积
     */
    E_AttributeType_Scale = 11;
    /**
     * 召唤数量
     */
    E_AttributeType_SummonCount = 12;
    /**
     * 防御
     */
    E_AttributeType_Defense = 13;
    /**
     * 收集范围
     */
    E_AttributeType_ExpCollectRange = 14;
    /**
     * 攻击加成
     */
    E_AttributeType_AtkRatio = 15;
    /**
     * 免伤加成
     */
    E_AttributeType_DefenseRatio = 16;
)

