
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 普通
     */
    E_BallType_Normal = 0;
    /**
     * 召唤
     */
    E_BallType_Summon = 1;
    /**
     * 技能
     */
    E_BallType_Skill = 2;
)

