
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 增益
     */
    E_BlessingType_Attr = 0;
    /**
     * 技能增加
     */
    E_BlessingType_SKill = 1;
    /**
     * 技能参数
     */
    E_BlessingType_SkillParam = 2;
    /**
     * 召唤物参数
     */
    E_BlessingType_SummonParam = 3;
    /**
     * Buff参数
     */
    E_BlessingType_BuffParam = 4;
    /**
     * 穿透参数
     */
    E_BlessingType_PenetrateType = 5;
    /**
     * Buff
     */
    E_BlessingType_Buff = 6;
    /**
     * Buff属性
     */
    E_BlessingType_BuffAttr = 7;
)

