
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 重置
     */
    E_BuffStackType_Reset = 0;
    /**
     * 不叠加
     */
    E_BuffStackType_NoStack = 1;
    /**
     * 时间叠加
     */
    E_BuffStackType_DurStack = 2;
    /**
     * 效果叠加
     */
    E_BuffStackType_EffStack = 3;
    /**
     * 层数叠加
     */
    E_BuffStackType_CountStack = 4;
    /**
     * 唯一效果
     */
    E_BuffStackType_Sole = 5;
)

