
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 增益
     */
    E_BuffType_AttributeBuff = 0;
    /**
     * 减益
     */
    E_BuffType_DamageBuff = 1;
    /**
     * 无敌
     */
    E_BuffType_Invincible = 2;
    /**
     * 时停
     */
    E_BuffType_MonsterStop = 3;
    /**
     * 围猎
     */
    E_BuffType_SetMap = 4;
    /**
     * 升级
     */
    E_BuffType_LevelUp = 5;
)

