
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 伤害
     */
    E_EffectType_Damage = 0;
    /**
     * 增益
     */
    E_EffectType_Buff = 1;
    /**
     * 特殊
     */
    E_EffectType_Special = 2;
    /**
     * 召唤
     */
    E_EffectType_Summon = 3;
    /**
     * 持续范围伤害
     */
    E_EffectType_AreaDotDamage = 4;
)

