
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 普通
     */
    E_LevelType_Normal = 0;
    /**
     * 精英
     */
    E_LevelType_Elite = 1;
    /**
     * 头目
     */
    E_LevelType_Boss = 2;
)

