
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 碰撞中心点
     */
    E_SpecialPosType_Center = 0;
    /**
     * 碰撞点
     */
    E_SpecialPosType_Collision = 1;
    /**
     * 出生点,屏幕下方
     */
    E_SpecialPosType_Spawn = 2;
    /**
     * 目标位置
     */
    E_SpecialPosType_Target = 3;
    /**
     * 挂点位置
     */
    E_SpecialPosType_AttachPoint = 4;
)

