
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 召唤
     */
    E_SpecialType_Summon = 0;
    /**
     * 穿透
     */
    E_SpecialType_Penetrate = 1;
    /**
     * 护盾
     */
    E_SpecialType_Shield = 2;
)

