
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

const (
    /**
     * 碰撞
     */
    E_TarggerType_Collision = 1;
    /**
     * 计时
     */
    E_TarggerType_Timer = 2;
    /**
     * 本体销毁
     */
    E_TarggerType_OwenDestroy = 3;
    /**
     * 目标销毁
     */
    E_TarggerType_TargetDestroy = 4;
    /**
     * 伤害计算后
     */
    E_TarggerType_DamageEnd = 5;
    /**
     * 技能释放后
     */
    E_TarggerType_SkillResolved = 6;
    /**
     * Buff触发
     */
    E_TarggerType_Buff = 7;
    /**
     * 发射时
     */
    E_TarggerType_Launch = 8;
)

