
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Equipment_lvEquipmentLv struct {
    Id int32
    HpAttr string
    AtkAttr string
    DefAttr string
    LvSpend int32
    KeyId int32
}

const TypeId_Equipment_lvEquipmentLv = 1423387653

func (*Equipment_lvEquipmentLv) GetTypeId() int32 {
    return 1423387653
}

func NewEquipment_lvEquipmentLv(_buf map[string]interface{}) (_v *Equipment_lvEquipmentLv, err error) {
    _v = &Equipment_lvEquipmentLv{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_hp_attr__ interface{}; if __json_hp_attr__, _ok_ = _buf["hp_attr"]; !_ok_ || __json_hp_attr__ == nil { err = errors.New("hp_attr error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_hp_attr__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.HpAttr = __x__ }}
    { var _ok_ bool; var __json_atk_attr__ interface{}; if __json_atk_attr__, _ok_ = _buf["atk_attr"]; !_ok_ || __json_atk_attr__ == nil { err = errors.New("atk_attr error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_atk_attr__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.AtkAttr = __x__ }}
    { var _ok_ bool; var __json_def_attr__ interface{}; if __json_def_attr__, _ok_ = _buf["def_attr"]; !_ok_ || __json_def_attr__ == nil { err = errors.New("def_attr error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_def_attr__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.DefAttr = __x__ }}
    { var _ok_ bool; var __json_lv_spend__ interface{}; if __json_lv_spend__, _ok_ = _buf["lv_spend"]; !_ok_ || __json_lv_spend__ == nil { err = errors.New("lv_spend error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_lv_spend__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LvSpend = __x__ }}
    { var _ok_ bool; var __json_key_id__ interface{}; if __json_key_id__, _ok_ = _buf["key_id"]; !_ok_ || __json_key_id__ == nil { err = errors.New("key_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_key_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.KeyId = __x__ }}
    return
}

