
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Equipment_lvTbEquipmentLv struct {
    _dataMap map[int32]*Equipment_lvEquipmentLv
    _dataList []*Equipment_lvEquipmentLv
}

func NewEquipment_lvTbEquipmentLv(_buf []map[string]interface{}) (*Equipment_lvTbEquipmentLv, error) {
    _dataList := make([]*Equipment_lvEquipmentLv, 0, len(_buf))
    dataMap := make(map[int32]*Equipment_lvEquipmentLv)

    for _, _ele_ := range _buf {
        if _v, err2 := NewEquipment_lvEquipmentLv(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Equipment_lvTbEquipmentLv{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Equipment_lvTbEquipmentLv) GetDataMap() map[int32]*Equipment_lvEquipmentLv {
    return table._dataMap
}

func (table *Equipment_lvTbEquipmentLv) GetDataList() []*Equipment_lvEquipmentLv {
    return table._dataList
}

func (table *Equipment_lvTbEquipmentLv) Get(key int32) *Equipment_lvEquipmentLv {
    return table._dataMap[key]
}


