
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Equipment_colorTbEquipmentColor struct {
    _dataMap map[int32]*Equipment_colorEquipmentColor
    _dataList []*Equipment_colorEquipmentColor
}

func NewEquipment_colorTbEquipmentColor(_buf []map[string]interface{}) (*Equipment_colorTbEquipmentColor, error) {
    _dataList := make([]*Equipment_colorEquipmentColor, 0, len(_buf))
    dataMap := make(map[int32]*Equipment_colorEquipmentColor)

    for _, _ele_ := range _buf {
        if _v, err2 := NewEquipment_colorEquipmentColor(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Equipment_colorTbEquipmentColor{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Equipment_colorTbEquipmentColor) GetDataMap() map[int32]*Equipment_colorEquipmentColor {
    return table._dataMap
}

func (table *Equipment_colorTbEquipmentColor) GetDataList() []*Equipment_colorEquipmentColor {
    return table._dataList
}

func (table *Equipment_colorTbEquipmentColor) Get(key int32) *Equipment_colorEquipmentColor {
    return table._dataMap[key]
}


