
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type EquipmentEquipment struct {
    Id int32
    Name string
    Color int32
    Type int32
    TypeE string
}

const TypeId_EquipmentEquipment = 1123362062

func (*EquipmentEquipment) GetTypeId() int32 {
    return 1123362062
}

func NewEquipmentEquipment(_buf map[string]interface{}) (_v *EquipmentEquipment, err error) {
    _v = &EquipmentEquipment{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_color__ interface{}; if __json_color__, _ok_ = _buf["color"]; !_ok_ || __json_color__ == nil { err = errors.New("color error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_color__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Color = __x__ }}
    { var _ok_ bool; var __json_type__ interface{}; if __json_type__, _ok_ = _buf["type"]; !_ok_ || __json_type__ == nil { err = errors.New("type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_type_e__ interface{}; if __json_type_e__, _ok_ = _buf["type_e"]; !_ok_ || __json_type_e__ == nil { err = errors.New("type_e error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_type_e__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.TypeE = __x__ }}
    return
}

