
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type EquipmentTbEquipment struct {
    _dataMap map[int32]*EquipmentEquipment
    _dataList []*EquipmentEquipment
}

func NewEquipmentTbEquipment(_buf []map[string]interface{}) (*EquipmentTbEquipment, error) {
    _dataList := make([]*EquipmentEquipment, 0, len(_buf))
    dataMap := make(map[int32]*EquipmentEquipment)

    for _, _ele_ := range _buf {
        if _v, err2 := NewEquipmentEquipment(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &EquipmentTbEquipment{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *EquipmentTbEquipment) GetDataMap() map[int32]*EquipmentEquipment {
    return table._dataMap
}

func (table *EquipmentTbEquipment) GetDataList() []*EquipmentEquipment {
    return table._dataList
}

func (table *EquipmentTbEquipment) Get(key int32) *EquipmentEquipment {
    return table._dataMap[key]
}


