
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Function struct {
    FuncID int32
}

const TypeId_Function = 1445582840

func (*Function) GetTypeId() int32 {
    return 1445582840
}

func NewFunction(_buf map[string]interface{}) (_v *Function, err error) {
    _v = &Function{}
    { var _ok_ bool; var __json_FuncID__ interface{}; if __json_FuncID__, _ok_ = _buf["FuncID"]; !_ok_ || __json_FuncID__ == nil { err = errors.New("FuncID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_FuncID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.FuncID = __x__ }}
    return
}

