
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Get_fromGetFrom struct {
    Id string
    Name string
    Des string
    Source string
}

const TypeId_Get_fromGetFrom = -2060915707

func (*Get_fromGetFrom) GetTypeId() int32 {
    return -2060915707
}

func NewGet_fromGetFrom(_buf map[string]interface{}) (_v *Get_fromGetFrom, err error) {
    _v = &Get_fromGetFrom{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_des__ interface{}; if __json_des__, _ok_ = _buf["des"]; !_ok_ || __json_des__ == nil { err = errors.New("des error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_des__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Des = __x__ }}
    { var _ok_ bool; var __json_source__ interface{}; if __json_source__, _ok_ = _buf["source"]; !_ok_ || __json_source__ == nil { err = errors.New("source error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_source__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Source = __x__ }}
    return
}

