
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Get_fromTbGetFrom struct {
    _dataMap map[string]*Get_fromGetFrom
    _dataList []*Get_fromGetFrom
}

func NewGet_fromTbGetFrom(_buf []map[string]interface{}) (*Get_fromTbGetFrom, error) {
    _dataList := make([]*Get_fromGetFrom, 0, len(_buf))
    dataMap := make(map[string]*Get_fromGetFrom)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGet_fromGetFrom(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Get_fromTbGetFrom{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Get_fromTbGetFrom) GetDataMap() map[string]*Get_fromGetFrom {
    return table._dataMap
}

func (table *Get_fromTbGetFrom) GetDataList() []*Get_fromGetFrom {
    return table._dataList
}

func (table *Get_fromTbGetFrom) Get(key string) *Get_fromGetFrom {
    return table._dataMap[key]
}


