
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Global struct {
    Start int32
    ActivityResetTime int32
    MallCashItemId int32
    RandomShopRefreshCost []int32
    StaminaItemId int32
    StaminaMaxNum int32
    StaminaRecover []int32
    TreasureChestFree []int32
    DefaultLineup []int32
    RandomShopFixedGoodsId int32
    RandomShopRefreshCount int32
    RefreshBlessingCount int32
    GetAllBlessingCount int32
}

const TypeId_Global = 2135814083

func (*Global) GetTypeId() int32 {
    return 2135814083
}

func NewGlobal(_buf map[string]interface{}) (_v *Global, err error) {
    _v = &Global{}
    { var _ok_ bool; var __json_Start__ interface{}; if __json_Start__, _ok_ = _buf["Start"]; !_ok_ || __json_Start__ == nil { err = errors.New("Start error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Start__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Start = __x__ }}
    { var _ok_ bool; var __json_ActivityResetTime__ interface{}; if __json_ActivityResetTime__, _ok_ = _buf["ActivityResetTime"]; !_ok_ || __json_ActivityResetTime__ == nil { err = errors.New("ActivityResetTime error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ActivityResetTime__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ActivityResetTime = __x__ }}
    { var _ok_ bool; var __json_MallCashItemId__ interface{}; if __json_MallCashItemId__, _ok_ = _buf["MallCashItemId"]; !_ok_ || __json_MallCashItemId__ == nil { err = errors.New("MallCashItemId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_MallCashItemId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MallCashItemId = __x__ }}
    { var _ok_ bool; var __json_RandomShopRefreshCost__ interface{}; if __json_RandomShopRefreshCost__, _ok_ = _buf["RandomShopRefreshCost"]; !_ok_ || __json_RandomShopRefreshCost__ == nil { err = errors.New("RandomShopRefreshCost error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_RandomShopRefreshCost__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.RandomShopRefreshCost = __x__ }}
    { var _ok_ bool; var __json_StaminaItemId__ interface{}; if __json_StaminaItemId__, _ok_ = _buf["StaminaItemId"]; !_ok_ || __json_StaminaItemId__ == nil { err = errors.New("StaminaItemId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_StaminaItemId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StaminaItemId = __x__ }}
    { var _ok_ bool; var __json_StaminaMaxNum__ interface{}; if __json_StaminaMaxNum__, _ok_ = _buf["StaminaMaxNum"]; !_ok_ || __json_StaminaMaxNum__ == nil { err = errors.New("StaminaMaxNum error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_StaminaMaxNum__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StaminaMaxNum = __x__ }}
    { var _ok_ bool; var __json_StaminaRecover__ interface{}; if __json_StaminaRecover__, _ok_ = _buf["StaminaRecover"]; !_ok_ || __json_StaminaRecover__ == nil { err = errors.New("StaminaRecover error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_StaminaRecover__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.StaminaRecover = __x__ }}
    { var _ok_ bool; var __json_TreasureChestFree__ interface{}; if __json_TreasureChestFree__, _ok_ = _buf["TreasureChestFree"]; !_ok_ || __json_TreasureChestFree__ == nil { err = errors.New("TreasureChestFree error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_TreasureChestFree__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.TreasureChestFree = __x__ }}
    { var _ok_ bool; var __json_DefaultLineup__ interface{}; if __json_DefaultLineup__, _ok_ = _buf["DefaultLineup"]; !_ok_ || __json_DefaultLineup__ == nil { err = errors.New("DefaultLineup error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_DefaultLineup__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.DefaultLineup = __x__ }}
    { var _ok_ bool; var __json_RandomShopFixedGoodsId__ interface{}; if __json_RandomShopFixedGoodsId__, _ok_ = _buf["RandomShopFixedGoodsId"]; !_ok_ || __json_RandomShopFixedGoodsId__ == nil { err = errors.New("RandomShopFixedGoodsId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RandomShopFixedGoodsId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RandomShopFixedGoodsId = __x__ }}
    { var _ok_ bool; var __json_RandomShopRefreshCount__ interface{}; if __json_RandomShopRefreshCount__, _ok_ = _buf["RandomShopRefreshCount"]; !_ok_ || __json_RandomShopRefreshCount__ == nil { err = errors.New("RandomShopRefreshCount error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RandomShopRefreshCount__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RandomShopRefreshCount = __x__ }}
    { var _ok_ bool; var __json_RefreshBlessingCount__ interface{}; if __json_RefreshBlessingCount__, _ok_ = _buf["RefreshBlessingCount"]; !_ok_ || __json_RefreshBlessingCount__ == nil { err = errors.New("RefreshBlessingCount error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RefreshBlessingCount__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RefreshBlessingCount = __x__ }}
    { var _ok_ bool; var __json_GetAllBlessingCount__ interface{}; if __json_GetAllBlessingCount__, _ok_ = _buf["GetAllBlessingCount"]; !_ok_ || __json_GetAllBlessingCount__ == nil { err = errors.New("GetAllBlessingCount error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_GetAllBlessingCount__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.GetAllBlessingCount = __x__ }}
    return
}

