
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Gold_buyGoldBuy struct {
    Id int32
    ItemName string
    Gold int32
}

const TypeId_Gold_buyGoldBuy = -623920865

func (*Gold_buyGoldBuy) GetTypeId() int32 {
    return -623920865
}

func NewGold_buyGoldBuy(_buf map[string]interface{}) (_v *Gold_buyGoldBuy, err error) {
    _v = &Gold_buyGoldBuy{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_item_name__ interface{}; if __json_item_name__, _ok_ = _buf["item_name"]; !_ok_ || __json_item_name__ == nil { err = errors.New("item_name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_item_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ItemName = __x__ }}
    { var _ok_ bool; var __json_gold__ interface{}; if __json_gold__, _ok_ = _buf["gold"]; !_ok_ || __json_gold__ == nil { err = errors.New("gold error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_gold__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Gold = __x__ }}
    return
}

