
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Gold_shopTbGoldShop struct {
    _dataMap map[int32]*Gold_shopGoldShop
    _dataList []*Gold_shopGoldShop
}

func NewGold_shopTbGoldShop(_buf []map[string]interface{}) (*Gold_shopTbGoldShop, error) {
    _dataList := make([]*Gold_shopGoldShop, 0, len(_buf))
    dataMap := make(map[int32]*Gold_shopGoldShop)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGold_shopGoldShop(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Gold_shopTbGoldShop{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Gold_shopTbGoldShop) GetDataMap() map[int32]*Gold_shopGoldShop {
    return table._dataMap
}

func (table *Gold_shopTbGoldShop) GetDataList() []*Gold_shopGoldShop {
    return table._dataList
}

func (table *Gold_shopTbGoldShop) Get(key int32) *Gold_shopGoldShop {
    return table._dataMap[key]
}


