
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Gua_ji_jin_biGuaJiJinBi struct {
    Id int32
    Level int32
    Coin int32
}

const TypeId_Gua_ji_jin_biGuaJiJinBi = -1701563257

func (*Gua_ji_jin_biGuaJiJinBi) GetTypeId() int32 {
    return -1701563257
}

func NewGua_ji_jin_biGuaJiJinBi(_buf map[string]interface{}) (_v *Gua_ji_jin_biGuaJiJinBi, err error) {
    _v = &Gua_ji_jin_biGuaJiJinBi{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_level__ interface{}; if __json_level__, _ok_ = _buf["level"]; !_ok_ || __json_level__ == nil { err = errors.New("level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Level = __x__ }}
    { var _ok_ bool; var __json_coin__ interface{}; if __json_coin__, _ok_ = _buf["coin"]; !_ok_ || __json_coin__ == nil { err = errors.New("coin error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_coin__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Coin = __x__ }}
    return
}

