
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Gua_ji_shi_changTbGuaJiShiChang struct {
    _dataMap map[int32]*Gua_ji_shi_changGuaJiShiChang
    _dataList []*Gua_ji_shi_changGuaJiShiChang
}

func NewGua_ji_shi_changTbGuaJiShiChang(_buf []map[string]interface{}) (*Gua_ji_shi_changTbGuaJiShiChang, error) {
    _dataList := make([]*Gua_ji_shi_changGuaJiShiChang, 0, len(_buf))
    dataMap := make(map[int32]*Gua_ji_shi_changGuaJiShiChang)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGua_ji_shi_changGuaJiShiChang(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Gua_ji_shi_changTbGuaJiShiChang{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Gua_ji_shi_changTbGuaJiShiChang) GetDataMap() map[int32]*Gua_ji_shi_changGuaJiShiChang {
    return table._dataMap
}

func (table *Gua_ji_shi_changTbGuaJiShiChang) GetDataList() []*Gua_ji_shi_changGuaJiShiChang {
    return table._dataList
}

func (table *Gua_ji_shi_changTbGuaJiShiChang) Get(key int32) *Gua_ji_shi_changGuaJiShiChang {
    return table._dataMap[key]
}


