
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Gua_ji_jin_biTbGuaJiJinBi struct {
    _dataMap map[int32]*Gua_ji_jin_biGuaJiJinBi
    _dataList []*Gua_ji_jin_biGuaJiJinBi
}

func NewGua_ji_jin_biTbGuaJiJinBi(_buf []map[string]interface{}) (*Gua_ji_jin_biTbGuaJiJinBi, error) {
    _dataList := make([]*Gua_ji_jin_biGuaJiJinBi, 0, len(_buf))
    dataMap := make(map[int32]*Gua_ji_jin_biGuaJiJinBi)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGua_ji_jin_biGuaJiJinBi(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Gua_ji_jin_biTbGuaJiJinBi{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Gua_ji_jin_biTbGuaJiJinBi) GetDataMap() map[int32]*Gua_ji_jin_biGuaJiJinBi {
    return table._dataMap
}

func (table *Gua_ji_jin_biTbGuaJiJinBi) GetDataList() []*Gua_ji_jin_biGuaJiJinBi {
    return table._dataList
}

func (table *Gua_ji_jin_biTbGuaJiJinBi) Get(key int32) *Gua_ji_jin_biGuaJiJinBi {
    return table._dataMap[key]
}


