
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Gua_ji_wu_pinTbGuaJiWuPin struct {
    _dataMap map[int32]*Gua_ji_wu_pinGuaJiWuPin
    _dataList []*Gua_ji_wu_pinGuaJiWuPin
}

func NewGua_ji_wu_pinTbGuaJiWuPin(_buf []map[string]interface{}) (*Gua_ji_wu_pinTbGuaJiWuPin, error) {
    _dataList := make([]*Gua_ji_wu_pinGuaJiWuPin, 0, len(_buf))
    dataMap := make(map[int32]*Gua_ji_wu_pinGuaJiWuPin)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGua_ji_wu_pinGuaJiWuPin(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Gua_ji_wu_pinTbGuaJiWuPin{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Gua_ji_wu_pinTbGuaJiWuPin) GetDataMap() map[int32]*Gua_ji_wu_pinGuaJiWuPin {
    return table._dataMap
}

func (table *Gua_ji_wu_pinTbGuaJiWuPin) GetDataList() []*Gua_ji_wu_pinGuaJiWuPin {
    return table._dataList
}

func (table *Gua_ji_wu_pinTbGuaJiWuPin) Get(key int32) *Gua_ji_wu_pinGuaJiWuPin {
    return table._dataMap[key]
}


