
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Gua_ji_shi_changGuaJiShiChang struct {
    Id int32
    Time int32
    Price int32
}

const TypeId_Gua_ji_shi_changGuaJiShiChang = 1232288635

func (*Gua_ji_shi_changGuaJiShiChang) GetTypeId() int32 {
    return 1232288635
}

func NewGua_ji_shi_changGuaJiShiChang(_buf map[string]interface{}) (_v *Gua_ji_shi_changGuaJiShiChang, err error) {
    _v = &Gua_ji_shi_changGuaJiShiChang{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_time__ interface{}; if __json_time__, _ok_ = _buf["time"]; !_ok_ || __json_time__ == nil { err = errors.New("time error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_time__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Time = __x__ }}
    { var _ok_ bool; var __json_price__ interface{}; if __json_price__, _ok_ = _buf["price"]; !_ok_ || __json_price__ == nil { err = errors.New("price error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_price__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Price = __x__ }}
    return
}

