
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Gua_ji_deng_jiGuaJiDengJi struct {
    Id int32
    Level int32
    ClearRewards string
    ClearItems string
}

const TypeId_Gua_ji_deng_jiGuaJiDengJi = -1247773331

func (*Gua_ji_deng_jiGuaJiDengJi) GetTypeId() int32 {
    return -1247773331
}

func NewGua_ji_deng_jiGuaJiDengJi(_buf map[string]interface{}) (_v *Gua_ji_deng_jiGuaJiDengJi, err error) {
    _v = &Gua_ji_deng_jiGuaJiDengJi{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_level__ interface{}; if __json_level__, _ok_ = _buf["level"]; !_ok_ || __json_level__ == nil { err = errors.New("level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Level = __x__ }}
    { var _ok_ bool; var __json_clear_rewards__ interface{}; if __json_clear_rewards__, _ok_ = _buf["clear_rewards"]; !_ok_ || __json_clear_rewards__ == nil { err = errors.New("clear_rewards error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_clear_rewards__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ClearRewards = __x__ }}
    { var _ok_ bool; var __json_clear_items__ interface{}; if __json_clear_items__, _ok_ = _buf["clear_items"]; !_ok_ || __json_clear_items__ == nil { err = errors.New("clear_items error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_clear_items__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ClearItems = __x__ }}
    return
}

