
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Hero_star_extHeroStarExt struct {
    Id int32
    DefRatio float32
    AtkRatio float32
    HpRatio float32
    CostClipNum int32
}

const TypeId_Hero_star_extHeroStarExt = -1822199840

func (*Hero_star_extHeroStarExt) GetTypeId() int32 {
    return -1822199840
}

func NewHero_star_extHeroStarExt(_buf map[string]interface{}) (_v *Hero_star_extHeroStarExt, err error) {
    _v = &Hero_star_extHeroStarExt{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_def_ratio__ interface{}; if __json_def_ratio__, _ok_ = _buf["def_ratio"]; !_ok_ || __json_def_ratio__ == nil { err = errors.New("def_ratio error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_def_ratio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.DefRatio = __x__ }}
    { var _ok_ bool; var __json_atk_ratio__ interface{}; if __json_atk_ratio__, _ok_ = _buf["atk_ratio"]; !_ok_ || __json_atk_ratio__ == nil { err = errors.New("atk_ratio error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_atk_ratio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.AtkRatio = __x__ }}
    { var _ok_ bool; var __json_hp_ratio__ interface{}; if __json_hp_ratio__, _ok_ = _buf["hp_ratio"]; !_ok_ || __json_hp_ratio__ == nil { err = errors.New("hp_ratio error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hp_ratio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.HpRatio = __x__ }}
    { var _ok_ bool; var __json_cost_clip_num__ interface{}; if __json_cost_clip_num__, _ok_ = _buf["cost_clip_num"]; !_ok_ || __json_cost_clip_num__ == nil { err = errors.New("cost_clip_num error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_cost_clip_num__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CostClipNum = __x__ }}
    return
}

