
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Hero_base_equipTbHeroBaseEquip struct {
    _dataMap map[int32]*Hero_base_equipHeroBaseEquip
    _dataList []*Hero_base_equipHeroBaseEquip
}

func NewHero_base_equipTbHeroBaseEquip(_buf []map[string]interface{}) (*Hero_base_equipTbHeroBaseEquip, error) {
    _dataList := make([]*Hero_base_equipHeroBaseEquip, 0, len(_buf))
    dataMap := make(map[int32]*Hero_base_equipHeroBaseEquip)

    for _, _ele_ := range _buf {
        if _v, err2 := NewHero_base_equipHeroBaseEquip(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Hero_base_equipTbHeroBaseEquip{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Hero_base_equipTbHeroBaseEquip) GetDataMap() map[int32]*Hero_base_equipHeroBaseEquip {
    return table._dataMap
}

func (table *Hero_base_equipTbHeroBaseEquip) GetDataList() []*Hero_base_equipHeroBaseEquip {
    return table._dataList
}

func (table *Hero_base_equipTbHeroBaseEquip) Get(key int32) *Hero_base_equipHeroBaseEquip {
    return table._dataMap[key]
}


