
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Hero_star_extTbHeroStarExt struct {
    _dataMap map[int32]*Hero_star_extHeroStarExt
    _dataList []*Hero_star_extHeroStarExt
}

func NewHero_star_extTbHeroStarExt(_buf []map[string]interface{}) (*Hero_star_extTbHeroStarExt, error) {
    _dataList := make([]*Hero_star_extHeroStarExt, 0, len(_buf))
    dataMap := make(map[int32]*Hero_star_extHeroStarExt)

    for _, _ele_ := range _buf {
        if _v, err2 := NewHero_star_extHeroStarExt(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Hero_star_extTbHeroStarExt{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Hero_star_extTbHeroStarExt) GetDataMap() map[int32]*Hero_star_extHeroStarExt {
    return table._dataMap
}

func (table *Hero_star_extTbHeroStarExt) GetDataList() []*Hero_star_extHeroStarExt {
    return table._dataList
}

func (table *Hero_star_extTbHeroStarExt) Get(key int32) *Hero_star_extHeroStarExt {
    return table._dataMap[key]
}


