
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Hero_orderTbHeroOrder struct {
    _dataMap map[int32]*Hero_orderHeroOrder
    _dataList []*Hero_orderHeroOrder
}

func NewHero_orderTbHeroOrder(_buf []map[string]interface{}) (*Hero_orderTbHeroOrder, error) {
    _dataList := make([]*Hero_orderHeroOrder, 0, len(_buf))
    dataMap := make(map[int32]*Hero_orderHeroOrder)

    for _, _ele_ := range _buf {
        if _v, err2 := NewHero_orderHeroOrder(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Hero_orderTbHeroOrder{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Hero_orderTbHeroOrder) GetDataMap() map[int32]*Hero_orderHeroOrder {
    return table._dataMap
}

func (table *Hero_orderTbHeroOrder) GetDataList() []*Hero_orderHeroOrder {
    return table._dataList
}

func (table *Hero_orderTbHeroOrder) Get(key int32) *Hero_orderHeroOrder {
    return table._dataMap[key]
}


