
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Hero_lv_spendTbHeroLvSpend struct {
    _dataMap map[int32]*Hero_lv_spendHeroLvSpend
    _dataList []*Hero_lv_spendHeroLvSpend
}

func NewHero_lv_spendTbHeroLvSpend(_buf []map[string]interface{}) (*Hero_lv_spendTbHeroLvSpend, error) {
    _dataList := make([]*Hero_lv_spendHeroLvSpend, 0, len(_buf))
    dataMap := make(map[int32]*Hero_lv_spendHeroLvSpend)

    for _, _ele_ := range _buf {
        if _v, err2 := NewHero_lv_spendHeroLvSpend(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Hero_lv_spendTbHeroLvSpend{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Hero_lv_spendTbHeroLvSpend) GetDataMap() map[int32]*Hero_lv_spendHeroLvSpend {
    return table._dataMap
}

func (table *Hero_lv_spendTbHeroLvSpend) GetDataList() []*Hero_lv_spendHeroLvSpend {
    return table._dataList
}

func (table *Hero_lv_spendTbHeroLvSpend) Get(key int32) *Hero_lv_spendHeroLvSpend {
    return table._dataMap[key]
}


