
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Hero_skillHeroSkill struct {
    Id int32
    Name string
    Describe string
    OpenStage int32
    Near int32
    EffectBallistic string
    EffectHit string
    SkillType int32
    AttackType int32
    AttackRatio float32
    Attrs string
}

const TypeId_Hero_skillHeroSkill = 52573365

func (*Hero_skillHeroSkill) GetTypeId() int32 {
    return 52573365
}

func NewHero_skillHeroSkill(_buf map[string]interface{}) (_v *Hero_skillHeroSkill, err error) {
    _v = &Hero_skillHeroSkill{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_describe__ interface{}; if __json_describe__, _ok_ = _buf["describe"]; !_ok_ || __json_describe__ == nil { err = errors.New("describe error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_describe__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Describe = __x__ }}
    { var _ok_ bool; var __json_open_stage__ interface{}; if __json_open_stage__, _ok_ = _buf["open_stage"]; !_ok_ || __json_open_stage__ == nil { err = errors.New("open_stage error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_open_stage__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.OpenStage = __x__ }}
    { var _ok_ bool; var __json_near__ interface{}; if __json_near__, _ok_ = _buf["near"]; !_ok_ || __json_near__ == nil { err = errors.New("near error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_near__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Near = __x__ }}
    { var _ok_ bool; var __json_effect_ballistic__ interface{}; if __json_effect_ballistic__, _ok_ = _buf["effect_ballistic"]; !_ok_ || __json_effect_ballistic__ == nil { err = errors.New("effect_ballistic error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_effect_ballistic__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.EffectBallistic = __x__ }}
    { var _ok_ bool; var __json_effect_hit__ interface{}; if __json_effect_hit__, _ok_ = _buf["effect_hit"]; !_ok_ || __json_effect_hit__ == nil { err = errors.New("effect_hit error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_effect_hit__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.EffectHit = __x__ }}
    { var _ok_ bool; var __json_skill_type__ interface{}; if __json_skill_type__, _ok_ = _buf["skill_type"]; !_ok_ || __json_skill_type__ == nil { err = errors.New("skill_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_skill_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SkillType = __x__ }}
    { var _ok_ bool; var __json_attack_type__ interface{}; if __json_attack_type__, _ok_ = _buf["attack_type"]; !_ok_ || __json_attack_type__ == nil { err = errors.New("attack_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_attack_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AttackType = __x__ }}
    { var _ok_ bool; var __json_attack_ratio__ interface{}; if __json_attack_ratio__, _ok_ = _buf["attack_ratio"]; !_ok_ || __json_attack_ratio__ == nil { err = errors.New("attack_ratio error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_attack_ratio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.AttackRatio = __x__ }}
    { var _ok_ bool; var __json_attrs__ interface{}; if __json_attrs__, _ok_ = _buf["attrs"]; !_ok_ || __json_attrs__ == nil { err = errors.New("attrs error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_attrs__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Attrs = __x__ }}
    return
}

