
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Hero_attrHeroAttr struct {
    Id int32
    Def float32
    Atk float32
    Spd float32
    Hp float32
    HeroId int32
}

const TypeId_Hero_attrHeroAttr = -2006855421

func (*Hero_attrHeroAttr) GetTypeId() int32 {
    return -2006855421
}

func NewHero_attrHeroAttr(_buf map[string]interface{}) (_v *Hero_attrHeroAttr, err error) {
    _v = &Hero_attrHeroAttr{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_def__ interface{}; if __json_def__, _ok_ = _buf["def"]; !_ok_ || __json_def__ == nil { err = errors.New("def error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_def__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Def = __x__ }}
    { var _ok_ bool; var __json_atk__ interface{}; if __json_atk__, _ok_ = _buf["atk"]; !_ok_ || __json_atk__ == nil { err = errors.New("atk error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_atk__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Atk = __x__ }}
    { var _ok_ bool; var __json_spd__ interface{}; if __json_spd__, _ok_ = _buf["spd"]; !_ok_ || __json_spd__ == nil { err = errors.New("spd error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_spd__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Spd = __x__ }}
    { var _ok_ bool; var __json_hp__ interface{}; if __json_hp__, _ok_ = _buf["hp"]; !_ok_ || __json_hp__ == nil { err = errors.New("hp error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hp__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Hp = __x__ }}
    { var _ok_ bool; var __json_hero_id__ interface{}; if __json_hero_id__, _ok_ = _buf["hero_id"]; !_ok_ || __json_hero_id__ == nil { err = errors.New("hero_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hero_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.HeroId = __x__ }}
    return
}

