
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Hero_lv_spendHeroLvSpend struct {
    Id int32
    LvSpend int32
}

const TypeId_Hero_lv_spendHeroLvSpend = 1895775130

func (*Hero_lv_spendHeroLvSpend) GetTypeId() int32 {
    return 1895775130
}

func NewHero_lv_spendHeroLvSpend(_buf map[string]interface{}) (_v *Hero_lv_spendHeroLvSpend, err error) {
    _v = &Hero_lv_spendHeroLvSpend{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_lv_spend__ interface{}; if __json_lv_spend__, _ok_ = _buf["lv_spend"]; !_ok_ || __json_lv_spend__ == nil { err = errors.New("lv_spend error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_lv_spend__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LvSpend = __x__ }}
    return
}

