
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type ItemItem struct {
    Id string
    Name string
    Des string
    Color int32
    ItemType int32
    BtnType int32
    Club int32
}

const TypeId_ItemItem = 2107285806

func (*ItemItem) GetTypeId() int32 {
    return 2107285806
}

func NewItemItem(_buf map[string]interface{}) (_v *ItemItem, err error) {
    _v = &ItemItem{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_des__ interface{}; if __json_des__, _ok_ = _buf["des"]; !_ok_ || __json_des__ == nil { err = errors.New("des error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_des__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Des = __x__ }}
    { var _ok_ bool; var __json_color__ interface{}; if __json_color__, _ok_ = _buf["color"]; !_ok_ || __json_color__ == nil { err = errors.New("color error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_color__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Color = __x__ }}
    { var _ok_ bool; var __json_item_type__ interface{}; if __json_item_type__, _ok_ = _buf["item_type"]; !_ok_ || __json_item_type__ == nil { err = errors.New("item_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_item_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ItemType = __x__ }}
    { var _ok_ bool; var __json_btn_type__ interface{}; if __json_btn_type__, _ok_ = _buf["btn_type"]; !_ok_ || __json_btn_type__ == nil { err = errors.New("btn_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_btn_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BtnType = __x__ }}
    { var _ok_ bool; var __json_club__ interface{}; if __json_club__, _ok_ = _buf["club"]; !_ok_ || __json_club__ == nil { err = errors.New("club error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_club__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Club = __x__ }}
    return
}

