
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Jump struct {
    UIID int32
}

const TypeId_Jump = 2320462

func (*Jump) GetTypeId() int32 {
    return 2320462
}

func NewJump(_buf map[string]interface{}) (_v *Jump, err error) {
    _v = &Jump{}
    { var _ok_ bool; var __json_UIID__ interface{}; if __json_UIID__, _ok_ = _buf["UIID"]; !_ok_ || __json_UIID__ == nil { err = errors.New("UIID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_UIID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UIID = __x__ }}
    return
}

