
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Level_coeffLevelCoeff struct {
    Id int32
    SpdCoeff float32
    OnlyId int32
    AtkCoeff string
    DefCoeff int32
}

const TypeId_Level_coeffLevelCoeff = 669498213

func (*Level_coeffLevelCoeff) GetTypeId() int32 {
    return 669498213
}

func NewLevel_coeffLevelCoeff(_buf map[string]interface{}) (_v *Level_coeffLevelCoeff, err error) {
    _v = &Level_coeffLevelCoeff{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_spdCoeff__ interface{}; if __json_spdCoeff__, _ok_ = _buf["spdCoeff"]; !_ok_ || __json_spdCoeff__ == nil { err = errors.New("spdCoeff error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_spdCoeff__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.SpdCoeff = __x__ }}
    { var _ok_ bool; var __json_onlyId__ interface{}; if __json_onlyId__, _ok_ = _buf["onlyId"]; !_ok_ || __json_onlyId__ == nil { err = errors.New("onlyId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_onlyId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.OnlyId = __x__ }}
    { var _ok_ bool; var __json_atkCoeff__ interface{}; if __json_atkCoeff__, _ok_ = _buf["atkCoeff"]; !_ok_ || __json_atkCoeff__ == nil { err = errors.New("atkCoeff error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_atkCoeff__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.AtkCoeff = __x__ }}
    { var _ok_ bool; var __json_defCoeff__ interface{}; if __json_defCoeff__, _ok_ = _buf["defCoeff"]; !_ok_ || __json_defCoeff__ == nil { err = errors.New("defCoeff error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_defCoeff__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DefCoeff = __x__ }}
    return
}

