
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Level_coeffTbLevelCoeff struct {
    _dataMap map[int32]*Level_coeffLevelCoeff
    _dataList []*Level_coeffLevelCoeff
}

func NewLevel_coeffTbLevelCoeff(_buf []map[string]interface{}) (*Level_coeffTbLevelCoeff, error) {
    _dataList := make([]*Level_coeffLevelCoeff, 0, len(_buf))
    dataMap := make(map[int32]*Level_coeffLevelCoeff)

    for _, _ele_ := range _buf {
        if _v, err2 := NewLevel_coeffLevelCoeff(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Level_coeffTbLevelCoeff{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Level_coeffTbLevelCoeff) GetDataMap() map[int32]*Level_coeffLevelCoeff {
    return table._dataMap
}

func (table *Level_coeffTbLevelCoeff) GetDataList() []*Level_coeffLevelCoeff {
    return table._dataList
}

func (table *Level_coeffTbLevelCoeff) Get(key int32) *Level_coeffLevelCoeff {
    return table._dataMap[key]
}


