
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Li_baoTbLiBao struct {
    _dataMap map[string]*Li_baoLiBao
    _dataList []*Li_baoLiBao
}

func NewLi_baoTbLiBao(_buf []map[string]interface{}) (*Li_baoTbLiBao, error) {
    _dataList := make([]*Li_baoLiBao, 0, len(_buf))
    dataMap := make(map[string]*Li_baoLiBao)

    for _, _ele_ := range _buf {
        if _v, err2 := NewLi_baoLiBao(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Li_baoTbLiBao{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Li_baoTbLiBao) GetDataMap() map[string]*Li_baoLiBao {
    return table._dataMap
}

func (table *Li_baoTbLiBao) GetDataList() []*Li_baoLiBao {
    return table._dataList
}

func (table *Li_baoTbLiBao) Get(key string) *Li_baoLiBao {
    return table._dataMap[key]
}


