
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Li_baoLiBao struct {
    Id string
    Name string
    Rewards string
}

const TypeId_Li_baoLiBao = 1496769939

func (*Li_baoLiBao) GetTypeId() int32 {
    return 1496769939
}

func NewLi_baoLiBao(_buf map[string]interface{}) (_v *Li_baoLiBao, err error) {
    _v = &Li_baoLiBao{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_rewards__ interface{}; if __json_rewards__, _ok_ = _buf["rewards"]; !_ok_ || __json_rewards__ == nil { err = errors.New("rewards error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_rewards__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Rewards = __x__ }}
    return
}

