
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Lord_attr_confLordAttrConf struct {
    HeroId int32
    Atk float32
    DefId float32
    Hp float32
    Clk float32
}

const TypeId_Lord_attr_confLordAttrConf = 597044016

func (*Lord_attr_confLordAttrConf) GetTypeId() int32 {
    return 597044016
}

func NewLord_attr_confLordAttrConf(_buf map[string]interface{}) (_v *Lord_attr_confLordAttrConf, err error) {
    _v = &Lord_attr_confLordAttrConf{}
    { var _ok_ bool; var __json_hero_id__ interface{}; if __json_hero_id__, _ok_ = _buf["hero_id"]; !_ok_ || __json_hero_id__ == nil { err = errors.New("hero_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hero_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.HeroId = __x__ }}
    { var _ok_ bool; var __json_atk__ interface{}; if __json_atk__, _ok_ = _buf["atk"]; !_ok_ || __json_atk__ == nil { err = errors.New("atk error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_atk__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Atk = __x__ }}
    { var _ok_ bool; var __json_def_id__ interface{}; if __json_def_id__, _ok_ = _buf["def_id"]; !_ok_ || __json_def_id__ == nil { err = errors.New("def_id error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_def_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.DefId = __x__ }}
    { var _ok_ bool; var __json_hp__ interface{}; if __json_hp__, _ok_ = _buf["hp"]; !_ok_ || __json_hp__ == nil { err = errors.New("hp error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hp__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Hp = __x__ }}
    { var _ok_ bool; var __json_clk__ interface{}; if __json_clk__, _ok_ = _buf["clk"]; !_ok_ || __json_clk__ == nil { err = errors.New("clk error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_clk__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Clk = __x__ }}
    return
}

