
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Lord_attr_confTbLordAttrConf struct {
    _dataMap map[int32]*Lord_attr_confLordAttrConf
    _dataList []*Lord_attr_confLordAttrConf
}

func NewLord_attr_confTbLordAttrConf(_buf []map[string]interface{}) (*Lord_attr_confTbLordAttrConf, error) {
    _dataList := make([]*Lord_attr_confLordAttrConf, 0, len(_buf))
    dataMap := make(map[int32]*Lord_attr_confLordAttrConf)

    for _, _ele_ := range _buf {
        if _v, err2 := NewLord_attr_confLordAttrConf(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.HeroId] = _v
        }
    }
    return &Lord_attr_confTbLordAttrConf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Lord_attr_confTbLordAttrConf) GetDataMap() map[int32]*Lord_attr_confLordAttrConf {
    return table._dataMap
}

func (table *Lord_attr_confTbLordAttrConf) GetDataList() []*Lord_attr_confLordAttrConf {
    return table._dataList
}

func (table *Lord_attr_confTbLordAttrConf) Get(key int32) *Lord_attr_confLordAttrConf {
    return table._dataMap[key]
}


