
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Lord_confTbLordConf struct {
    _dataMap map[int32]*Lord_confLordConf
    _dataList []*Lord_confLordConf
}

func NewLord_confTbLordConf(_buf []map[string]interface{}) (*Lord_confTbLordConf, error) {
    _dataList := make([]*Lord_confLordConf, 0, len(_buf))
    dataMap := make(map[int32]*Lord_confLordConf)

    for _, _ele_ := range _buf {
        if _v, err2 := NewLord_confLordConf(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Lord_confTbLordConf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Lord_confTbLordConf) GetDataMap() map[int32]*Lord_confLordConf {
    return table._dataMap
}

func (table *Lord_confTbLordConf) GetDataList() []*Lord_confLordConf {
    return table._dataList
}

func (table *Lord_confTbLordConf) Get(key int32) *Lord_confLordConf {
    return table._dataMap[key]
}


