
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Lord_order_confLordOrderConf struct {
    Id int32
    LordLv int32
    OrderSpend int32
    AtkRatio float32
    HpRatio float32
    DefRatio float32
    Conditions string
}

const TypeId_Lord_order_confLordOrderConf = -26000050

func (*Lord_order_confLordOrderConf) GetTypeId() int32 {
    return -26000050
}

func NewLord_order_confLordOrderConf(_buf map[string]interface{}) (_v *Lord_order_confLordOrderConf, err error) {
    _v = &Lord_order_confLordOrderConf{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_lord_lv__ interface{}; if __json_lord_lv__, _ok_ = _buf["lord_lv"]; !_ok_ || __json_lord_lv__ == nil { err = errors.New("lord_lv error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_lord_lv__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LordLv = __x__ }}
    { var _ok_ bool; var __json_order_spend__ interface{}; if __json_order_spend__, _ok_ = _buf["order_spend"]; !_ok_ || __json_order_spend__ == nil { err = errors.New("order_spend error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_order_spend__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.OrderSpend = __x__ }}
    { var _ok_ bool; var __json_atk_ratio__ interface{}; if __json_atk_ratio__, _ok_ = _buf["atk_ratio"]; !_ok_ || __json_atk_ratio__ == nil { err = errors.New("atk_ratio error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_atk_ratio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.AtkRatio = __x__ }}
    { var _ok_ bool; var __json_hp_ratio__ interface{}; if __json_hp_ratio__, _ok_ = _buf["hp_ratio"]; !_ok_ || __json_hp_ratio__ == nil { err = errors.New("hp_ratio error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hp_ratio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.HpRatio = __x__ }}
    { var _ok_ bool; var __json_def_ratio__ interface{}; if __json_def_ratio__, _ok_ = _buf["def_ratio"]; !_ok_ || __json_def_ratio__ == nil { err = errors.New("def_ratio error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_def_ratio__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.DefRatio = __x__ }}
    { var _ok_ bool; var __json_conditions__ interface{}; if __json_conditions__, _ok_ = _buf["conditions"]; !_ok_ || __json_conditions__ == nil { err = errors.New("conditions error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_conditions__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Conditions = __x__ }}
    return
}

