
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Lord_confLordConf struct {
    Id int32
    Name string
    Type int32
    Normal int32
    Passives string
    Atk int32
    DefId int32
    Hp int32
    Clk int32
}

const TypeId_Lord_confLordConf = 1518837657

func (*Lord_confLordConf) GetTypeId() int32 {
    return 1518837657
}

func NewLord_confLordConf(_buf map[string]interface{}) (_v *Lord_confLordConf, err error) {
    _v = &Lord_confLordConf{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_type__ interface{}; if __json_type__, _ok_ = _buf["type"]; !_ok_ || __json_type__ == nil { err = errors.New("type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_normal__ interface{}; if __json_normal__, _ok_ = _buf["normal"]; !_ok_ || __json_normal__ == nil { err = errors.New("normal error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_normal__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Normal = __x__ }}
    { var _ok_ bool; var __json_passives__ interface{}; if __json_passives__, _ok_ = _buf["passives"]; !_ok_ || __json_passives__ == nil { err = errors.New("passives error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_passives__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Passives = __x__ }}
    { var _ok_ bool; var __json_atk__ interface{}; if __json_atk__, _ok_ = _buf["atk"]; !_ok_ || __json_atk__ == nil { err = errors.New("atk error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_atk__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Atk = __x__ }}
    { var _ok_ bool; var __json_def_id__ interface{}; if __json_def_id__, _ok_ = _buf["def_id"]; !_ok_ || __json_def_id__ == nil { err = errors.New("def_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_def_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.DefId = __x__ }}
    { var _ok_ bool; var __json_hp__ interface{}; if __json_hp__, _ok_ = _buf["hp"]; !_ok_ || __json_hp__ == nil { err = errors.New("hp error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hp__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Hp = __x__ }}
    { var _ok_ bool; var __json_clk__ interface{}; if __json_clk__, _ok_ = _buf["clk"]; !_ok_ || __json_clk__ == nil { err = errors.New("clk error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_clk__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Clk = __x__ }}
    return
}

