
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Lord_lv_confTbLordLvConf struct {
    _dataMap map[int32]*Lord_lv_confLordLvConf
    _dataList []*Lord_lv_confLordLvConf
}

func NewLord_lv_confTbLordLvConf(_buf []map[string]interface{}) (*Lord_lv_confTbLordLvConf, error) {
    _dataList := make([]*Lord_lv_confLordLvConf, 0, len(_buf))
    dataMap := make(map[int32]*Lord_lv_confLordLvConf)

    for _, _ele_ := range _buf {
        if _v, err2 := NewLord_lv_confLordLvConf(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Lord_lv_confTbLordLvConf{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Lord_lv_confTbLordLvConf) GetDataMap() map[int32]*Lord_lv_confLordLvConf {
    return table._dataMap
}

func (table *Lord_lv_confTbLordLvConf) GetDataList() []*Lord_lv_confLordLvConf {
    return table._dataList
}

func (table *Lord_lv_confTbLordLvConf) Get(key int32) *Lord_lv_confLordLvConf {
    return table._dataMap[key]
}


