
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Lottery struct {
    ID int32
    SingleDrawItem *ItemNumPair
    TenDrawItem *ItemNumPair
    SingleDrawRes *ItemNumPair
    TenDrawRes *ItemNumPair
    RewardId int32
    Adtimes int32
}

const TypeId_Lottery = 2019323689

func (*Lottery) GetTypeId() int32 {
    return 2019323689
}

func NewLottery(_buf map[string]interface{}) (_v *Lottery, err error) {
    _v = &Lottery{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    { var _ok_ bool; var __json_SingleDrawItem__ interface{}; if __json_SingleDrawItem__, _ok_ = _buf["SingleDrawItem"]; !_ok_ || __json_SingleDrawItem__ == nil { _v.SingleDrawItem = nil } else { var __x__ *ItemNumPair;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_SingleDrawItem__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewItemNumPair(_x_); err != nil { return } }; _v.SingleDrawItem = __x__ }}
    { var _ok_ bool; var __json_TenDrawItem__ interface{}; if __json_TenDrawItem__, _ok_ = _buf["TenDrawItem"]; !_ok_ || __json_TenDrawItem__ == nil { _v.TenDrawItem = nil } else { var __x__ *ItemNumPair;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_TenDrawItem__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewItemNumPair(_x_); err != nil { return } }; _v.TenDrawItem = __x__ }}
    { var _ok_ bool; var __json_SingleDrawRes__ interface{}; if __json_SingleDrawRes__, _ok_ = _buf["SingleDrawRes"]; !_ok_ || __json_SingleDrawRes__ == nil { _v.SingleDrawRes = nil } else { var __x__ *ItemNumPair;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_SingleDrawRes__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewItemNumPair(_x_); err != nil { return } }; _v.SingleDrawRes = __x__ }}
    { var _ok_ bool; var __json_TenDrawRes__ interface{}; if __json_TenDrawRes__, _ok_ = _buf["TenDrawRes"]; !_ok_ || __json_TenDrawRes__ == nil { _v.TenDrawRes = nil } else { var __x__ *ItemNumPair;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_TenDrawRes__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewItemNumPair(_x_); err != nil { return } }; _v.TenDrawRes = __x__ }}
    { var _ok_ bool; var __json_RewardId__ interface{}; if __json_RewardId__, _ok_ = _buf["RewardId"]; !_ok_ || __json_RewardId__ == nil { err = errors.New("RewardId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RewardId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RewardId = __x__ }}
    { var _ok_ bool; var __json_Adtimes__ interface{}; if __json_Adtimes__, _ok_ = _buf["Adtimes"]; !_ok_ || __json_Adtimes__ == nil { err = errors.New("Adtimes error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Adtimes__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Adtimes = __x__ }}
    return
}

