
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type LuckyWeight struct {
    Weight int32
    Min int32
    Max int32
}

const TypeId_LuckyWeight = 907191136

func (*LuckyWeight) GetTypeId() int32 {
    return 907191136
}

func NewLuckyWeight(_buf map[string]interface{}) (_v *LuckyWeight, err error) {
    _v = &LuckyWeight{}
    { var _ok_ bool; var __json_Weight__ interface{}; if __json_Weight__, _ok_ = _buf["Weight"]; !_ok_ || __json_Weight__ == nil { err = errors.New("Weight error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Weight__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Weight = __x__ }}
    { var _ok_ bool; var __json_Min__ interface{}; if __json_Min__, _ok_ = _buf["Min"]; !_ok_ || __json_Min__ == nil { err = errors.New("Min error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Min__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Min = __x__ }}
    { var _ok_ bool; var __json_Max__ interface{}; if __json_Max__, _ok_ = _buf["Max"]; !_ok_ || __json_Max__ == nil { err = errors.New("Max error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Max__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Max = __x__ }}
    return
}

