
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Lucky struct {
    ID int32
}

const TypeId_Lucky = 73771720

func (*Lucky) GetTypeId() int32 {
    return 73771720
}

func NewLucky(_buf map[string]interface{}) (_v *Lucky, err error) {
    _v = &Lucky{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    return
}

