
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Mail struct {
    MailID int32
    MailType int32
    Items []int32
    IsLimited int32
    LimitDay int32
    LimitTime int32
}

const TypeId_Mail = 2390487

func (*Mail) GetTypeId() int32 {
    return 2390487
}

func NewMail(_buf map[string]interface{}) (_v *Mail, err error) {
    _v = &Mail{}
    { var _ok_ bool; var __json_MailID__ interface{}; if __json_MailID__, _ok_ = _buf["MailID"]; !_ok_ || __json_MailID__ == nil { err = errors.New("MailID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_MailID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MailID = __x__ }}
    { var _ok_ bool; var __json_MailType__ interface{}; if __json_MailType__, _ok_ = _buf["MailType"]; !_ok_ || __json_MailType__ == nil { err = errors.New("MailType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_MailType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MailType = __x__ }}
    { var _ok_ bool; var __json_Items__ interface{}; if __json_Items__, _ok_ = _buf["Items"]; !_ok_ || __json_Items__ == nil { err = errors.New("Items error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_Items__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Items = __x__ }}
    { var _ok_ bool; var __json_IsLimited__ interface{}; if __json_IsLimited__, _ok_ = _buf["IsLimited"]; !_ok_ || __json_IsLimited__ == nil { err = errors.New("IsLimited error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_IsLimited__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.IsLimited = __x__ }}
    { var _ok_ bool; var __json_LimitDay__ interface{}; if __json_LimitDay__, _ok_ = _buf["LimitDay"]; !_ok_ || __json_LimitDay__ == nil { err = errors.New("LimitDay error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_LimitDay__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LimitDay = __x__ }}
    { var _ok_ bool; var __json_LimitTime__ interface{}; if __json_LimitTime__, _ok_ = _buf["LimitTime"]; !_ok_ || __json_LimitTime__ == nil { err = errors.New("LimitTime error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_LimitTime__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LimitTime = __x__ }}
    return
}

