
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Mail_langMailLang struct {
    Id string
    Chinese string
}

const TypeId_Mail_langMailLang = -166038563

func (*Mail_langMailLang) GetTypeId() int32 {
    return -166038563
}

func NewMail_langMailLang(_buf map[string]interface{}) (_v *Mail_langMailLang, err error) {
    _v = &Mail_langMailLang{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_chinese__ interface{}; if __json_chinese__, _ok_ = _buf["chinese"]; !_ok_ || __json_chinese__ == nil { err = errors.New("chinese error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_chinese__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Chinese = __x__ }}
    return
}

