
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Mall struct {
    ShopItemId int32
    GroupId int32
    BuyType int32
    LimitType int32
    LimitNum int32
    Weight int32
    UnlockConditions []*ConditionGroup
    ItemId []int32
    ItemAdd []int32
    ItemdAdd2 []int32
    Sort int32
    MoneyNum float32
    CostNum *ItemNumPair
    ActualCost *ItemNumPair
    FirstPurchase int32
    IsShow int32
    VipPoint int32
    ProductIdIos string
    ProductIdGP string
}

const TypeId_Mall = 2390580

func (*Mall) GetTypeId() int32 {
    return 2390580
}

func NewMall(_buf map[string]interface{}) (_v *Mall, err error) {
    _v = &Mall{}
    { var _ok_ bool; var __json_ShopItemId__ interface{}; if __json_ShopItemId__, _ok_ = _buf["ShopItemId"]; !_ok_ || __json_ShopItemId__ == nil { err = errors.New("ShopItemId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ShopItemId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ShopItemId = __x__ }}
    { var _ok_ bool; var __json_GroupId__ interface{}; if __json_GroupId__, _ok_ = _buf["GroupId"]; !_ok_ || __json_GroupId__ == nil { err = errors.New("GroupId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_GroupId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.GroupId = __x__ }}
    { var _ok_ bool; var __json_BuyType__ interface{}; if __json_BuyType__, _ok_ = _buf["BuyType"]; !_ok_ || __json_BuyType__ == nil { err = errors.New("BuyType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_BuyType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BuyType = __x__ }}
    { var _ok_ bool; var __json_LimitType__ interface{}; if __json_LimitType__, _ok_ = _buf["LimitType"]; !_ok_ || __json_LimitType__ == nil { err = errors.New("LimitType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_LimitType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LimitType = __x__ }}
    { var _ok_ bool; var __json_LimitNum__ interface{}; if __json_LimitNum__, _ok_ = _buf["LimitNum"]; !_ok_ || __json_LimitNum__ == nil { err = errors.New("LimitNum error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_LimitNum__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LimitNum = __x__ }}
    { var _ok_ bool; var __json_Weight__ interface{}; if __json_Weight__, _ok_ = _buf["Weight"]; !_ok_ || __json_Weight__ == nil { err = errors.New("Weight error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Weight__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Weight = __x__ }}
    { var _ok_ bool; var __json_UnlockConditions__ interface{}; if __json_UnlockConditions__, _ok_ = _buf["UnlockConditions"]; !_ok_ || __json_UnlockConditions__ == nil { err = errors.New("UnlockConditions error"); return } else { var __x__ []*ConditionGroup;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_UnlockConditions__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]*ConditionGroup, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ *ConditionGroup
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e0_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v0_ error"); return }; if _list_v0_, err = NewConditionGroup(_x_); err != nil { return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.UnlockConditions = __x__ }}
    { var _ok_ bool; var __json_ItemId__ interface{}; if __json_ItemId__, _ok_ = _buf["ItemId"]; !_ok_ || __json_ItemId__ == nil { err = errors.New("ItemId error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_ItemId__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.ItemId = __x__ }}
    { var _ok_ bool; var __json_ItemAdd__ interface{}; if __json_ItemAdd__, _ok_ = _buf["ItemAdd"]; !_ok_ || __json_ItemAdd__ == nil { err = errors.New("ItemAdd error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_ItemAdd__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.ItemAdd = __x__ }}
    { var _ok_ bool; var __json_ItemdAdd2__ interface{}; if __json_ItemdAdd2__, _ok_ = _buf["ItemdAdd2"]; !_ok_ || __json_ItemdAdd2__ == nil { err = errors.New("ItemdAdd2 error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_ItemdAdd2__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.ItemdAdd2 = __x__ }}
    { var _ok_ bool; var __json_Sort__ interface{}; if __json_Sort__, _ok_ = _buf["Sort"]; !_ok_ || __json_Sort__ == nil { err = errors.New("Sort error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Sort__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Sort = __x__ }}
    { var _ok_ bool; var __json_MoneyNum__ interface{}; if __json_MoneyNum__, _ok_ = _buf["MoneyNum"]; !_ok_ || __json_MoneyNum__ == nil { err = errors.New("MoneyNum error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_MoneyNum__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.MoneyNum = __x__ }}
    { var _ok_ bool; var __json_CostNum__ interface{}; if __json_CostNum__, _ok_ = _buf["CostNum"]; !_ok_ || __json_CostNum__ == nil { _v.CostNum = nil } else { var __x__ *ItemNumPair;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_CostNum__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewItemNumPair(_x_); err != nil { return } }; _v.CostNum = __x__ }}
    { var _ok_ bool; var __json_ActualCost__ interface{}; if __json_ActualCost__, _ok_ = _buf["ActualCost"]; !_ok_ || __json_ActualCost__ == nil { _v.ActualCost = nil } else { var __x__ *ItemNumPair;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_ActualCost__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewItemNumPair(_x_); err != nil { return } }; _v.ActualCost = __x__ }}
    { var _ok_ bool; var __json_FirstPurchase__ interface{}; if __json_FirstPurchase__, _ok_ = _buf["FirstPurchase"]; !_ok_ || __json_FirstPurchase__ == nil { err = errors.New("FirstPurchase error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_FirstPurchase__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.FirstPurchase = __x__ }}
    { var _ok_ bool; var __json_IsShow__ interface{}; if __json_IsShow__, _ok_ = _buf["IsShow"]; !_ok_ || __json_IsShow__ == nil { err = errors.New("IsShow error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_IsShow__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.IsShow = __x__ }}
    { var _ok_ bool; var __json_VipPoint__ interface{}; if __json_VipPoint__, _ok_ = _buf["VipPoint"]; !_ok_ || __json_VipPoint__ == nil { err = errors.New("VipPoint error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_VipPoint__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.VipPoint = __x__ }}
    { var _ok_ bool; var __json_ProductIdIos__ interface{}; if __json_ProductIdIos__, _ok_ = _buf["ProductIdIos"]; !_ok_ || __json_ProductIdIos__ == nil { err = errors.New("ProductIdIos error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_ProductIdIos__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ProductIdIos = __x__ }}
    { var _ok_ bool; var __json_ProductIdGP__ interface{}; if __json_ProductIdGP__, _ok_ = _buf["ProductIdGP"]; !_ok_ || __json_ProductIdGP__ == nil { err = errors.New("ProductIdGP error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_ProductIdGP__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ProductIdGP = __x__ }}
    return
}

