
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type ModuleModule struct {
    Id int32
    Hide int32
    Des string
    AuditPlatform int32
    CheckSwitch string
    Platform int32
    KeyId int32
    UnlockShow int32
    Condition string
    Name string
}

const TypeId_ModuleModule = 1182515278

func (*ModuleModule) GetTypeId() int32 {
    return 1182515278
}

func NewModuleModule(_buf map[string]interface{}) (_v *ModuleModule, err error) {
    _v = &ModuleModule{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_hide__ interface{}; if __json_hide__, _ok_ = _buf["hide"]; !_ok_ || __json_hide__ == nil { err = errors.New("hide error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hide__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Hide = __x__ }}
    { var _ok_ bool; var __json_des__ interface{}; if __json_des__, _ok_ = _buf["des"]; !_ok_ || __json_des__ == nil { err = errors.New("des error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_des__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Des = __x__ }}
    { var _ok_ bool; var __json_audit_platform__ interface{}; if __json_audit_platform__, _ok_ = _buf["audit_platform"]; !_ok_ || __json_audit_platform__ == nil { err = errors.New("audit_platform error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_audit_platform__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AuditPlatform = __x__ }}
    { var _ok_ bool; var __json_check_switch__ interface{}; if __json_check_switch__, _ok_ = _buf["check_switch"]; !_ok_ || __json_check_switch__ == nil { err = errors.New("check_switch error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_check_switch__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CheckSwitch = __x__ }}
    { var _ok_ bool; var __json_platform__ interface{}; if __json_platform__, _ok_ = _buf["platform"]; !_ok_ || __json_platform__ == nil { err = errors.New("platform error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_platform__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Platform = __x__ }}
    { var _ok_ bool; var __json_key_id__ interface{}; if __json_key_id__, _ok_ = _buf["key_id"]; !_ok_ || __json_key_id__ == nil { err = errors.New("key_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_key_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.KeyId = __x__ }}
    { var _ok_ bool; var __json_unlock_show__ interface{}; if __json_unlock_show__, _ok_ = _buf["unlock_show"]; !_ok_ || __json_unlock_show__ == nil { err = errors.New("unlock_show error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_unlock_show__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnlockShow = __x__ }}
    { var _ok_ bool; var __json_condition__ interface{}; if __json_condition__, _ok_ = _buf["condition"]; !_ok_ || __json_condition__ == nil { err = errors.New("condition error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_condition__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Condition = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    return
}

