
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type MonsterMonster struct {
    Id int32
    AbilityType float32
    Club int32
    Work int32
    Attack int32
    HpAbsCoeff int32
    BaseHp float32
    SkinId int32
    BaseAttk float32
    BaseSpeed int32
    BaseDefense int32
    MonsterName string
    OnlyId int32
    Desc string
}

const TypeId_MonsterMonster = 1495842214

func (*MonsterMonster) GetTypeId() int32 {
    return 1495842214
}

func NewMonsterMonster(_buf map[string]interface{}) (_v *MonsterMonster, err error) {
    _v = &MonsterMonster{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_abilityType__ interface{}; if __json_abilityType__, _ok_ = _buf["abilityType"]; !_ok_ || __json_abilityType__ == nil { err = errors.New("abilityType error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_abilityType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.AbilityType = __x__ }}
    { var _ok_ bool; var __json_club__ interface{}; if __json_club__, _ok_ = _buf["club"]; !_ok_ || __json_club__ == nil { err = errors.New("club error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_club__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Club = __x__ }}
    { var _ok_ bool; var __json_work__ interface{}; if __json_work__, _ok_ = _buf["work"]; !_ok_ || __json_work__ == nil { err = errors.New("work error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_work__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Work = __x__ }}
    { var _ok_ bool; var __json_attack__ interface{}; if __json_attack__, _ok_ = _buf["attack"]; !_ok_ || __json_attack__ == nil { err = errors.New("attack error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_attack__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Attack = __x__ }}
    { var _ok_ bool; var __json_hpAbsCoeff__ interface{}; if __json_hpAbsCoeff__, _ok_ = _buf["hpAbsCoeff"]; !_ok_ || __json_hpAbsCoeff__ == nil { err = errors.New("hpAbsCoeff error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_hpAbsCoeff__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.HpAbsCoeff = __x__ }}
    { var _ok_ bool; var __json_baseHp__ interface{}; if __json_baseHp__, _ok_ = _buf["baseHp"]; !_ok_ || __json_baseHp__ == nil { err = errors.New("baseHp error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_baseHp__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.BaseHp = __x__ }}
    { var _ok_ bool; var __json_skinId__ interface{}; if __json_skinId__, _ok_ = _buf["skinId"]; !_ok_ || __json_skinId__ == nil { err = errors.New("skinId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_skinId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SkinId = __x__ }}
    { var _ok_ bool; var __json_baseAttk__ interface{}; if __json_baseAttk__, _ok_ = _buf["baseAttk"]; !_ok_ || __json_baseAttk__ == nil { err = errors.New("baseAttk error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_baseAttk__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.BaseAttk = __x__ }}
    { var _ok_ bool; var __json_baseSpeed__ interface{}; if __json_baseSpeed__, _ok_ = _buf["baseSpeed"]; !_ok_ || __json_baseSpeed__ == nil { err = errors.New("baseSpeed error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_baseSpeed__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BaseSpeed = __x__ }}
    { var _ok_ bool; var __json_baseDefense__ interface{}; if __json_baseDefense__, _ok_ = _buf["baseDefense"]; !_ok_ || __json_baseDefense__ == nil { err = errors.New("baseDefense error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_baseDefense__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BaseDefense = __x__ }}
    { var _ok_ bool; var __json_monsterName__ interface{}; if __json_monsterName__, _ok_ = _buf["monsterName"]; !_ok_ || __json_monsterName__ == nil { err = errors.New("monsterName error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_monsterName__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.MonsterName = __x__ }}
    { var _ok_ bool; var __json_onlyId__ interface{}; if __json_onlyId__, _ok_ = _buf["onlyId"]; !_ok_ || __json_onlyId__ == nil { err = errors.New("onlyId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_onlyId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.OnlyId = __x__ }}
    { var _ok_ bool; var __json_desc__ interface{}; if __json_desc__, _ok_ = _buf["desc"]; !_ok_ || __json_desc__ == nil { err = errors.New("desc error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_desc__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Desc = __x__ }}
    return
}

