
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type PlayerDecor struct {
    PersonResID int32
    Type int32
    UnlockID int32
    IsShow int32
    Sort int32
    Timelimited int32
    ExistenceTime int32
}

const TypeId_PlayerDecor = -2095359260

func (*PlayerDecor) GetTypeId() int32 {
    return -2095359260
}

func NewPlayerDecor(_buf map[string]interface{}) (_v *PlayerDecor, err error) {
    _v = &PlayerDecor{}
    { var _ok_ bool; var __json_PersonResID__ interface{}; if __json_PersonResID__, _ok_ = _buf["PersonResID"]; !_ok_ || __json_PersonResID__ == nil { err = errors.New("PersonResID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_PersonResID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.PersonResID = __x__ }}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_UnlockID__ interface{}; if __json_UnlockID__, _ok_ = _buf["UnlockID"]; !_ok_ || __json_UnlockID__ == nil { err = errors.New("UnlockID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_UnlockID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnlockID = __x__ }}
    { var _ok_ bool; var __json_IsShow__ interface{}; if __json_IsShow__, _ok_ = _buf["IsShow"]; !_ok_ || __json_IsShow__ == nil { err = errors.New("IsShow error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_IsShow__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.IsShow = __x__ }}
    { var _ok_ bool; var __json_Sort__ interface{}; if __json_Sort__, _ok_ = _buf["Sort"]; !_ok_ || __json_Sort__ == nil { err = errors.New("Sort error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Sort__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Sort = __x__ }}
    { var _ok_ bool; var __json_Timelimited__ interface{}; if __json_Timelimited__, _ok_ = _buf["Timelimited"]; !_ok_ || __json_Timelimited__ == nil { err = errors.New("Timelimited error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Timelimited__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Timelimited = __x__ }}
    { var _ok_ bool; var __json_ExistenceTime__ interface{}; if __json_ExistenceTime__, _ok_ = _buf["ExistenceTime"]; !_ok_ || __json_ExistenceTime__ == nil { err = errors.New("ExistenceTime error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ExistenceTime__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExistenceTime = __x__ }}
    return
}

