
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Qi_riTbQiRi struct {
    _dataMap map[int32]*Qi_riQiRi
    _dataList []*Qi_riQiRi
}

func NewQi_riTbQiRi(_buf []map[string]interface{}) (*Qi_riTbQiRi, error) {
    _dataList := make([]*Qi_riQiRi, 0, len(_buf))
    dataMap := make(map[int32]*Qi_riQiRi)

    for _, _ele_ := range _buf {
        if _v, err2 := NewQi_riQiRi(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Qi_riTbQiRi{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Qi_riTbQiRi) GetDataMap() map[int32]*Qi_riQiRi {
    return table._dataMap
}

func (table *Qi_riTbQiRi) GetDataList() []*Qi_riQiRi {
    return table._dataList
}

func (table *Qi_riTbQiRi) Get(key int32) *Qi_riQiRi {
    return table._dataMap[key]
}


