
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Qian_daoQianDao struct {
    Id int32
    Rewards string
    KeyId string
}

const TypeId_Qian_daoQianDao = 2071953815

func (*Qian_daoQianDao) GetTypeId() int32 {
    return 2071953815
}

func NewQian_daoQianDao(_buf map[string]interface{}) (_v *Qian_daoQianDao, err error) {
    _v = &Qian_daoQianDao{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_rewards__ interface{}; if __json_rewards__, _ok_ = _buf["rewards"]; !_ok_ || __json_rewards__ == nil { err = errors.New("rewards error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_rewards__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Rewards = __x__ }}
    { var _ok_ bool; var __json_key_id__ interface{}; if __json_key_id__, _ok_ = _buf["key_id"]; !_ok_ || __json_key_id__ == nil { err = errors.New("key_id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_key_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.KeyId = __x__ }}
    return
}

