
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type RetrievalCoefficient struct {
    CoefficientValue int32
}

const TypeId_RetrievalCoefficient = -1711475327

func (*RetrievalCoefficient) GetTypeId() int32 {
    return -1711475327
}

func NewRetrievalCoefficient(_buf map[string]interface{}) (_v *RetrievalCoefficient, err error) {
    _v = &RetrievalCoefficient{}
    { var _ok_ bool; var __json_CoefficientValue__ interface{}; if __json_CoefficientValue__, _ok_ = _buf["CoefficientValue"]; !_ok_ || __json_CoefficientValue__ == nil { err = errors.New("CoefficientValue error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_CoefficientValue__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CoefficientValue = __x__ }}
    return
}

