
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type RetrievalBase struct {
}

const TypeId_RetrievalBase = -1996310523

func (*RetrievalBase) GetTypeId() int32 {
    return -1996310523
}

func NewRetrievalBase(_buf map[string]interface{}) (interface{}, error) {
    var id string
    var _ok_ bool
    if id, _ok_ = _buf["$type"].(string) ; !_ok_ {
        return nil, errors.New("type id missing")
    }
    switch id {
        case "RetrievalCoefficient": _v, err := NewRetrievalCoefficient(_buf); if err != nil { return nil, errors.New("retrievalcoefficient") } else { return _v, nil }
        case "RetrievalLucky": _v, err := NewRetrievalLucky(_buf); if err != nil { return nil, errors.New("retrievallucky") } else { return _v, nil }
        default: return nil, errors.New("unknown type id")
    }
}


