
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Reward struct {
    RewardId int32
    RewardType int32
    AbsoluteItem *DropItemList
    WeightItem *DropItemPool
    ProbilityItem *DropItemList
    OptionItem *DropItemList
    AbsoluteReward *DropItemList
    WeightReward *DropItemPool
    ProbilityReward *DropItemList
    OptionReward *DropItemList
    BountyItem *BountyItemPair
    BountyReward *BountyItemPair
}

const TypeId_Reward = -1850459313

func (*Reward) GetTypeId() int32 {
    return -1850459313
}

func NewReward(_buf map[string]interface{}) (_v *Reward, err error) {
    _v = &Reward{}
    { var _ok_ bool; var __json_RewardId__ interface{}; if __json_RewardId__, _ok_ = _buf["RewardId"]; !_ok_ || __json_RewardId__ == nil { err = errors.New("RewardId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RewardId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RewardId = __x__ }}
    { var _ok_ bool; var __json_RewardType__ interface{}; if __json_RewardType__, _ok_ = _buf["RewardType"]; !_ok_ || __json_RewardType__ == nil { err = errors.New("RewardType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_RewardType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.RewardType = __x__ }}
    { var _ok_ bool; var __json_AbsoluteItem__ interface{}; if __json_AbsoluteItem__, _ok_ = _buf["AbsoluteItem"]; !_ok_ || __json_AbsoluteItem__ == nil { _v.AbsoluteItem = nil } else { var __x__ *DropItemList;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_AbsoluteItem__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewDropItemList(_x_); err != nil { return } }; _v.AbsoluteItem = __x__ }}
    { var _ok_ bool; var __json_WeightItem__ interface{}; if __json_WeightItem__, _ok_ = _buf["WeightItem"]; !_ok_ || __json_WeightItem__ == nil { _v.WeightItem = nil } else { var __x__ *DropItemPool;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_WeightItem__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewDropItemPool(_x_); err != nil { return } }; _v.WeightItem = __x__ }}
    { var _ok_ bool; var __json_ProbilityItem__ interface{}; if __json_ProbilityItem__, _ok_ = _buf["ProbilityItem"]; !_ok_ || __json_ProbilityItem__ == nil { _v.ProbilityItem = nil } else { var __x__ *DropItemList;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_ProbilityItem__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewDropItemList(_x_); err != nil { return } }; _v.ProbilityItem = __x__ }}
    { var _ok_ bool; var __json_OptionItem__ interface{}; if __json_OptionItem__, _ok_ = _buf["OptionItem"]; !_ok_ || __json_OptionItem__ == nil { _v.OptionItem = nil } else { var __x__ *DropItemList;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_OptionItem__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewDropItemList(_x_); err != nil { return } }; _v.OptionItem = __x__ }}
    { var _ok_ bool; var __json_AbsoluteReward__ interface{}; if __json_AbsoluteReward__, _ok_ = _buf["AbsoluteReward"]; !_ok_ || __json_AbsoluteReward__ == nil { _v.AbsoluteReward = nil } else { var __x__ *DropItemList;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_AbsoluteReward__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewDropItemList(_x_); err != nil { return } }; _v.AbsoluteReward = __x__ }}
    { var _ok_ bool; var __json_WeightReward__ interface{}; if __json_WeightReward__, _ok_ = _buf["WeightReward"]; !_ok_ || __json_WeightReward__ == nil { _v.WeightReward = nil } else { var __x__ *DropItemPool;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_WeightReward__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewDropItemPool(_x_); err != nil { return } }; _v.WeightReward = __x__ }}
    { var _ok_ bool; var __json_ProbilityReward__ interface{}; if __json_ProbilityReward__, _ok_ = _buf["ProbilityReward"]; !_ok_ || __json_ProbilityReward__ == nil { _v.ProbilityReward = nil } else { var __x__ *DropItemList;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_ProbilityReward__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewDropItemList(_x_); err != nil { return } }; _v.ProbilityReward = __x__ }}
    { var _ok_ bool; var __json_OptionReward__ interface{}; if __json_OptionReward__, _ok_ = _buf["OptionReward"]; !_ok_ || __json_OptionReward__ == nil { _v.OptionReward = nil } else { var __x__ *DropItemList;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_OptionReward__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewDropItemList(_x_); err != nil { return } }; _v.OptionReward = __x__ }}
    { var _ok_ bool; var __json_BountyItem__ interface{}; if __json_BountyItem__, _ok_ = _buf["BountyItem"]; !_ok_ || __json_BountyItem__ == nil { _v.BountyItem = nil } else { var __x__ *BountyItemPair;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_BountyItem__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewBountyItemPair(_x_); err != nil { return } }; _v.BountyItem = __x__ }}
    { var _ok_ bool; var __json_BountyReward__ interface{}; if __json_BountyReward__, _ok_ = _buf["BountyReward"]; !_ok_ || __json_BountyReward__ == nil { _v.BountyReward = nil } else { var __x__ *BountyItemPair;  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_BountyReward__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewBountyItemPair(_x_); err != nil { return } }; _v.BountyReward = __x__ }}
    return
}

