
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Role_modelTbRoleModel struct {
    _dataMap map[int32]*Role_modelRoleModel
    _dataList []*Role_modelRoleModel
}

func NewRole_modelTbRoleModel(_buf []map[string]interface{}) (*Role_modelTbRoleModel, error) {
    _dataList := make([]*Role_modelRoleModel, 0, len(_buf))
    dataMap := make(map[int32]*Role_modelRoleModel)

    for _, _ele_ := range _buf {
        if _v, err2 := NewRole_modelRoleModel(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Role_modelTbRoleModel{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Role_modelTbRoleModel) GetDataMap() map[int32]*Role_modelRoleModel {
    return table._dataMap
}

func (table *Role_modelTbRoleModel) GetDataList() []*Role_modelRoleModel {
    return table._dataList
}

func (table *Role_modelTbRoleModel) Get(key int32) *Role_modelRoleModel {
    return table._dataMap[key]
}


