
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Sign struct {
    ID int32
    Type int32
    BasicReward []int32
    PremiumReward []int32
    MakeupType int32
    MakeupCost []int32
}

const TypeId_Sign = 2576861

func (*Sign) GetTypeId() int32 {
    return 2576861
}

func NewSign(_buf map[string]interface{}) (_v *Sign, err error) {
    _v = &Sign{}
    { var _ok_ bool; var __json_ID__ interface{}; if __json_ID__, _ok_ = _buf["ID"]; !_ok_ || __json_ID__ == nil { err = errors.New("ID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ID = __x__ }}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_BasicReward__ interface{}; if __json_BasicReward__, _ok_ = _buf["BasicReward"]; !_ok_ || __json_BasicReward__ == nil { err = errors.New("BasicReward error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_BasicReward__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.BasicReward = __x__ }}
    { var _ok_ bool; var __json_PremiumReward__ interface{}; if __json_PremiumReward__, _ok_ = _buf["PremiumReward"]; !_ok_ || __json_PremiumReward__ == nil { err = errors.New("PremiumReward error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_PremiumReward__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.PremiumReward = __x__ }}
    { var _ok_ bool; var __json_MakeupType__ interface{}; if __json_MakeupType__, _ok_ = _buf["MakeupType"]; !_ok_ || __json_MakeupType__ == nil { err = errors.New("MakeupType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_MakeupType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MakeupType = __x__ }}
    { var _ok_ bool; var __json_MakeupCost__ interface{}; if __json_MakeupCost__, _ok_ = _buf["MakeupCost"]; !_ok_ || __json_MakeupCost__ == nil { err = errors.New("MakeupCost error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_MakeupCost__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.MakeupCost = __x__ }}
    return
}

