
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbSkillWarning struct {
    _dataMap map[int32]*SkillSkillWarning
    _dataList []*SkillSkillWarning
}

func NewSkillTbSkillWarning(_buf []map[string]interface{}) (*SkillTbSkillWarning, error) {
    _dataList := make([]*SkillSkillWarning, 0, len(_buf))
    dataMap := make(map[int32]*SkillSkillWarning)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillSkillWarning(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbSkillWarning{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbSkillWarning) GetDataMap() map[int32]*SkillSkillWarning {
    return table._dataMap
}

func (table *SkillTbSkillWarning) GetDataList() []*SkillSkillWarning {
    return table._dataList
}

func (table *SkillTbSkillWarning) Get(key int32) *SkillSkillWarning {
    return table._dataMap[key]
}


