
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbBlessingEffect struct {
    _dataMap map[int32]*SkillBlessingEffect
    _dataList []*SkillBlessingEffect
}

func NewSkillTbBlessingEffect(_buf []map[string]interface{}) (*SkillTbBlessingEffect, error) {
    _dataList := make([]*SkillBlessingEffect, 0, len(_buf))
    dataMap := make(map[int32]*SkillBlessingEffect)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillBlessingEffect(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbBlessingEffect{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbBlessingEffect) GetDataMap() map[int32]*SkillBlessingEffect {
    return table._dataMap
}

func (table *SkillTbBlessingEffect) GetDataList() []*SkillBlessingEffect {
    return table._dataList
}

func (table *SkillTbBlessingEffect) Get(key int32) *SkillBlessingEffect {
    return table._dataMap[key]
}


