
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbSkillTrigger struct {
    _dataMap map[int32]*SkillSkillTrigger
    _dataList []*SkillSkillTrigger
}

func NewSkillTbSkillTrigger(_buf []map[string]interface{}) (*SkillTbSkillTrigger, error) {
    _dataList := make([]*SkillSkillTrigger, 0, len(_buf))
    dataMap := make(map[int32]*SkillSkillTrigger)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillSkillTrigger(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbSkillTrigger{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbSkillTrigger) GetDataMap() map[int32]*SkillSkillTrigger {
    return table._dataMap
}

func (table *SkillTbSkillTrigger) GetDataList() []*SkillSkillTrigger {
    return table._dataList
}

func (table *SkillTbSkillTrigger) Get(key int32) *SkillSkillTrigger {
    return table._dataMap[key]
}


