
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbBuffTrigger struct {
    _dataMap map[int32]*SkillBuffTrigger
    _dataList []*SkillBuffTrigger
}

func NewSkillTbBuffTrigger(_buf []map[string]interface{}) (*SkillTbBuffTrigger, error) {
    _dataList := make([]*SkillBuffTrigger, 0, len(_buf))
    dataMap := make(map[int32]*SkillBuffTrigger)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillBuffTrigger(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbBuffTrigger{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbBuffTrigger) GetDataMap() map[int32]*SkillBuffTrigger {
    return table._dataMap
}

func (table *SkillTbBuffTrigger) GetDataList() []*SkillBuffTrigger {
    return table._dataList
}

func (table *SkillTbBuffTrigger) Get(key int32) *SkillBuffTrigger {
    return table._dataMap[key]
}


