
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbSkillFindTarget struct {
    _dataMap map[int32]*SkillSkillFindTarget
    _dataList []*SkillSkillFindTarget
}

func NewSkillTbSkillFindTarget(_buf []map[string]interface{}) (*SkillTbSkillFindTarget, error) {
    _dataList := make([]*SkillSkillFindTarget, 0, len(_buf))
    dataMap := make(map[int32]*SkillSkillFindTarget)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillSkillFindTarget(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbSkillFindTarget{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbSkillFindTarget) GetDataMap() map[int32]*SkillSkillFindTarget {
    return table._dataMap
}

func (table *SkillTbSkillFindTarget) GetDataList() []*SkillSkillFindTarget {
    return table._dataList
}

func (table *SkillTbSkillFindTarget) Get(key int32) *SkillSkillFindTarget {
    return table._dataMap[key]
}


