
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbSkillBuffEffect struct {
    _dataMap map[int32]*SkillSkillBuffEffect
    _dataList []*SkillSkillBuffEffect
}

func NewSkillTbSkillBuffEffect(_buf []map[string]interface{}) (*SkillTbSkillBuffEffect, error) {
    _dataList := make([]*SkillSkillBuffEffect, 0, len(_buf))
    dataMap := make(map[int32]*SkillSkillBuffEffect)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillSkillBuffEffect(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbSkillBuffEffect{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbSkillBuffEffect) GetDataMap() map[int32]*SkillSkillBuffEffect {
    return table._dataMap
}

func (table *SkillTbSkillBuffEffect) GetDataList() []*SkillSkillBuffEffect {
    return table._dataList
}

func (table *SkillTbSkillBuffEffect) Get(key int32) *SkillSkillBuffEffect {
    return table._dataMap[key]
}


