
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbSkillTriggerCondition struct {
    _dataMap map[int32]*SkillSkillTriggerCondition
    _dataList []*SkillSkillTriggerCondition
}

func NewSkillTbSkillTriggerCondition(_buf []map[string]interface{}) (*SkillTbSkillTriggerCondition, error) {
    _dataList := make([]*SkillSkillTriggerCondition, 0, len(_buf))
    dataMap := make(map[int32]*SkillSkillTriggerCondition)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillSkillTriggerCondition(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbSkillTriggerCondition{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbSkillTriggerCondition) GetDataMap() map[int32]*SkillSkillTriggerCondition {
    return table._dataMap
}

func (table *SkillTbSkillTriggerCondition) GetDataList() []*SkillSkillTriggerCondition {
    return table._dataList
}

func (table *SkillTbSkillTriggerCondition) Get(key int32) *SkillSkillTriggerCondition {
    return table._dataMap[key]
}


