
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbSkillSummonEffect struct {
    _dataMap map[int32]*SkillSkillSummonEffect
    _dataList []*SkillSkillSummonEffect
}

func NewSkillTbSkillSummonEffect(_buf []map[string]interface{}) (*SkillTbSkillSummonEffect, error) {
    _dataList := make([]*SkillSkillSummonEffect, 0, len(_buf))
    dataMap := make(map[int32]*SkillSkillSummonEffect)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillSkillSummonEffect(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbSkillSummonEffect{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbSkillSummonEffect) GetDataMap() map[int32]*SkillSkillSummonEffect {
    return table._dataMap
}

func (table *SkillTbSkillSummonEffect) GetDataList() []*SkillSkillSummonEffect {
    return table._dataList
}

func (table *SkillTbSkillSummonEffect) Get(key int32) *SkillSkillSummonEffect {
    return table._dataMap[key]
}


