
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type SkillSkillSpecialEffect struct {
    Id int32
}

const TypeId_SkillSkillSpecialEffect = -324508714

func (*SkillSkillSpecialEffect) GetTypeId() int32 {
    return -324508714
}

func NewSkillSkillSpecialEffect(_buf map[string]interface{}) (_v *SkillSkillSpecialEffect, err error) {
    _v = &SkillSkillSpecialEffect{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    return
}

