
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbSkillDamageEffect struct {
    _dataMap map[int32]*SkillSkillDamageEffect
    _dataList []*SkillSkillDamageEffect
}

func NewSkillTbSkillDamageEffect(_buf []map[string]interface{}) (*SkillTbSkillDamageEffect, error) {
    _dataList := make([]*SkillSkillDamageEffect, 0, len(_buf))
    dataMap := make(map[int32]*SkillSkillDamageEffect)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillSkillDamageEffect(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbSkillDamageEffect{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbSkillDamageEffect) GetDataMap() map[int32]*SkillSkillDamageEffect {
    return table._dataMap
}

func (table *SkillTbSkillDamageEffect) GetDataList() []*SkillSkillDamageEffect {
    return table._dataList
}

func (table *SkillTbSkillDamageEffect) Get(key int32) *SkillSkillDamageEffect {
    return table._dataMap[key]
}


