
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type SkillTbSkillSpecialEffect struct {
    _dataMap map[int32]*SkillSkillSpecialEffect
    _dataList []*SkillSkillSpecialEffect
}

func NewSkillTbSkillSpecialEffect(_buf []map[string]interface{}) (*SkillTbSkillSpecialEffect, error) {
    _dataList := make([]*SkillSkillSpecialEffect, 0, len(_buf))
    dataMap := make(map[int32]*SkillSkillSpecialEffect)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSkillSkillSpecialEffect(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SkillTbSkillSpecialEffect{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SkillTbSkillSpecialEffect) GetDataMap() map[int32]*SkillSkillSpecialEffect {
    return table._dataMap
}

func (table *SkillTbSkillSpecialEffect) GetDataList() []*SkillSkillSpecialEffect {
    return table._dataList
}

func (table *SkillTbSkillSpecialEffect) Get(key int32) *SkillSkillSpecialEffect {
    return table._dataMap[key]
}


