
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
    TBChapter *TBChapter
    TBTreasureChestPoints *TBTreasureChestPoints
    TbAttributeDisplay *TbAttributeDisplay
    TbAttributeExpression *TbAttributeExpression
    TbAttributeRetrieval *TbAttributeRetrieval
    TbAudio *TbAudio
    TbBall *TbBall
    TbBlessing *TbBlessing
    TbChapterDifficult *TbChapterDifficult
    TbChapterInfo *TbChapterInfo
    TbChapterLevel *TbChapterLevel
    TbErrorCode *TbErrorCode
    TbFunction *TbFunction
    TbGlobal *TbGlobal
    TbHeroLevel *TbHeroLevel
    TbItem *TbItem
    TbJump *TbJump
    TbLottery *TbLottery
    TbLucky *TbLucky
    TbMail *TbMail
    TbMall *TbMall
    TbMonster *TbMonster
    TbMonsterRageEffect *TbMonsterRageEffect
    TbMonsterShape *TbMonsterShape
    TbPlayerDecor *TbPlayerDecor
    TbReward *TbReward
    TbRole *TbRole
    TbSign *TbSign
    TbSignIn *TbSignIn
    TbTalent *TbTalent
    TbTalentAttrCard *TbTalentAttrCard
    TbTask *TbTask
    TbTaskActivation *TbTaskActivation
    TbWeapon *TbWeapon
    TbBlessingEffect *SkillTbBlessingEffect
    TbBuffTrigger *SkillTbBuffTrigger
    TbCameraShake *SkillTbCameraShake
    TbSkill *SkillTbSkill
    TbSkillAreaDotDamageEffect *SkillTbSkillAreaDotDamageEffect
    TbSkillBuffEffect *SkillTbSkillBuffEffect
    TbSkillBullet *SkillTbSkillBullet
    TbSkillDamageEffect *SkillTbSkillDamageEffect
    TbSkillFindTarget *SkillTbSkillFindTarget
    TbSkillSpecialEffect *SkillTbSkillSpecialEffect
    TbSkillSummonEffect *SkillTbSkillSummonEffect
    TbSkillTrigger *SkillTbSkillTrigger
    TbSkillTriggerCondition *SkillTbSkillTriggerCondition
    TbSkillVFXSFX *SkillTbSkillVFXSFX
    TbSkillWarning *SkillTbSkillWarning
}

func NewTables(loader JsonLoader) (*Tables, error) {
    var err error
    var buf []map[string]interface{}

    tables := &Tables{}
    if buf, err = loader("tbchapter") ; err != nil {
        return nil, err
    }
    if tables.TBChapter, err = NewTBChapter(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbtreasurechestpoints") ; err != nil {
        return nil, err
    }
    if tables.TBTreasureChestPoints, err = NewTBTreasureChestPoints(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbattributedisplay") ; err != nil {
        return nil, err
    }
    if tables.TbAttributeDisplay, err = NewTbAttributeDisplay(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbattributeexpression") ; err != nil {
        return nil, err
    }
    if tables.TbAttributeExpression, err = NewTbAttributeExpression(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbattributeretrieval") ; err != nil {
        return nil, err
    }
    if tables.TbAttributeRetrieval, err = NewTbAttributeRetrieval(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbaudio") ; err != nil {
        return nil, err
    }
    if tables.TbAudio, err = NewTbAudio(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbball") ; err != nil {
        return nil, err
    }
    if tables.TbBall, err = NewTbBall(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbblessing") ; err != nil {
        return nil, err
    }
    if tables.TbBlessing, err = NewTbBlessing(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbchapterdifficult") ; err != nil {
        return nil, err
    }
    if tables.TbChapterDifficult, err = NewTbChapterDifficult(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbchapterinfo") ; err != nil {
        return nil, err
    }
    if tables.TbChapterInfo, err = NewTbChapterInfo(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbchapterlevel") ; err != nil {
        return nil, err
    }
    if tables.TbChapterLevel, err = NewTbChapterLevel(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tberrorcode") ; err != nil {
        return nil, err
    }
    if tables.TbErrorCode, err = NewTbErrorCode(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbfunction") ; err != nil {
        return nil, err
    }
    if tables.TbFunction, err = NewTbFunction(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbglobal") ; err != nil {
        return nil, err
    }
    if tables.TbGlobal, err = NewTbGlobal(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbherolevel") ; err != nil {
        return nil, err
    }
    if tables.TbHeroLevel, err = NewTbHeroLevel(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbitem") ; err != nil {
        return nil, err
    }
    if tables.TbItem, err = NewTbItem(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbjump") ; err != nil {
        return nil, err
    }
    if tables.TbJump, err = NewTbJump(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tblottery") ; err != nil {
        return nil, err
    }
    if tables.TbLottery, err = NewTbLottery(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tblucky") ; err != nil {
        return nil, err
    }
    if tables.TbLucky, err = NewTbLucky(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbmail") ; err != nil {
        return nil, err
    }
    if tables.TbMail, err = NewTbMail(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbmall") ; err != nil {
        return nil, err
    }
    if tables.TbMall, err = NewTbMall(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbmonster") ; err != nil {
        return nil, err
    }
    if tables.TbMonster, err = NewTbMonster(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbmonsterrageeffect") ; err != nil {
        return nil, err
    }
    if tables.TbMonsterRageEffect, err = NewTbMonsterRageEffect(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbmonstershape") ; err != nil {
        return nil, err
    }
    if tables.TbMonsterShape, err = NewTbMonsterShape(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbplayerdecor") ; err != nil {
        return nil, err
    }
    if tables.TbPlayerDecor, err = NewTbPlayerDecor(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbreward") ; err != nil {
        return nil, err
    }
    if tables.TbReward, err = NewTbReward(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbrole") ; err != nil {
        return nil, err
    }
    if tables.TbRole, err = NewTbRole(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbsign") ; err != nil {
        return nil, err
    }
    if tables.TbSign, err = NewTbSign(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbsignin") ; err != nil {
        return nil, err
    }
    if tables.TbSignIn, err = NewTbSignIn(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbtalent") ; err != nil {
        return nil, err
    }
    if tables.TbTalent, err = NewTbTalent(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbtalentattrcard") ; err != nil {
        return nil, err
    }
    if tables.TbTalentAttrCard, err = NewTbTalentAttrCard(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbtask") ; err != nil {
        return nil, err
    }
    if tables.TbTask, err = NewTbTask(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbtaskactivation") ; err != nil {
        return nil, err
    }
    if tables.TbTaskActivation, err = NewTbTaskActivation(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbweapon") ; err != nil {
        return nil, err
    }
    if tables.TbWeapon, err = NewTbWeapon(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbblessingeffect") ; err != nil {
        return nil, err
    }
    if tables.TbBlessingEffect, err = NewSkillTbBlessingEffect(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbbufftrigger") ; err != nil {
        return nil, err
    }
    if tables.TbBuffTrigger, err = NewSkillTbBuffTrigger(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbcamerashake") ; err != nil {
        return nil, err
    }
    if tables.TbCameraShake, err = NewSkillTbCameraShake(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskill") ; err != nil {
        return nil, err
    }
    if tables.TbSkill, err = NewSkillTbSkill(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskillareadotdamageeffect") ; err != nil {
        return nil, err
    }
    if tables.TbSkillAreaDotDamageEffect, err = NewSkillTbSkillAreaDotDamageEffect(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskillbuffeffect") ; err != nil {
        return nil, err
    }
    if tables.TbSkillBuffEffect, err = NewSkillTbSkillBuffEffect(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskillbullet") ; err != nil {
        return nil, err
    }
    if tables.TbSkillBullet, err = NewSkillTbSkillBullet(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskilldamageeffect") ; err != nil {
        return nil, err
    }
    if tables.TbSkillDamageEffect, err = NewSkillTbSkillDamageEffect(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskillfindtarget") ; err != nil {
        return nil, err
    }
    if tables.TbSkillFindTarget, err = NewSkillTbSkillFindTarget(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskillspecialeffect") ; err != nil {
        return nil, err
    }
    if tables.TbSkillSpecialEffect, err = NewSkillTbSkillSpecialEffect(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskillsummoneffect") ; err != nil {
        return nil, err
    }
    if tables.TbSkillSummonEffect, err = NewSkillTbSkillSummonEffect(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskilltrigger") ; err != nil {
        return nil, err
    }
    if tables.TbSkillTrigger, err = NewSkillTbSkillTrigger(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskilltriggercondition") ; err != nil {
        return nil, err
    }
    if tables.TbSkillTriggerCondition, err = NewSkillTbSkillTriggerCondition(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskillvfxsfx") ; err != nil {
        return nil, err
    }
    if tables.TbSkillVFXSFX, err = NewSkillTbSkillVFXSFX(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("skill_tbskillwarning") ; err != nil {
        return nil, err
    }
    if tables.TbSkillWarning, err = NewSkillTbSkillWarning(buf) ; err != nil {
        return nil, err
    }
    return tables, nil
}


