
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
    TbConstant *ConfigTbConstant
    TbItem *ItemTbItem
    TbHeroAttr *Hero_attrTbHeroAttr
    TbGetFrom *Get_fromTbGetFrom
    TbRoleModel *Role_modelTbRoleModel
    TbHeroLvSpend *Hero_lv_spendTbHeroLvSpend
    TbHeroOrder *Hero_orderTbHeroOrder
    TbHeroStarExt *Hero_star_extTbHeroStarExt
    TbCard *CardTbCard
    TbMonster *MonsterTbMonster
    TbBattle *BattleTbBattle
    TbLevelCoeff *Level_coeffTbLevelCoeff
    TbAuto *AutoTbAuto
    TbEquipment *EquipmentTbEquipment
    TbEquipmentLv *Equipment_lvTbEquipmentLv
    TbEquipmentColor *Equipment_colorTbEquipmentColor
    TbGuaJiDengJi *Gua_ji_deng_jiTbGuaJiDengJi
    TbGuaJiJinBi *Gua_ji_jin_biTbGuaJiJinBi
    TbGuaJiShiChang *Gua_ji_shi_changTbGuaJiShiChang
    TbGuaJiWuPin *Gua_ji_wu_pinTbGuaJiWuPin
    TbWeekZhaoMu *Week_zhao_muTbWeekZhaoMu
    TbBox *BoxTbBox
    TbBoxStage *Box_stageTbBoxStage
    TbVip *VipTbVip
    TbVipBenefit *Vip_benefitTbVipBenefit
    TbLiBao *Li_baoTbLiBao
    TbDailyDeal *Daily_dealTbDailyDeal
    TbGoldShop *Gold_shopTbGoldShop
    TbGoldBuy *Gold_buyTbGoldBuy
    TbQianDao *Qian_daoTbQianDao
    TbQiRi *Qi_riTbQiRi
    TbDailyTask *Daily_taskTbDailyTask
    TbMailLang *Mail_langTbMailLang
    TbModule *ModuleTbModule
    TbLordConf *Lord_confTbLordConf
    TbLordLvConf *Lord_lv_confTbLordLvConf
    TbLordOrderConf *Lord_order_confTbLordOrderConf
    TbLordAttrConf *Lord_attr_confTbLordAttrConf
    TbBookConf *Book_confTbBookConf
    TbHeroBaseEquip *Hero_base_equipTbHeroBaseEquip
    TbBuff *BuffTbBuff
    TbHeroSkill *Hero_skillTbHeroSkill
    TbCfgActivity *ConfigTbCfgActivity
    TbBuffEffect *Buff_effectTbBuffEffect
    TbFormula *Buff_formulaTbFormula
    TbCfgKanbanMaid *ConfigTbCfgKanbanMaid
}

func NewTables(loader JsonLoader) (*Tables, error) {
    var err error
    var buf []map[string]interface{}

    tables := &Tables{}
    if buf, err = loader("config_tbconstant") ; err != nil {
        return nil, err
    }
    if tables.TbConstant, err = NewConfigTbConstant(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("item_tbitem") ; err != nil {
        return nil, err
    }
    if tables.TbItem, err = NewItemTbItem(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("hero_attr_tbheroattr") ; err != nil {
        return nil, err
    }
    if tables.TbHeroAttr, err = NewHero_attrTbHeroAttr(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("get_from_tbgetfrom") ; err != nil {
        return nil, err
    }
    if tables.TbGetFrom, err = NewGet_fromTbGetFrom(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("role_model_tbrolemodel") ; err != nil {
        return nil, err
    }
    if tables.TbRoleModel, err = NewRole_modelTbRoleModel(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("hero_lv_spend_tbherolvspend") ; err != nil {
        return nil, err
    }
    if tables.TbHeroLvSpend, err = NewHero_lv_spendTbHeroLvSpend(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("hero_order_tbheroorder") ; err != nil {
        return nil, err
    }
    if tables.TbHeroOrder, err = NewHero_orderTbHeroOrder(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("hero_star_ext_tbherostarext") ; err != nil {
        return nil, err
    }
    if tables.TbHeroStarExt, err = NewHero_star_extTbHeroStarExt(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("card_tbcard") ; err != nil {
        return nil, err
    }
    if tables.TbCard, err = NewCardTbCard(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("monster_tbmonster") ; err != nil {
        return nil, err
    }
    if tables.TbMonster, err = NewMonsterTbMonster(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("battle_tbbattle") ; err != nil {
        return nil, err
    }
    if tables.TbBattle, err = NewBattleTbBattle(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("level_coeff_tblevelcoeff") ; err != nil {
        return nil, err
    }
    if tables.TbLevelCoeff, err = NewLevel_coeffTbLevelCoeff(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("auto_tbauto") ; err != nil {
        return nil, err
    }
    if tables.TbAuto, err = NewAutoTbAuto(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("equipment_tbequipment") ; err != nil {
        return nil, err
    }
    if tables.TbEquipment, err = NewEquipmentTbEquipment(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("equipment_lv_tbequipmentlv") ; err != nil {
        return nil, err
    }
    if tables.TbEquipmentLv, err = NewEquipment_lvTbEquipmentLv(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("equipment_color_tbequipmentcolor") ; err != nil {
        return nil, err
    }
    if tables.TbEquipmentColor, err = NewEquipment_colorTbEquipmentColor(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("gua_ji_deng_ji_tbguajidengji") ; err != nil {
        return nil, err
    }
    if tables.TbGuaJiDengJi, err = NewGua_ji_deng_jiTbGuaJiDengJi(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("gua_ji_jin_bi_tbguajijinbi") ; err != nil {
        return nil, err
    }
    if tables.TbGuaJiJinBi, err = NewGua_ji_jin_biTbGuaJiJinBi(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("gua_ji_shi_chang_tbguajishichang") ; err != nil {
        return nil, err
    }
    if tables.TbGuaJiShiChang, err = NewGua_ji_shi_changTbGuaJiShiChang(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("gua_ji_wu_pin_tbguajiwupin") ; err != nil {
        return nil, err
    }
    if tables.TbGuaJiWuPin, err = NewGua_ji_wu_pinTbGuaJiWuPin(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("week_zhao_mu_tbweekzhaomu") ; err != nil {
        return nil, err
    }
    if tables.TbWeekZhaoMu, err = NewWeek_zhao_muTbWeekZhaoMu(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("box_tbbox") ; err != nil {
        return nil, err
    }
    if tables.TbBox, err = NewBoxTbBox(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("box_stage_tbboxstage") ; err != nil {
        return nil, err
    }
    if tables.TbBoxStage, err = NewBox_stageTbBoxStage(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("vip_tbvip") ; err != nil {
        return nil, err
    }
    if tables.TbVip, err = NewVipTbVip(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("vip_benefit_tbvipbenefit") ; err != nil {
        return nil, err
    }
    if tables.TbVipBenefit, err = NewVip_benefitTbVipBenefit(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("li_bao_tblibao") ; err != nil {
        return nil, err
    }
    if tables.TbLiBao, err = NewLi_baoTbLiBao(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("daily_deal_tbdailydeal") ; err != nil {
        return nil, err
    }
    if tables.TbDailyDeal, err = NewDaily_dealTbDailyDeal(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("gold_shop_tbgoldshop") ; err != nil {
        return nil, err
    }
    if tables.TbGoldShop, err = NewGold_shopTbGoldShop(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("gold_buy_tbgoldbuy") ; err != nil {
        return nil, err
    }
    if tables.TbGoldBuy, err = NewGold_buyTbGoldBuy(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("qian_dao_tbqiandao") ; err != nil {
        return nil, err
    }
    if tables.TbQianDao, err = NewQian_daoTbQianDao(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("qi_ri_tbqiri") ; err != nil {
        return nil, err
    }
    if tables.TbQiRi, err = NewQi_riTbQiRi(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("daily_task_tbdailytask") ; err != nil {
        return nil, err
    }
    if tables.TbDailyTask, err = NewDaily_taskTbDailyTask(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("mail_lang_tbmaillang") ; err != nil {
        return nil, err
    }
    if tables.TbMailLang, err = NewMail_langTbMailLang(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("module_tbmodule") ; err != nil {
        return nil, err
    }
    if tables.TbModule, err = NewModuleTbModule(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("lord_conf_tblordconf") ; err != nil {
        return nil, err
    }
    if tables.TbLordConf, err = NewLord_confTbLordConf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("lord_lv_conf_tblordlvconf") ; err != nil {
        return nil, err
    }
    if tables.TbLordLvConf, err = NewLord_lv_confTbLordLvConf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("lord_order_conf_tblordorderconf") ; err != nil {
        return nil, err
    }
    if tables.TbLordOrderConf, err = NewLord_order_confTbLordOrderConf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("lord_attr_conf_tblordattrconf") ; err != nil {
        return nil, err
    }
    if tables.TbLordAttrConf, err = NewLord_attr_confTbLordAttrConf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("book_conf_tbbookconf") ; err != nil {
        return nil, err
    }
    if tables.TbBookConf, err = NewBook_confTbBookConf(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("hero_base_equip_tbherobaseequip") ; err != nil {
        return nil, err
    }
    if tables.TbHeroBaseEquip, err = NewHero_base_equipTbHeroBaseEquip(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("buff_tbbuff") ; err != nil {
        return nil, err
    }
    if tables.TbBuff, err = NewBuffTbBuff(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("hero_skill_tbheroskill") ; err != nil {
        return nil, err
    }
    if tables.TbHeroSkill, err = NewHero_skillTbHeroSkill(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("config_tbcfgactivity") ; err != nil {
        return nil, err
    }
    if tables.TbCfgActivity, err = NewConfigTbCfgActivity(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("buff_effect_tbbuffeffect") ; err != nil {
        return nil, err
    }
    if tables.TbBuffEffect, err = NewBuff_effectTbBuffEffect(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("buff_formula_tbformula") ; err != nil {
        return nil, err
    }
    if tables.TbFormula, err = NewBuff_formulaTbFormula(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("config_tbcfgkanbanmaid") ; err != nil {
        return nil, err
    }
    if tables.TbCfgKanbanMaid, err = NewConfigTbCfgKanbanMaid(buf) ; err != nil {
        return nil, err
    }
    return tables, nil
}


