
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Talent struct {
    Id int32
    Grade int32
    Type int32
    Cost []int32
    CardAttrIDs []int32
    CardAttrTypes []int32
    CardAttrVals []int32
    NextNode int32
}

const TypeId_Talent = -1797219060

func (*Talent) GetTypeId() int32 {
    return -1797219060
}

func NewTalent(_buf map[string]interface{}) (_v *Talent, err error) {
    _v = &Talent{}
    { var _ok_ bool; var __json_Id__ interface{}; if __json_Id__, _ok_ = _buf["Id"]; !_ok_ || __json_Id__ == nil { err = errors.New("Id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_Grade__ interface{}; if __json_Grade__, _ok_ = _buf["Grade"]; !_ok_ || __json_Grade__ == nil { err = errors.New("Grade error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Grade__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Grade = __x__ }}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_Cost__ interface{}; if __json_Cost__, _ok_ = _buf["Cost"]; !_ok_ || __json_Cost__ == nil { err = errors.New("Cost error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_Cost__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Cost = __x__ }}
    { var _ok_ bool; var __json_CardAttrIDs__ interface{}; if __json_CardAttrIDs__, _ok_ = _buf["CardAttrIDs"]; !_ok_ || __json_CardAttrIDs__ == nil { err = errors.New("CardAttrIDs error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_CardAttrIDs__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.CardAttrIDs = __x__ }}
    { var _ok_ bool; var __json_CardAttrTypes__ interface{}; if __json_CardAttrTypes__, _ok_ = _buf["CardAttrTypes"]; !_ok_ || __json_CardAttrTypes__ == nil { err = errors.New("CardAttrTypes error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_CardAttrTypes__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.CardAttrTypes = __x__ }}
    { var _ok_ bool; var __json_CardAttrVals__ interface{}; if __json_CardAttrVals__, _ok_ = _buf["CardAttrVals"]; !_ok_ || __json_CardAttrVals__ == nil { err = errors.New("CardAttrVals error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_CardAttrVals__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.CardAttrVals = __x__ }}
    { var _ok_ bool; var __json_NextNode__ interface{}; if __json_NextNode__, _ok_ = _buf["NextNode"]; !_ok_ || __json_NextNode__ == nil { err = errors.New("NextNode error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_NextNode__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.NextNode = __x__ }}
    return
}

