
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type TalentAttrCard struct {
    Id int32
    Cardtype1 int32
    MAXLevel int32
    Cost []int32
    CardAttrIDs []int32
    CardAttrTypes []int32
    CardAttrVals []int32
}

const TypeId_TalentAttrCard = -989815347

func (*TalentAttrCard) GetTypeId() int32 {
    return -989815347
}

func NewTalentAttrCard(_buf map[string]interface{}) (_v *TalentAttrCard, err error) {
    _v = &TalentAttrCard{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_Cardtype1__ interface{}; if __json_Cardtype1__, _ok_ = _buf["Cardtype1"]; !_ok_ || __json_Cardtype1__ == nil { err = errors.New("Cardtype1 error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Cardtype1__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Cardtype1 = __x__ }}
    { var _ok_ bool; var __json_MAXLevel__ interface{}; if __json_MAXLevel__, _ok_ = _buf["MAXLevel"]; !_ok_ || __json_MAXLevel__ == nil { err = errors.New("MAXLevel error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_MAXLevel__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MAXLevel = __x__ }}
    { var _ok_ bool; var __json_Cost__ interface{}; if __json_Cost__, _ok_ = _buf["Cost"]; !_ok_ || __json_Cost__ == nil { err = errors.New("Cost error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_Cost__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Cost = __x__ }}
    { var _ok_ bool; var __json_CardAttrIDs__ interface{}; if __json_CardAttrIDs__, _ok_ = _buf["CardAttrIDs"]; !_ok_ || __json_CardAttrIDs__ == nil { err = errors.New("CardAttrIDs error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_CardAttrIDs__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.CardAttrIDs = __x__ }}
    { var _ok_ bool; var __json_CardAttrTypes__ interface{}; if __json_CardAttrTypes__, _ok_ = _buf["CardAttrTypes"]; !_ok_ || __json_CardAttrTypes__ == nil { err = errors.New("CardAttrTypes error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_CardAttrTypes__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.CardAttrTypes = __x__ }}
    { var _ok_ bool; var __json_CardAttrVals__ interface{}; if __json_CardAttrVals__, _ok_ = _buf["CardAttrVals"]; !_ok_ || __json_CardAttrVals__ == nil { err = errors.New("CardAttrVals error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_CardAttrVals__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.CardAttrVals = __x__ }}
    return
}

