
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Task struct {
    TaskID int32
    AddUpGroup int32
    TaskSorting int32
    TaskType int32
    ConditionType int32
    Key []int32
    RewardItem []int32
    TaskActivation int32
    ActivationType []int32
    TaskUnlock int32
    JumpID int32
    TaskAddUpGroupKey int64
    TaskResetType int32
}

const TypeId_Task = 2599333

func (*Task) GetTypeId() int32 {
    return 2599333
}

func NewTask(_buf map[string]interface{}) (_v *Task, err error) {
    _v = &Task{}
    { var _ok_ bool; var __json_TaskID__ interface{}; if __json_TaskID__, _ok_ = _buf["TaskID"]; !_ok_ || __json_TaskID__ == nil { err = errors.New("TaskID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_TaskID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TaskID = __x__ }}
    { var _ok_ bool; var __json_AddUpGroup__ interface{}; if __json_AddUpGroup__, _ok_ = _buf["AddUpGroup"]; !_ok_ || __json_AddUpGroup__ == nil { err = errors.New("AddUpGroup error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_AddUpGroup__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.AddUpGroup = __x__ }}
    { var _ok_ bool; var __json_TaskSorting__ interface{}; if __json_TaskSorting__, _ok_ = _buf["TaskSorting"]; !_ok_ || __json_TaskSorting__ == nil { err = errors.New("TaskSorting error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_TaskSorting__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TaskSorting = __x__ }}
    { var _ok_ bool; var __json_TaskType__ interface{}; if __json_TaskType__, _ok_ = _buf["TaskType"]; !_ok_ || __json_TaskType__ == nil { err = errors.New("TaskType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_TaskType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TaskType = __x__ }}
    { var _ok_ bool; var __json_ConditionType__ interface{}; if __json_ConditionType__, _ok_ = _buf["ConditionType"]; !_ok_ || __json_ConditionType__ == nil { err = errors.New("ConditionType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ConditionType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ConditionType = __x__ }}
    { var _ok_ bool; var __json_Key__ interface{}; if __json_Key__, _ok_ = _buf["Key"]; !_ok_ || __json_Key__ == nil { err = errors.New("Key error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_Key__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Key = __x__ }}
    { var _ok_ bool; var __json_RewardItem__ interface{}; if __json_RewardItem__, _ok_ = _buf["RewardItem"]; !_ok_ || __json_RewardItem__ == nil { err = errors.New("RewardItem error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_RewardItem__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.RewardItem = __x__ }}
    { var _ok_ bool; var __json_TaskActivation__ interface{}; if __json_TaskActivation__, _ok_ = _buf["TaskActivation"]; !_ok_ || __json_TaskActivation__ == nil { err = errors.New("TaskActivation error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_TaskActivation__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TaskActivation = __x__ }}
    { var _ok_ bool; var __json_ActivationType__ interface{}; if __json_ActivationType__, _ok_ = _buf["ActivationType"]; !_ok_ || __json_ActivationType__ == nil { err = errors.New("ActivationType error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_ActivationType__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.ActivationType = __x__ }}
    { var _ok_ bool; var __json_TaskUnlock__ interface{}; if __json_TaskUnlock__, _ok_ = _buf["TaskUnlock"]; !_ok_ || __json_TaskUnlock__ == nil { err = errors.New("TaskUnlock error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_TaskUnlock__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TaskUnlock = __x__ }}
    { var _ok_ bool; var __json_JumpID__ interface{}; if __json_JumpID__, _ok_ = _buf["JumpID"]; !_ok_ || __json_JumpID__ == nil { err = errors.New("JumpID error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_JumpID__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.JumpID = __x__ }}
    { var _ok_ bool; var __json_TaskAddUpGroupKey__ interface{}; if __json_TaskAddUpGroupKey__, _ok_ = _buf["TaskAddUpGroupKey"]; !_ok_ || __json_TaskAddUpGroupKey__ == nil { err = errors.New("TaskAddUpGroupKey error"); return } else { var __x__ int64;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_TaskAddUpGroupKey__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int64(_x_) }; _v.TaskAddUpGroupKey = __x__ }}
    { var _ok_ bool; var __json_TaskResetType__ interface{}; if __json_TaskResetType__, _ok_ = _buf["TaskResetType"]; !_ok_ || __json_TaskResetType__ == nil { err = errors.New("TaskResetType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_TaskResetType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TaskResetType = __x__ }}
    return
}

