
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type TaskActivation struct {
    Id int32
    Type int32
    Sort int32
    ActivationCondition int32
    ActivationReward []int32
    ResetType int32
}

const TypeId_TaskActivation = 491519131

func (*TaskActivation) GetTypeId() int32 {
    return 491519131
}

func NewTaskActivation(_buf map[string]interface{}) (_v *TaskActivation, err error) {
    _v = &TaskActivation{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_Type__ interface{}; if __json_Type__, _ok_ = _buf["Type"]; !_ok_ || __json_Type__ == nil { err = errors.New("Type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_Sort__ interface{}; if __json_Sort__, _ok_ = _buf["Sort"]; !_ok_ || __json_Sort__ == nil { err = errors.New("Sort error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Sort__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Sort = __x__ }}
    { var _ok_ bool; var __json_ActivationCondition__ interface{}; if __json_ActivationCondition__, _ok_ = _buf["ActivationCondition"]; !_ok_ || __json_ActivationCondition__ == nil { err = errors.New("ActivationCondition error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ActivationCondition__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ActivationCondition = __x__ }}
    { var _ok_ bool; var __json_ActivationReward__ interface{}; if __json_ActivationReward__, _ok_ = _buf["ActivationReward"]; !_ok_ || __json_ActivationReward__ == nil { err = errors.New("ActivationReward error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_ActivationReward__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.ActivationReward = __x__ }}
    { var _ok_ bool; var __json_ResetType__ interface{}; if __json_ResetType__, _ok_ = _buf["ResetType"]; !_ok_ || __json_ResetType__ == nil { err = errors.New("ResetType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ResetType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ResetType = __x__ }}
    return
}

