
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbAttributeRetrieval struct {
    _dataMap map[int32]*AttributeRetrieval
    _dataList []*AttributeRetrieval
}

func NewTbAttributeRetrieval(_buf []map[string]interface{}) (*TbAttributeRetrieval, error) {
    _dataList := make([]*AttributeRetrieval, 0, len(_buf))
    dataMap := make(map[int32]*AttributeRetrieval)

    for _, _ele_ := range _buf {
        if _v, err2 := NewAttributeRetrieval(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbAttributeRetrieval{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbAttributeRetrieval) GetDataMap() map[int32]*AttributeRetrieval {
    return table._dataMap
}

func (table *TbAttributeRetrieval) GetDataList() []*AttributeRetrieval {
    return table._dataList
}

func (table *TbAttributeRetrieval) Get(key int32) *AttributeRetrieval {
    return table._dataMap[key]
}


