
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbAttributeExpression struct {
    _dataMap map[int32]*AttributeExpression
    _dataList []*AttributeExpression
}

func NewTbAttributeExpression(_buf []map[string]interface{}) (*TbAttributeExpression, error) {
    _dataList := make([]*AttributeExpression, 0, len(_buf))
    dataMap := make(map[int32]*AttributeExpression)

    for _, _ele_ := range _buf {
        if _v, err2 := NewAttributeExpression(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbAttributeExpression{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbAttributeExpression) GetDataMap() map[int32]*AttributeExpression {
    return table._dataMap
}

func (table *TbAttributeExpression) GetDataList() []*AttributeExpression {
    return table._dataList
}

func (table *TbAttributeExpression) Get(key int32) *AttributeExpression {
    return table._dataMap[key]
}


