
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbAudio struct {
    _dataMap map[string]*Audio
    _dataList []*Audio
}

func NewTbAudio(_buf []map[string]interface{}) (*TbAudio, error) {
    _dataList := make([]*Audio, 0, len(_buf))
    dataMap := make(map[string]*Audio)

    for _, _ele_ := range _buf {
        if _v, err2 := NewAudio(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Key] = _v
        }
    }
    return &TbAudio{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbAudio) GetDataMap() map[string]*Audio {
    return table._dataMap
}

func (table *TbAudio) GetDataList() []*Audio {
    return table._dataList
}

func (table *TbAudio) Get(key string) *Audio {
    return table._dataMap[key]
}


