
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbBall struct {
    _dataMap map[int32]*Ball
    _dataList []*Ball
}

func NewTbBall(_buf []map[string]interface{}) (*TbBall, error) {
    _dataList := make([]*Ball, 0, len(_buf))
    dataMap := make(map[int32]*Ball)

    for _, _ele_ := range _buf {
        if _v, err2 := NewBall(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbBall{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbBall) GetDataMap() map[int32]*Ball {
    return table._dataMap
}

func (table *TbBall) GetDataList() []*Ball {
    return table._dataList
}

func (table *TbBall) Get(key int32) *Ball {
    return table._dataMap[key]
}


