
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbBlessing struct {
    _dataMap map[int32]*Blessing
    _dataList []*Blessing
}

func NewTbBlessing(_buf []map[string]interface{}) (*TbBlessing, error) {
    _dataList := make([]*Blessing, 0, len(_buf))
    dataMap := make(map[int32]*Blessing)

    for _, _ele_ := range _buf {
        if _v, err2 := NewBlessing(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbBlessing{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbBlessing) GetDataMap() map[int32]*Blessing {
    return table._dataMap
}

func (table *TbBlessing) GetDataList() []*Blessing {
    return table._dataList
}

func (table *TbBlessing) Get(key int32) *Blessing {
    return table._dataMap[key]
}


