
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TBChapter struct {
    _dataList []*DataChapter
}

func NewTBChapter(_buf []map[string]interface{}) (*TBChapter, error) {
    _dataList := make([]*DataChapter, 0, len(_buf))
    for _, _ele_ := range _buf {
        if _v, err2 := NewDataChapter(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
        }
    }
    return &TBChapter{_dataList:_dataList}, nil
}

func (table *TBChapter) GetDataList() []*DataChapter {
    return table._dataList
}

func (table *TBChapter) Get(index int) *DataChapter {
    return table._dataList[index]
}


