
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbChapterLevel struct {
    _dataMap map[int32]*ChapterLevel
    _dataList []*ChapterLevel
}

func NewTbChapterLevel(_buf []map[string]interface{}) (*TbChapterLevel, error) {
    _dataList := make([]*ChapterLevel, 0, len(_buf))
    dataMap := make(map[int32]*ChapterLevel)

    for _, _ele_ := range _buf {
        if _v, err2 := NewChapterLevel(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbChapterLevel{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbChapterLevel) GetDataMap() map[int32]*ChapterLevel {
    return table._dataMap
}

func (table *TbChapterLevel) GetDataList() []*ChapterLevel {
    return table._dataList
}

func (table *TbChapterLevel) Get(key int32) *ChapterLevel {
    return table._dataMap[key]
}


