
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbChapterDifficult struct {
    _dataMap map[int32]*ChapterDifficult
    _dataList []*ChapterDifficult
}

func NewTbChapterDifficult(_buf []map[string]interface{}) (*TbChapterDifficult, error) {
    _dataList := make([]*ChapterDifficult, 0, len(_buf))
    dataMap := make(map[int32]*ChapterDifficult)

    for _, _ele_ := range _buf {
        if _v, err2 := NewChapterDifficult(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &TbChapterDifficult{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbChapterDifficult) GetDataMap() map[int32]*ChapterDifficult {
    return table._dataMap
}

func (table *TbChapterDifficult) GetDataList() []*ChapterDifficult {
    return table._dataList
}

func (table *TbChapterDifficult) Get(key int32) *ChapterDifficult {
    return table._dataMap[key]
}


