
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbChapterInfo struct {
    _dataMap map[int32]*ChapterInfo
    _dataList []*ChapterInfo
}

func NewTbChapterInfo(_buf []map[string]interface{}) (*TbChapterInfo, error) {
    _dataList := make([]*ChapterInfo, 0, len(_buf))
    dataMap := make(map[int32]*ChapterInfo)

    for _, _ele_ := range _buf {
        if _v, err2 := NewChapterInfo(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.KeyId] = _v
        }
    }
    return &TbChapterInfo{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbChapterInfo) GetDataMap() map[int32]*ChapterInfo {
    return table._dataMap
}

func (table *TbChapterInfo) GetDataList() []*ChapterInfo {
    return table._dataList
}

func (table *TbChapterInfo) Get(key int32) *ChapterInfo {
    return table._dataMap[key]
}


