
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbErrorCode struct {
    _dataMap map[int32]*ErrorCode
    _dataList []*ErrorCode
}

func NewTbErrorCode(_buf []map[string]interface{}) (*TbErrorCode, error) {
    _dataList := make([]*ErrorCode, 0, len(_buf))
    dataMap := make(map[int32]*ErrorCode)

    for _, _ele_ := range _buf {
        if _v, err2 := NewErrorCode(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbErrorCode{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbErrorCode) GetDataMap() map[int32]*ErrorCode {
    return table._dataMap
}

func (table *TbErrorCode) GetDataList() []*ErrorCode {
    return table._dataList
}

func (table *TbErrorCode) Get(key int32) *ErrorCode {
    return table._dataMap[key]
}


