
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type TBFloatArrayParam struct {
    UpdateType int32
    Value []float32
}

const TypeId_TBFloatArrayParam = 1968817378

func (*TBFloatArrayParam) GetTypeId() int32 {
    return 1968817378
}

func NewTBFloatArrayParam(_buf map[string]interface{}) (_v *TBFloatArrayParam, err error) {
    _v = &TBFloatArrayParam{}
    { var _ok_ bool; var __json_UpdateType__ interface{}; if __json_UpdateType__, _ok_ = _buf["UpdateType"]; !_ok_ || __json_UpdateType__ == nil { err = errors.New("UpdateType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_UpdateType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UpdateType = __x__ }}
    { var _ok_ bool; var __json_value__ interface{}; if __json_value__, _ok_ = _buf["value"]; !_ok_ || __json_value__ == nil { err = errors.New("value error"); return } else { var __x__ []float32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_value__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]float32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ float32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = float32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Value = __x__ }}
    return
}

