
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type TBFloatParam struct {
    UpdateType int32
    Value float32
}

const TypeId_TBFloatParam = 580539551

func (*TBFloatParam) GetTypeId() int32 {
    return 580539551
}

func NewTBFloatParam(_buf map[string]interface{}) (_v *TBFloatParam, err error) {
    _v = &TBFloatParam{}
    { var _ok_ bool; var __json_UpdateType__ interface{}; if __json_UpdateType__, _ok_ = _buf["UpdateType"]; !_ok_ || __json_UpdateType__ == nil { err = errors.New("UpdateType error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_UpdateType__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UpdateType = __x__ }}
    { var _ok_ bool; var __json_value__ interface{}; if __json_value__, _ok_ = _buf["value"]; !_ok_ || __json_value__ == nil { err = errors.New("value error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_value__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Value = __x__ }}
    return
}

