
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbGlobal struct {
    _dataMap map[int32]*Global
    _dataList []*Global
}

func NewTbGlobal(_buf []map[string]interface{}) (*TbGlobal, error) {
    _dataList := make([]*Global, 0, len(_buf))
    dataMap := make(map[int32]*Global)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGlobal(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Start] = _v
        }
    }
    return &TbGlobal{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbGlobal) GetDataMap() map[int32]*Global {
    return table._dataMap
}

func (table *TbGlobal) GetDataList() []*Global {
    return table._dataList
}

func (table *TbGlobal) Get(key int32) *Global {
    return table._dataMap[key]
}


