
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbHeroLevel struct {
    _dataMap map[int32]*HeroLevel
    _dataList []*HeroLevel
}

func NewTbHeroLevel(_buf []map[string]interface{}) (*TbHeroLevel, error) {
    _dataList := make([]*HeroLevel, 0, len(_buf))
    dataMap := make(map[int32]*HeroLevel)

    for _, _ele_ := range _buf {
        if _v, err2 := NewHeroLevel(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Level] = _v
        }
    }
    return &TbHeroLevel{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbHeroLevel) GetDataMap() map[int32]*HeroLevel {
    return table._dataMap
}

func (table *TbHeroLevel) GetDataList() []*HeroLevel {
    return table._dataList
}

func (table *TbHeroLevel) Get(key int32) *HeroLevel {
    return table._dataMap[key]
}


