
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbJump struct {
    _dataMap map[int32]*Jump
    _dataList []*Jump
}

func NewTbJump(_buf []map[string]interface{}) (*TbJump, error) {
    _dataList := make([]*Jump, 0, len(_buf))
    dataMap := make(map[int32]*Jump)

    for _, _ele_ := range _buf {
        if _v, err2 := NewJump(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.UIID] = _v
        }
    }
    return &TbJump{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbJump) GetDataMap() map[int32]*Jump {
    return table._dataMap
}

func (table *TbJump) GetDataList() []*Jump {
    return table._dataList
}

func (table *TbJump) Get(key int32) *Jump {
    return table._dataMap[key]
}


