
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbLottery struct {
    _dataMap map[int32]*Lottery
    _dataList []*Lottery
}

func NewTbLottery(_buf []map[string]interface{}) (*TbLottery, error) {
    _dataList := make([]*Lottery, 0, len(_buf))
    dataMap := make(map[int32]*Lottery)

    for _, _ele_ := range _buf {
        if _v, err2 := NewLottery(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &TbLottery{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbLottery) GetDataMap() map[int32]*Lottery {
    return table._dataMap
}

func (table *TbLottery) GetDataList() []*Lottery {
    return table._dataList
}

func (table *TbLottery) Get(key int32) *Lottery {
    return table._dataMap[key]
}


