
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbLucky struct {
    _dataMap map[int32]*Lucky
    _dataList []*Lucky
}

func NewTbLucky(_buf []map[string]interface{}) (*TbLucky, error) {
    _dataList := make([]*Lucky, 0, len(_buf))
    dataMap := make(map[int32]*Lucky)

    for _, _ele_ := range _buf {
        if _v, err2 := NewLucky(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ID] = _v
        }
    }
    return &TbLucky{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbLucky) GetDataMap() map[int32]*Lucky {
    return table._dataMap
}

func (table *TbLucky) GetDataList() []*Lucky {
    return table._dataList
}

func (table *TbLucky) Get(key int32) *Lucky {
    return table._dataMap[key]
}


