
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbMail struct {
    _dataMap map[int32]*Mail
    _dataList []*Mail
}

func NewTbMail(_buf []map[string]interface{}) (*TbMail, error) {
    _dataList := make([]*Mail, 0, len(_buf))
    dataMap := make(map[int32]*Mail)

    for _, _ele_ := range _buf {
        if _v, err2 := NewMail(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.MailID] = _v
        }
    }
    return &TbMail{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbMail) GetDataMap() map[int32]*Mail {
    return table._dataMap
}

func (table *TbMail) GetDataList() []*Mail {
    return table._dataList
}

func (table *TbMail) Get(key int32) *Mail {
    return table._dataMap[key]
}


