
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbPlayerDecor struct {
    _dataMap map[int32]*PlayerDecor
    _dataList []*PlayerDecor
}

func NewTbPlayerDecor(_buf []map[string]interface{}) (*TbPlayerDecor, error) {
    _dataList := make([]*PlayerDecor, 0, len(_buf))
    dataMap := make(map[int32]*PlayerDecor)

    for _, _ele_ := range _buf {
        if _v, err2 := NewPlayerDecor(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.PersonResID] = _v
        }
    }
    return &TbPlayerDecor{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbPlayerDecor) GetDataMap() map[int32]*PlayerDecor {
    return table._dataMap
}

func (table *TbPlayerDecor) GetDataList() []*PlayerDecor {
    return table._dataList
}

func (table *TbPlayerDecor) Get(key int32) *PlayerDecor {
    return table._dataMap[key]
}


