
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbSignIn struct {
    _dataMap map[int32]*SignIn
    _dataList []*SignIn
}

func NewTbSignIn(_buf []map[string]interface{}) (*TbSignIn, error) {
    _dataList := make([]*SignIn, 0, len(_buf))
    dataMap := make(map[int32]*SignIn)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSignIn(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.FuncID] = _v
        }
    }
    return &TbSignIn{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbSignIn) GetDataMap() map[int32]*SignIn {
    return table._dataMap
}

func (table *TbSignIn) GetDataList() []*SignIn {
    return table._dataList
}

func (table *TbSignIn) Get(key int32) *SignIn {
    return table._dataMap[key]
}


