
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type TBSkillParamData struct {
    Attribute string
    Param interface{}
}

const TypeId_TBSkillParamData = 223333524

func (*TBSkillParamData) GetTypeId() int32 {
    return 223333524
}

func NewTBSkillParamData(_buf map[string]interface{}) (_v *TBSkillParamData, err error) {
    _v = &TBSkillParamData{}
    { var _ok_ bool; var __json_Attribute__ interface{}; if __json_Attribute__, _ok_ = _buf["Attribute"]; !_ok_ || __json_Attribute__ == nil { err = errors.New("Attribute error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_Attribute__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Attribute = __x__ }}
    { var _ok_ bool; var __json_Param__ interface{}; if __json_Param__, _ok_ = _buf["Param"]; !_ok_ || __json_Param__ == nil { err = errors.New("Param error"); return } else { var __x__ interface{};  { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = __json_Param__.(map[string]interface{}); !_ok_ { err = errors.New("__x__ error"); return }; if __x__, err = NewTBSkillParam(_x_); err != nil { return } }; _v.Param = __x__ }}
    return
}

