
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type TBSkillParam struct {
    UpdateType int32
}

const TypeId_TBSkillParam = -1090036278

func (*TBSkillParam) GetTypeId() int32 {
    return -1090036278
}

func NewTBSkillParam(_buf map[string]interface{}) (interface{}, error) {
    var id string
    var _ok_ bool
    if id, _ok_ = _buf["$type"].(string) ; !_ok_ {
        return nil, errors.New("type id missing")
    }
    switch id {
        case "TBFloatParam": _v, err := NewTBFloatParam(_buf); if err != nil { return nil, errors.New("tbfloatparam") } else { return _v, nil }
        case "TBBoolParam": _v, err := NewTBBoolParam(_buf); if err != nil { return nil, errors.New("tbboolparam") } else { return _v, nil }
        case "TBFloatArrayParam": _v, err := NewTBFloatArrayParam(_buf); if err != nil { return nil, errors.New("tbfloatarrayparam") } else { return _v, nil }
        default: return nil, errors.New("unknown type id")
    }
}


