
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TbTask struct {
    _dataMap map[int32]*Task
    _dataList []*Task
}

func NewTbTask(_buf []map[string]interface{}) (*TbTask, error) {
    _dataList := make([]*Task, 0, len(_buf))
    dataMap := make(map[int32]*Task)

    for _, _ele_ := range _buf {
        if _v, err2 := NewTask(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.TaskID] = _v
        }
    }
    return &TbTask{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbTask) GetDataMap() map[int32]*Task {
    return table._dataMap
}

func (table *TbTask) GetDataList() []*Task {
    return table._dataList
}

func (table *TbTask) Get(key int32) *Task {
    return table._dataMap[key]
}


