
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


type TBTreasureChestPoints struct {
    _dataMap map[int32]*DataTreasureChestPoints
    _dataList []*DataTreasureChestPoints
}

func NewTBTreasureChestPoints(_buf []map[string]interface{}) (*TBTreasureChestPoints, error) {
    _dataList := make([]*DataTreasureChestPoints, 0, len(_buf))
    dataMap := make(map[int32]*DataTreasureChestPoints)

    for _, _ele_ := range _buf {
        if _v, err2 := NewDataTreasureChestPoints(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TBTreasureChestPoints{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TBTreasureChestPoints) GetDataMap() map[int32]*DataTreasureChestPoints {
    return table._dataMap
}

func (table *TBTreasureChestPoints) GetDataList() []*DataTreasureChestPoints {
    return table._dataList
}

func (table *TBTreasureChestPoints) Get(key int32) *DataTreasureChestPoints {
    return table._dataMap[key]
}


