
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Vip_benefitVipBenefit struct {
    Id int32
    CoinGet string
    CoinIncome string
    Atk string
    Zs string
    Hp string
    Js string
    FriendNum string
    MarketRefresh string
}

const TypeId_Vip_benefitVipBenefit = 23769843

func (*Vip_benefitVipBenefit) GetTypeId() int32 {
    return 23769843
}

func NewVip_benefitVipBenefit(_buf map[string]interface{}) (_v *Vip_benefitVipBenefit, err error) {
    _v = &Vip_benefitVipBenefit{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_coin_get__ interface{}; if __json_coin_get__, _ok_ = _buf["coin_get"]; !_ok_ || __json_coin_get__ == nil { err = errors.New("coin_get error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_coin_get__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CoinGet = __x__ }}
    { var _ok_ bool; var __json_coin_income__ interface{}; if __json_coin_income__, _ok_ = _buf["coin_income"]; !_ok_ || __json_coin_income__ == nil { err = errors.New("coin_income error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_coin_income__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CoinIncome = __x__ }}
    { var _ok_ bool; var __json_atk__ interface{}; if __json_atk__, _ok_ = _buf["atk"]; !_ok_ || __json_atk__ == nil { err = errors.New("atk error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_atk__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Atk = __x__ }}
    { var _ok_ bool; var __json_zs__ interface{}; if __json_zs__, _ok_ = _buf["zs"]; !_ok_ || __json_zs__ == nil { err = errors.New("zs error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_zs__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Zs = __x__ }}
    { var _ok_ bool; var __json_hp__ interface{}; if __json_hp__, _ok_ = _buf["hp"]; !_ok_ || __json_hp__ == nil { err = errors.New("hp error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_hp__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Hp = __x__ }}
    { var _ok_ bool; var __json_js__ interface{}; if __json_js__, _ok_ = _buf["js"]; !_ok_ || __json_js__ == nil { err = errors.New("js error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_js__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Js = __x__ }}
    { var _ok_ bool; var __json_friend_num__ interface{}; if __json_friend_num__, _ok_ = _buf["friend_num"]; !_ok_ || __json_friend_num__ == nil { err = errors.New("friend_num error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_friend_num__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.FriendNum = __x__ }}
    { var _ok_ bool; var __json_market_refresh__ interface{}; if __json_market_refresh__, _ok_ = _buf["market_refresh"]; !_ok_ || __json_market_refresh__ == nil { err = errors.New("market_refresh error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_market_refresh__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.MarketRefresh = __x__ }}
    return
}

