
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package docpb;


import "errors"

type Weapon struct {
    WeaponId int32
    WeaponGroupId int32
    WeaponLevel int32
    IsDefault int32
    WeaponQuality int32
    UpgradeCost []int32
    NextLevel int32
    AttributeID []int32
    AttributeDes []int32
    AttributeNum []int32
    InitialSkill []int32
    RelatedSkill []int32
}

const TypeId_Weapon = -1707954628

func (*Weapon) GetTypeId() int32 {
    return -1707954628
}

func NewWeapon(_buf map[string]interface{}) (_v *Weapon, err error) {
    _v = &Weapon{}
    { var _ok_ bool; var __json_WeaponId__ interface{}; if __json_WeaponId__, _ok_ = _buf["WeaponId"]; !_ok_ || __json_WeaponId__ == nil { err = errors.New("WeaponId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_WeaponId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.WeaponId = __x__ }}
    { var _ok_ bool; var __json_WeaponGroupId__ interface{}; if __json_WeaponGroupId__, _ok_ = _buf["WeaponGroupId"]; !_ok_ || __json_WeaponGroupId__ == nil { err = errors.New("WeaponGroupId error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_WeaponGroupId__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.WeaponGroupId = __x__ }}
    { var _ok_ bool; var __json_WeaponLevel__ interface{}; if __json_WeaponLevel__, _ok_ = _buf["WeaponLevel"]; !_ok_ || __json_WeaponLevel__ == nil { err = errors.New("WeaponLevel error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_WeaponLevel__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.WeaponLevel = __x__ }}
    { var _ok_ bool; var __json_IsDefault__ interface{}; if __json_IsDefault__, _ok_ = _buf["IsDefault"]; !_ok_ || __json_IsDefault__ == nil { err = errors.New("IsDefault error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_IsDefault__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.IsDefault = __x__ }}
    { var _ok_ bool; var __json_WeaponQuality__ interface{}; if __json_WeaponQuality__, _ok_ = _buf["WeaponQuality"]; !_ok_ || __json_WeaponQuality__ == nil { err = errors.New("WeaponQuality error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_WeaponQuality__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.WeaponQuality = __x__ }}
    { var _ok_ bool; var __json_UpgradeCost__ interface{}; if __json_UpgradeCost__, _ok_ = _buf["UpgradeCost"]; !_ok_ || __json_UpgradeCost__ == nil { err = errors.New("UpgradeCost error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_UpgradeCost__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.UpgradeCost = __x__ }}
    { var _ok_ bool; var __json_NextLevel__ interface{}; if __json_NextLevel__, _ok_ = _buf["NextLevel"]; !_ok_ || __json_NextLevel__ == nil { err = errors.New("NextLevel error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_NextLevel__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.NextLevel = __x__ }}
    { var _ok_ bool; var __json_AttributeID__ interface{}; if __json_AttributeID__, _ok_ = _buf["AttributeID"]; !_ok_ || __json_AttributeID__ == nil { err = errors.New("AttributeID error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_AttributeID__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AttributeID = __x__ }}
    { var _ok_ bool; var __json_AttributeDes__ interface{}; if __json_AttributeDes__, _ok_ = _buf["AttributeDes"]; !_ok_ || __json_AttributeDes__ == nil { err = errors.New("AttributeDes error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_AttributeDes__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AttributeDes = __x__ }}
    { var _ok_ bool; var __json_AttributeNum__ interface{}; if __json_AttributeNum__, _ok_ = _buf["AttributeNum"]; !_ok_ || __json_AttributeNum__ == nil { err = errors.New("AttributeNum error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_AttributeNum__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AttributeNum = __x__ }}
    { var _ok_ bool; var __json_InitialSkill__ interface{}; if __json_InitialSkill__, _ok_ = _buf["InitialSkill"]; !_ok_ || __json_InitialSkill__ == nil { err = errors.New("InitialSkill error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_InitialSkill__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.InitialSkill = __x__ }}
    { var _ok_ bool; var __json_RelatedSkill__ interface{}; if __json_RelatedSkill__, _ok_ = _buf["RelatedSkill"]; !_ok_ || __json_RelatedSkill__ == nil { err = errors.New("RelatedSkill error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_RelatedSkill__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.RelatedSkill = __x__ }}
    return
}

