
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


type Week_zhao_muTbWeekZhaoMu struct {
    _dataMap map[int32]*Week_zhao_muWeekZhaoMu
    _dataList []*Week_zhao_muWeekZhaoMu
}

func NewWeek_zhao_muTbWeekZhaoMu(_buf []map[string]interface{}) (*Week_zhao_muTbWeekZhaoMu, error) {
    _dataList := make([]*Week_zhao_muWeekZhaoMu, 0, len(_buf))
    dataMap := make(map[int32]*Week_zhao_muWeekZhaoMu)

    for _, _ele_ := range _buf {
        if _v, err2 := NewWeek_zhao_muWeekZhaoMu(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Week_zhao_muTbWeekZhaoMu{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Week_zhao_muTbWeekZhaoMu) GetDataMap() map[int32]*Week_zhao_muWeekZhaoMu {
    return table._dataMap
}

func (table *Week_zhao_muTbWeekZhaoMu) GetDataList() []*Week_zhao_muWeekZhaoMu {
    return table._dataList
}

func (table *Week_zhao_muTbWeekZhaoMu) Get(key int32) *Week_zhao_muWeekZhaoMu {
    return table._dataMap[key]
}


