
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package GameConfig;


import "errors"

type Week_zhao_muWeekZhaoMu struct {
    Id int32
    Value int32
    Description string
    Points int32
    Rewards string
}

const TypeId_Week_zhao_muWeekZhaoMu = 1809524454

func (*Week_zhao_muWeekZhaoMu) GetTypeId() int32 {
    return 1809524454
}

func NewWeek_zhao_muWeekZhaoMu(_buf map[string]interface{}) (_v *Week_zhao_muWeekZhaoMu, err error) {
    _v = &Week_zhao_muWeekZhaoMu{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_value__ interface{}; if __json_value__, _ok_ = _buf["value"]; !_ok_ || __json_value__ == nil { err = errors.New("value error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_value__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Value = __x__ }}
    { var _ok_ bool; var __json_description__ interface{}; if __json_description__, _ok_ = _buf["description"]; !_ok_ || __json_description__ == nil { err = errors.New("description error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_description__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Description = __x__ }}
    { var _ok_ bool; var __json_points__ interface{}; if __json_points__, _ok_ = _buf["points"]; !_ok_ || __json_points__ == nil { err = errors.New("points error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_points__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Points = __x__ }}
    { var _ok_ bool; var __json_rewards__ interface{}; if __json_rewards__, _ok_ = _buf["rewards"]; !_ok_ || __json_rewards__ == nil { err = errors.New("rewards error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_rewards__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Rewards = __x__ }}
    return
}

